### ISSUE TITLE
一些小建议

### ISSUE THREAD

**Issue by Minelu** [xushengfeng/eSearch#1]
希望大佬可以增加保存截图时的默认格式。和取色器一键复制默认格式色值的功能

**Comment by xushengfeng** [comment]
好啊

**Comment by xushengfeng** [comment]
已添加 
[可设定保存默认格式](https://github.com/xushengfeng/eSearch/commit/16fa357aeb09e55397b024b40d055452908b2566)
[快捷键复制默认格式颜色](https://github.com/xushengfeng/eSearch/commit/78b81a4e7e4cf2c94d6298ee8624692d8fc42468)

预计在下周末推送到1.4.5
