### ISSUE TITLE
截屏快捷键无法添加 printscreen

### ISSUE THREAD

**Issue by xushengfeng** [xushengfeng/eSearch#10]

**Comment by xushengfeng** [comment]
临时解决方案：
在设置-高级-高级设置-直接编辑设置源文件（即打开`config.json`），在`快捷键-截屏搜索`添加`"key":"Ctrl+PrintScreen"`

**Comment by XZ1314XZ** [comment]
问题同上，还会出现卡死，多个截图界面出现情况
