### ISSUE TITLE
关于ocr 的建议

### ISSUE THREAD

**Issue by kadxka** [xushengfeng/eSearch#100]
**1.速度慢**
**2.希望增加像微信那样在图片上选择文字的功能**
**举个栗子**
截取图片中黄色部分：
本软件：![63a29f1787a15_63a29f17aa1ce](https://user-images.githubusercontent.com/121008319/208832393-4f320b62-e219-43a1-bb75-a082afbb62d5.gif)
（效率低）
微信（先截图然后直接打开，自动识别文字，拖拽鼠标可以在图片上直接选择文字复制）：
![63a29b12a0574_63a29b12c4d5a](https://user-images.githubusercontent.com/121008319/208832735-4647d674-d742-4e29-8475-a0afc73bcbca.gif)（十分方便~）
3.图片歪了，截取不了或不准
举个栗子
还是刚才那个图片，只不过转了一下（截取图片中黄色部分）：
本软件：
![63a2a1f42ecc1_63a2a2823d7c3](https://user-images.githubusercontent.com/121008319/208834427-426e9fca-e2d2-47ad-8453-751c84c3c2fd.gif)
识别不出来
微信（alt+a截图，框选后点击提取文字，识别准确）：
![63a2a3cdd1f62_63a2a3ce15357](https://user-images.githubusercontent.com/121008319/208834699-fc09cdf2-2adf-4c48-8061-afa2434b127d.gif)
轻松方便

### **_希望作者对照改进~谢谢·~~~~~~~~_**
本人发现微信截图功能挺多，这里没提到的希望作者有时间可以对照改进~

以上仅是建议，如果对本软件没有帮助请忽略

**Comment by xushengfeng** [comment]
关于速度，默认的本地ocr目前已经尽力做到快了，后面我会研究怎么更快的
微信是联网识别的，速度会快一些，本软件也提供了联网ocr的接口（百度的和阿里的）
不同方向文字的识别我会添加的

直接在图片上选择文字，这个我打算开发

**Comment by CXido** [comment]
另外百度的OCR好像有一些问题，标准版 和 高精度版 使用不了，不知道是不是我个人问题，其他的OCR选项都可以使用

**Comment by xushengfeng** [comment]
与图片同步选择已经实现
方向检测暂时不添加
