### ISSUE TITLE
ding在屏幕上大小不是原大小

### ISSUE THREAD

**Issue by sywy52pojie** [xushengfeng/eSearch#101]
1.长按alt+c会出现很多截图界面，。。。
2.ding在屏幕上大小不是原大小
![63a3e69dd75fe_63a3e69e0db1e](https://user-images.githubusercontent.com/114221053/209062494-726053a3-ece0-4ba9-937c-0ef2272b17e1.gif)

**Comment by xushengfeng** [comment]
alt+c 就是截屏一次，长按alt+c**操作系统**会重复触发，就会把截屏界面截屏……不算bug吧

**Comment by xushengfeng** [comment]
9509a61d43f6ad35a382e534928b598707be3b63
