### ISSUE TITLE
贴图缩放和形状bug

### ISSUE THREAD

**Issue by tqllorry** [xushengfeng/eSearch#103]
**描述问题**
框出来图片之后，贴图在屏幕上，缩放（会变得很大）和形状都和框选的不对。
**重现步骤**
1、框选
2、贴图

**屏幕截图**
![屏幕截图 2022-12-23 135852](https://user-images.githubusercontent.com/42569800/209281019-b5acfe0e-22a4-4bc1-9741-a84aee152874.png)
![屏幕截图 2022-12-23 135911](https://user-images.githubusercontent.com/42569800/209281178-5c18e295-e74c-48f3-a0d5-a8a84c01d3d9.png)
![屏幕截图 2022-12-23 140002](https://user-images.githubusercontent.com/42569800/209281189-e550e868-ddf0-4b67-aacc-55e81ecdde28.png)

**设别和软件信息**

-   操作系统和具体版本: win10
-   屏幕参数: 27寸
-   软件版本: 1.9.5,1.9.6都有这个问题，1.9.4就没问题

**更多信息**

**Comment by xushengfeng** [comment]
了解了，这个问题 #101 反馈过了，我会在 #101 反馈修复、开发进度
