### ISSUE TITLE
你好，可否给一个联系方式，我想聊一下商业合作 EasyIsAllYouNeed@foxmai.com  

### ISSUE THREAD

**Issue by EasyIsAllYouNeed** [xushengfeng/eSearch#104]
**设别和软件信息**

-   操作系统和具体版本: [如： Win11 专业版 pre 25158]
-   软件版本: [如：1.7.2]

**请自由地描述你的提议（如有多个不同方向的建议，最好分成几个issue）**

**Comment by xushengfeng** [comment]
商业合作就不用了
