### ISSUE TITLE
截屏BUG-截屏时方向键移动后露出原始屏幕

### ISSUE THREAD

**Issue by sywy52pojie** [xushengfeng/eSearch#105]
截屏时方向键移动后露出原始屏幕。（但如果截屏后放大或缩小屏幕不会出现此问题）
截图：

进行缩放操作：
![进行缩放操作](https://user-images.githubusercontent.com/114221053/210128143-c0e58f04-c44c-41be-8256-48e4b0ab8d19.gif)
不进行缩放操作：
![不进行缩放操作](https://user-images.githubusercontent.com/114221053/210128150-2ca28d6b-5495-4d92-b06e-0606bd5b301d.gif)

**Comment by xushengfeng** [comment]
6165b937c50fd35c0bdc5bf329ee15f96a6be689 已在代码中修复
