### ISSUE TITLE
无法使用托盘的ocr和以图搜图功能

### ISSUE THREAD

**Issue by jinsuichen** [xushengfeng/eSearch#107]
**描述问题**

在程序托盘的列表中点击“OCR（文字识别）”和“以图搜图”两个选项报错

**重现步骤**

1.点击托盘图标

2.选择“OCR（文字识别）”或“以图搜图”两个选项

![image](https://user-images.githubusercontent.com/42372982/210163273-a8c0d0c9-37cc-424a-a050-557518c0a8e0.png)

**本应该**

程序报错，不知道正常情况应该会怎么样

**屏幕截图**

![image](https://user-images.githubusercontent.com/42372982/210163123-08ea38d6-137a-445e-b288-626c46cc433d.png)

**设别和软件信息**

-   操作系统和具体版本: Ubuntu 22.04.1 LTS
-   屏幕参数: 27 寸，2560*1440，1.25 倍缩放
-   软件版本: 1.9.7

**更多信息**

无其他信息

**Comment by xushengfeng** [comment]
截屏是否正常？

**Comment by jinsuichen** [comment]
我使用 Alt + C 的快捷键可以正常唤起截屏并可以正常使用各种功能

**Comment by xushengfeng** [comment]
已在代码中修复： 5dab95d90ff4af9190d90d09f6bb0b842696b623
