### ISSUE TITLE
长截屏白屏

### ISSUE THREAD

**Issue by kadxka** [xushengfeng/eSearch#108]
选区截屏后，点击长截屏后会白屏
![2023-01-03-10-37-55](https://user-images.githubusercontent.com/121008319/210294040-5134c5ac-3334-4b3b-b1d8-c6f674e4b059.gif)

**Comment by xushengfeng** [comment]
点击长截屏按钮后是出现虚线选框了吗？还是直接白屏？

**Comment by xushengfeng** [comment]
我好像没能复现这个错误。
你的总是这样吗

**Comment by kadxka** [comment]
不好意思，刚才试了一下，没有出现以上错误 上次不知道怎么回事😅
打扰您了
