### ISSUE TITLE
添加矩形后再点击矩形，方框丢不掉

### ISSUE THREAD

**Issue by orchiss** [xushengfeng/eSearch#11]
使用【功能-图像编辑-形状文字-矩形、圆】这两个工具
在截图中画好图形，然后点击选区调整位置，选区会一直跟随光标丢不掉
此时ESC无法退出，需del删除矩形选区才能退出截图。
另外，del删除选区后鼠标依然处于调整选区的状态，不能做其他事情，只能结束截图。
（我不清楚是否是我的电脑环境导致的问题，我没有做更多测试，看您能否复现bug吧）
![image](https://user-images.githubusercontent.com/38742331/178913343-d5c4729f-d5b6-4d12-affe-6210e3715f3a.png)

**Comment by xushengfeng** [comment]
出现的概率有多大

**Comment by orchiss** [comment]
只要去点击创建好的矩形，每一次都会出现
