### ISSUE TITLE
部分窗口/编辑界面偏移

### ISSUE THREAD

**Issue by u-Sir** [xushengfeng/eSearch#110]
**描述问题**

**重现步骤**

1. 两个同分辨率但缩放不同的
2. 在外屏截图并添加文字
3. 添加文字的框的位置偏移了，不在截图范围内

或者 执行 OCR，OCR 识别完外屏的内容后的窗口出现在主屏上
**本应该**
显示在截图范围内

**屏幕截图**
可选

**设别和软件信息**

-   操作系统和具体版本: [如： Win11 专业版 22h2]
-   屏幕参数: 15.6 寸，3840*2160，2.50 倍缩放 + 27 寸，3840*2160，1.50 倍缩放
-   软件版本: 1.9.7

**更多信息**

**Comment by xushengfeng** [comment]
主页面出现位置已在代码修复 cd0ee973c439f6191ae9ff3de73e4074d33aa31b
添加文字还未修

**Comment by u-Sir** [comment]
@xushengfeng 好的，‘添加文字’ 只是其中一个，感觉工具条里涉及到位置的有问题，如：添加形状，方形、圆形

**Comment by xushengfeng** [comment]
已在代码修复 e9b855a3fbefe2f6630a1dc41c9640a757ceaf24
