### ISSUE TITLE
建议提供 arm64 安装包下载

### ISSUE THREAD

**Issue by liutun** [xushengfeng/eSearch#111]
现在国家正在大力推广信创，尤其是政府和国企央企，从2022年开始都在大量购置信创电脑，用的最多的是 arm64 架构的飞腾CPU，希望能提供支持 arm64 的deb包下载，谢谢。

**Comment by xushengfeng** [comment]
我发布了一个支持arm64的预览版 https://github.com/xushengfeng/eSearch/releases/tag/1.9.8-beta.3 目前不保证全功能可用性，欢迎继续反馈

**Comment by xushengfeng** [comment]
很抱歉，目前所依赖的截屏库 https://github.com/nashaofu/node-screenshots 暂时不支持linux arm64

**Comment by Xu-Wade** [comment]
作者大大你好，想问下arm64版解压后，后续该如何操作？直接npm install就会找不到node-screenshots版本

**Comment by xushengfeng** [comment]
我在代码里添加了一个功能：可选外部截屏器来截屏
e1c6ec16570cfc1ae3173499ad526b165313acd9

如果可以编译调试代码的话，拉取最新代码，在设置-高级设置里添加命令
比如Flameshot：`flameshot full -p /tmp/img.png `
