### ISSUE TITLE
截图的OCR识别，对于英文字母串会自动加很多空格，这个很不友好

### ISSUE THREAD

**Issue by EastPearlStar2019** [xushengfeng/eSearch#112]
截图的OCR识别中，对于英文字母串会自动加很多空格，这个很不友好。
例如：
https://objectsgithubusercontent.com/github-production-release-asset-2e65be
会被识别成：
https://objects.g it hub user content.com/g
lub-production-release-asset-2e65be
不但加了空格，还自动加了换行。

eSearch.Setup.1.9.7.exe
Windows10

**Comment by xushengfeng** [comment]
234be899ae230ab54d153ff9dc02b12ef1572513 已在代码中修复
