### ISSUE TITLE
最新版本长截图会白屏无法使用

### ISSUE THREAD

**Issue by Fowindy** [xushengfeng/eSearch#113]
**描述问题**

**重现步骤**

1. 在……界面
2. 点击
3. 发生错误

**本应该**
显示 xxx

**屏幕截图**
可选

**设别和软件信息**

-   操作系统和具体版本: [如： Win11 专业版 pre 25158]
-   屏幕参数: [如：15.6 寸，1920*1080，1.25 倍缩放]
-   软件版本: [如：1.7.2]

**更多信息**

**Comment by xushengfeng** [comment]
是beta版本吗？
点击按钮后直接白屏还是拼接完后白屏？

**Comment by Fowindy** [comment]
点击长截图按钮后，滚动鼠标滑轮



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2023年1月6日(周五) 中午12:31
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [xushengfeng/eSearch] 最新版本长截图会白屏无法使用 (Issue #113)




 
是beta版本吗？
 点击按钮后直接白屏还是拼接完后白屏？

**Comment by xushengfeng** [comment]
已尝试在代码中修复 ebcd4dbadc5d4b9fe3d5c55f18a231148ca9156e 并发布了一个预览版本 https://github.com/xushengfeng/eSearch/releases/tag/1.9.8-beta.6
