### ISSUE TITLE
四个问题

### ISSUE THREAD

**Issue by qwertyue** [xushengfeng/eSearch#114]
**描述问题1**
全局快捷键中的选中搜索快捷键设置了，但不触发

**重现步骤**

1. 设置选中搜索的全局快捷键，如Alt + A
2. 选中文字后按下Alt + A
3. 选中搜索的功能没有被触发

**本应该**
弹出浏览器（设置了在浏览器中打开），并且使用我设置的引擎搜索选中文字

**描述问题2**
全局快捷键中的自动识别快捷键设置了Ctrl + Shift + A，在Chrome中使用该组合按键会弹出F12的控制台，同时也能正常弹出截图界面

**重现步骤**

1.  设置自动识别的全局快捷键为Ctrl + Shift + A
2. 在Chrome浏览器中触发该组合快捷键
3. 弹出截图界面，截图完成后会发现F12的控制台界面也被触发了

**本应该**
只弹出截图界面

**描述问题3**
设置中的 浏览器打开后自动关闭标签页 无效？
我认为该选项的含义：选中搜索的内容在我的浏览器（如Chrome）打开，而且不显示eSearch的自带浏览器
可能是我没理解这个选项的含义？

**描述问题4**
关闭设置界面后会在关闭按钮的位置触发右键选项

**重现步骤**
1.  打开设置界面，点击右上角的关闭按钮
2. 此时设置界面被关闭，但是会在关闭按钮的位置弹出菜单栏（即任务栏右击eSearch图标会触发的菜单栏）

**本应该**
关闭设置界面，不弹出菜单栏

**设备和软件信息**

-   操作系统和具体版本:  win10 家庭版 22H2
-   屏幕参数: 2560 x 1600 125%缩放
-   软件版本:  1.9.7

**更多信息**

**Comment by qwertyue** [comment]
对于问题2 好像不少快捷键组合都会导致额外触发

**Comment by xushengfeng** [comment]
选中搜索目前有些问题，触发有点困难，我尝试调节一下。
全局快捷键是由软件注册，操作系统管理，像中断传播这些软件目前实现不了。这种情况建议更换快捷键。
想要在自己的浏览器打开，请设置“浏览器中打开”。自动关闭标签页是指在软件自带浏览器中点击浏览器打开按钮后，关闭自带浏览器的标签页，并通过系统浏览器打开。
第四个是bug，会尝试解决的。

还有，建议多个问题可以开多个issue，这样便于问题追踪

**Comment by xushengfeng** [comment]
已在代码修复第四个问题 3cdf2940817e7b49a4dad5244b45cadd6c556745

**Comment by qwertyue** [comment]
不好意思 作者大大 
第二个问题我才发现漏描述了

**描述问题2**
全局快捷键中的自动识别快捷键设置了Ctrl + Shift + A，在Chrome中使用该组合按键会弹出F12的控制台，同时也能正常弹出截图界面
而且Ctrl + Shift + A是没有任何快捷键的，经尝试，关闭软件后，Ctrl + Shift + A这个组合键在CHrome中无反应

所以这个问题应该是 设定好的快捷键不仅会触发绑定的功能，而且还会触发一些额外的功能。并且关闭软件后使用该组合键，这些额外的功能不会触发

第三个问题我明白了 谢谢作者大大的解答

**Comment by xushengfeng** [comment]
通过快捷触发其他功能（如截屏搜索）会怎么样？

PS：想要只在系统浏览器打开，更直接的方法就是设置浏览器打开，不用再勾选其他
![eSearch-2023-01-08-14-45-43](https://user-images.githubusercontent.com/28475549/211184024-d59b8d9a-475c-4977-b078-fb5e8655fc8c.png)
右键系统托盘勾选浏览器打开也是一样的

**Comment by qwertyue** [comment]
截屏搜索的快捷键触发是正常的
.. 其实我不知道这个功能该怎么用
我认知的是：截图 -> 识别截图中的文字 -> 进行搜索
但是我每次触发截屏搜索后，感觉不知道该按哪才能触发搜索，可以说我把这个功能用成了截图的....

浏览器打开这个
如果只勾选浏览器中打开的话
软件会同时打开两个搜索窗口：
1个是系统浏览器
1个是软件窗口

**Comment by qwertyue** [comment]
截屏搜索的快捷键触发是正常的
.. 其实我不知道这个功能该怎么用
我认知的是：截图 -> 识别截图中的文字 -> 进行搜索
但是我每次触发截屏搜索后，感觉不知道该按哪才能触发搜索，可以说我把这个功能用成了截图的....


同时我对自动识别和截屏搜索的功能有些困惑：
我阅读了教程，查看了自动识别和截屏搜索的定义：
自动识别：如果你选中了屏幕上的某些文字，eSearch将直接搜索它，否则开启文字识别识别屏幕文字。
截屏搜索：识别框选的屏幕内容进行搜索，也可以进行编辑、保存等操作。

我进行了好几次的尝试，无论我是否选中文字，我的自动识别快捷键触发的都是截屏操作
换句话说 自动识别和截屏搜索的功能好像是一样的？
即：**如果你选中了屏幕上的某些文字，eSearch将直接搜索它**  这个功能好像没有实现

**Comment by xushengfeng** [comment]
也许是选中检测这块出了问题，我会尝试修复的

截屏后要手动点击ocr按钮检测文字

**Comment by qwertyue** [comment]
> 也许是选中检测这块出了问题，我会尝试修复的
> 
> 截屏后要手动点击ocr按钮检测文字



> 浏览器打开这个 如果只勾选浏览器中打开的话 软件会同时打开两个搜索窗口： 1个是系统浏览器 1个是软件窗口


这个功能可以麻烦您进行一下更新吗
就是勾选了浏览器打开的话 
就只在系统浏览器里显示搜索结果，而不用在软件窗口中也打开了

**Comment by qwertyue** [comment]
目前我是1.98版本
问题4已经没有了


但是关于问题2 我有了新的发现

我之前提到
**设定好的快捷键不仅会触发绑定的功能，而且还会触发一些额外的功能。并且关闭软件后使用该组合键，这些额外的功能不会触发**

我测试了下别的几个设定，如设置截屏搜索或者主界面、剪贴板搜索的快捷键为Ctrl+Shift+A，它们都不会触发额外的功能（如chrome弹出F12控制台）

只有自动识别设置了快捷键之后，会触发一些额外的功能

**Comment by xushengfeng** [comment]
> > 也许是选中检测这块出了问题，我会尝试修复的
> > 截屏后要手动点击ocr按钮检测文字
> 
> > 浏览器打开这个 如果只勾选浏览器中打开的话 软件会同时打开两个搜索窗口： 1个是系统浏览器 1个是软件窗口
> 
> 这个功能可以麻烦您进行一下更新吗 就是勾选了浏览器打开的话 就只在系统浏览器里显示搜索结果，而不用在软件窗口中也打开了

你说的软件窗口是指主页面（就是可以编辑文字的那个界面）吗？
如果ocr之类的完成后肯定要打开主页面的，因为ocr识别后的文字大多要编辑和复制，当然开启失焦关闭和自动搜索后一般也不显示主页面
如果从选中搜索唤起主页面的话，我认为失焦关闭也能做到不显示主页面

**Comment by xushengfeng** [comment]
感谢你的持续反馈！
目前自动搜索和选中搜索确实有些问题，我会尝试修复

**Comment by xushengfeng** [comment]
自动搜索和选中搜索已在 https://github.com/xushengfeng/eSearch/releases/tag/1.10.1-beta.2 修复
