### ISSUE TITLE
无法使用托盘的ocr和以图搜图功能的错误未能解决

### ISSUE THREAD

**Issue by jinsuichen** [xushengfeng/eSearch#115]
在 1.9.7 版本时，我发现无法使用托盘的 ocr 和以图搜图功能，并提交 #107 

在 1.9.8 新版本中，该问题依然存在，并未被解决。重现步骤、屏幕截图、设别和软件信息见 #107

**Comment by xushengfeng** [comment]
我测试了一下，若开启浏览器打开，则会闪退。你开启了吗？关闭后试一下。
对此我会尝试修复

**Comment by jinsuichen** [comment]
> 我测试了一下，若开启浏览器打开，则会闪退。你开启了吗？关闭后试一下。 对此我会尝试修复

无论是否开启设置中的“浏览器中打开”选项，结果均是 #107 中提到的报错，并不会闪退。

**Comment by xushengfeng** [comment]
我目前在22.04.1上无法重现
尝试重新下载软件安装？之前的官网存在一个错误，导致无法下载新版本的eSearch，不过现在修复了。你在设置中检查一下软件版本是否是1.9.8？按理来说，#107 截图中的错误已解决，你现在的报错与之前是否一样？

**Comment by jinsuichen** [comment]
之前已经多次尝试重转软件，并未解决问题。软件版本为1.9.8。现在的报错与之前一致。

我的ubuntu版本

![image](https://user-images.githubusercontent.com/42372982/212133575-280b13ce-341c-4483-a808-5c4365facd11.png)

bug复现视频

https://user-images.githubusercontent.com/42372982/212133328-fc376e3f-700e-4ab6-a840-7aea003e6181.mp4

**Comment by xushengfeng** [comment]
尝试修复： 2d2cf6575578e110a245c29bee4059ab17db3004
https://github.com/xushengfeng/eSearch/releases/tag/1.10.0-beta.1

**Comment by jinsuichen** [comment]
这个版本不会报错。
但是 ocr 和以图搜图这两个功能均截取显示器的整个界面进行操作，不知道这是否为正常的逻辑。如果是的话，此问题得以修复。

**Comment by xushengfeng** [comment]
托盘快捷针对全屏，这个逻辑没错:)
