### ISSUE TITLE
无法把截图钉在外屏上屏幕

### ISSUE THREAD

**Issue by u-Sir** [xushengfeng/eSearch#117]
在外屏中截图，选择钉住

屏幕信息：3840 2160 2.5 和 38402160 1.5
windows 11 22h2

**Comment by xushengfeng** [comment]
是在主屏上出现还是消失了

**Comment by u-Sir** [comment]
> 是在主屏上出现还是消失了

消失了吧，点击钉住后只有一个长条，点击长条就看到临时保存的图标
![图片](https://user-images.githubusercontent.com/93647031/211769335-ce155b87-8023-4fd2-81dc-5007d1b7e7ff.png)
