### ISSUE TITLE
希望可以添加截图选定范围内左键双击直接复制

### ISSUE THREAD

**Issue by qwertyue** [xushengfeng/eSearch#119]
现在目前比较流行的
QQ截图
微信截图
Snipaste

这些软件都是支持左键在框选范围内双击直接复制（即快捷键->截图->复制）功能
所以希望eSearch也可以支持这一功能

**Comment by xushengfeng** [comment]
046cb2a8e6434b2b9a0f432cd22fdeb3789668da
