### ISSUE TITLE
期待改善的地方

### ISSUE THREAD

**Issue by Super-Zoe** [xushengfeng/eSearch#12]
希望能够增加的功能：
1. 增加**多个OCR接口选择**(例如腾讯云OCR，讯飞OCR等)，当然增加**多个翻译接口**也行~
2. 增加 **功能开关** 例如没有用到取色器 可以将其关闭

不知道是不是bug（window平台的）：
1. 点击 **OCR识别** 有时会跳到 **搜索** 有时会跳到 **翻译**
2. 点击 **搜索** 则提示 A JavaScript error occurred in the main process **Error :Cannot find module 'form-data'**
3. 贴图后 选择最小化 然后不知道藏到哪里去了

**Comment by xushengfeng** [comment]
ocr会慢慢加的（现在主要是又实名又付费的，不好调试）

功能开关不加，因为太多了

如果不想自动跳转，可以在设置关闭 `搜索-自动-自动搜索`

搜索错误是以图搜图时选了google吧，这个是bug，准备修

贴图最小化后，屏幕左上角有dock栏，点击它就出现最小化的贴图了

**Comment by xushengfeng** [comment]
1. 我或许可以搞
2. 应该与 #6 是同一个bug
3. 后面会出配置等目录的自定义路径

**Comment by xushengfeng** [comment]
才想起来，取色器可以在 设置-取色器-大小 里调节，也能起到隐藏效果吧

**Comment by Super-Zoe** [comment]
嗯嗯 但之前也有试了一下 效果不是很好

**Comment by xushengfeng** [comment]
隐藏取色器可[下载](https://esearch.vercel.app/plugin.html)相关插件
谷歌搜图错误、ocr错误和自定义配置路径已在[1.7.3](https://github.com/xushengfeng/eSearch/releases/tag/1.7.3)修复实现
