### ISSUE TITLE
双屏幕截图异常

### ISSUE THREAD

**Issue by qwertyue** [xushengfeng/eSearch#120]
**背景**
笔记本外接了一台3440x1440、缩放率为150%的显示器
同时笔记本合盖状态，只使用了外接显示旗做界面展示

**描述问题**
在触发截图的时候，会默认选中当前屏幕（外接显示器屏幕）大小，这应该是不正常的
而且在点击复制/保存之后，保存的内容是黑的（内存的分辨率大小等信息都是正常的）

**本应该**
1、触发截图的时候，不应该默认框选我整个外接显示器屏幕大小
2、保存的内容不应该是黑的

**屏幕截图**

**设备和软件信息**

-   操作系统和具体版本:
-   屏幕1参数: 3440 x 1440 缩放率150%   （主屏幕，在显示设置中设置为主屏幕）
-   屏幕2参数: 1920 x 1080 缩放率 125% （笔记本屏幕，合盖状态，未使用）
-   软件版本: 1.9.8
-   操作系统: win10 21H2

**更多信息**

**Comment by xushengfeng** [comment]
是拓展屏幕还是使用复制屏幕模式？

**Comment by qwertyue** [comment]
> 是拓展屏幕还是使用复制屏幕模式？

扩展屏幕

**Comment by qwertyue** [comment]
> 是拓展屏幕还是使用复制屏幕模式？

我才发现一件挺奇怪的事情

我之前写了一句
"如果笔记本不进入合盖状态，双屏同时使用则无上述问题"
是因为我另一套电脑的配置就是笔记本+扩展屏 笔记本不合盖使用的（这两台的分辨率分别是2560x1440 和 2560x1600 都是125%缩放率）

目前这一套好像合盖与不合盖使用都有问题  难道是因为分辨率和缩放率差距太大了？

**Comment by qwertyue** [comment]
我又测试了一下
如果我把外接显示器的缩放率设置为125%，与合盖笔记本的缩放率保持一致
那么按下截图快捷键自动框选整个屏幕的问题就没有了

但是截图的内容依然是黑的

**Comment by qwertyue** [comment]
Ding 在屏幕上 

这个功能也失效了
选中范围后点击钉在屏幕上选项
截图就结束了 但是图也没被钉上

**Comment by xushengfeng** [comment]
你说的“自动框选整个屏幕”是怎么样子的？eSearch截屏时默认框选整个屏幕，无论多屏与否

**Comment by qwertyue** [comment]
> 

没错 就是这个意思 
当我的外接显示器缩放率与笔记本缩放率不一致的时候，截屏时默认框选了整个屏幕
如果保持一致的话，则不会默认框选整个屏幕

不过这两种情况截屏保存的内容都是黑的

**Comment by xushengfeng** [comment]
https://github.com/xushengfeng/eSearch/releases/tag/1.10.0-beta.4 我试着在这个版本修复，看看解决了吗

**Comment by qwertyue** [comment]
> https://github.com/xushengfeng/eSearch/releases/tag/1.10.0-beta.4 我试着在这个版本修复，看看解决了吗

经测试没有问题了
