### ISSUE TITLE
双屏幕录制视频异常

### ISSUE THREAD

**Issue by qwertyue** [xushengfeng/eSearch#121]
**背景**
笔记本外接了一台3440x1440、缩放率为150%的显示器
同时笔记本合盖状态，只使用了外接显示器做界面展示

**描述问题**
框选范围后点击录制选项，开始进入录制状态
完成录制后在参数设置界面（码率、帧率、保存界面）发现录制视频的范围并不是我框选的范围

**本应该**
录制视频的范围应该与我框选的范围一致

**屏幕截图**

**设备和软件信息**

-   操作系统和具体版本:
-   屏幕1参数: 3440 x 1440 缩放率150%   （主屏幕，在显示设置中设置为主屏幕）
-   屏幕2参数: 1920 x 1080 缩放率 125% （笔记本屏幕，合盖状态，未使用）
-   软件版本: 1.9.8
-   操作系统: win10 21H2

**更多信息**

**Comment by qwertyue** [comment]
这个问题也是扩展屏幕

**Comment by klay2019** [comment]
双屏下，默认最佳DPI就没问题，换了缩放截图录屏就不行了，难受。

**Comment by qwertyue** [comment]
在[1.10.0-beta.4](https://github.com/xushengfeng/eSearch/releases/tag/1.10.0-beta.4) 这个版本也没问题了
