### ISSUE TITLE
无法启动，提示“A JavaScript error occurred in the main process”（此问题已解决，提供一个参考方法）

### ISSUE THREAD

**Issue by duxueminsi** [xushengfeng/eSearch#123]
背景是我更新了win11的12月补丁，并脑残的使用了腾讯管家深度清理功能。结果，问题①如图：
![image](https://user-images.githubusercontent.com/74960379/213297862-1e8cb19c-0c9f-456a-9af2-5980a1726363.png)
同时，②PS、AI无法打开，③鼠标右键“acrobat合并文件”选项消失…
邮件咨询后，作者建议安装依赖库，后证明与此bug无关。
![image](https://user-images.githubusercontent.com/74960379/213298971-0000286d-c62c-45fd-a5a8-dfd4aa81b056.png)
搜索发现，其他软件也有“A JavaScript error occurred in the main process”提示并无法启动的问题。
一种方法是重装，可以解决③，但对①②无效。
另一种方法是运行兼容性疑难解答，这个方法可以解决①的无法启动问题，但是不能开机自启；同样②也可以启动，但不能拖拽打开文件。
针对问题②，找到以下解决方法
https://blog.csdn.net/qq_42229253/article/details/108765734
参考操作后，①②问题完全解决！

**Comment by xushengfeng** [comment]
感谢提供解决方案！
