### ISSUE TITLE
使用热键进行自动识别时会反复切换numlock开关状态，影响使用效率

### ISSUE THREAD

**Issue by willhsueh** [xushengfeng/eSearch#124]
**描述问题**

**重现步骤**

1. 在Windows11任意界面
2. 点击alt+c进行自动识别
3. 会来回切换numlock键盘开关状态（因为安装了罗技的Logi Options+，每次切换numlock状态会在屏幕上会有切换状态显示，会出现在截图内，影响正常使用效率）

**本应该**
不对numlock数字键盘开关状态进行切换

**屏幕截图**
![图片](https://user-images.githubusercontent.com/65895489/213936448-35027a98-1568-4f92-bcc7-bc99cabaca16.png)

**设备和软件信息**

-   操作系统和具体版本: Windows 11 专业工作站版 22H2 22621.1105
-   屏幕参数:
- 屏幕排列如下：
- 
![图片](https://user-images.githubusercontent.com/65895489/213936703-6da3dd45-24a6-494b-b3e8-e432c8b4f0fd.png)

-   软件版本: 1.9.8

**更多信息**

**Comment by xushengfeng** [comment]
尝试修改快捷键，是否还会切换numlock？
按理应该不会影响numlock

**Comment by qwertyue** [comment]
> 尝试修改快捷键，是否还会切换numlock？ 按理应该不会影响numlock

这个问题我好像之前也提过 就是自动识别的快捷键会额外触发一些别的操作
我之前是chrome界面用ctrl+shift+A触发 结果它给我还打开了F12控制台

**Comment by Koizumikanon** [comment]
> 尝试修改快捷键，是否还会切换numlock？ 按理应该不会影响numlock
![image](https://user-images.githubusercontent.com/79064716/217450076-dad0c920-d787-4512-867c-990ba465a723.png)
1.10.0-beta.2版本仍存在该问题，我的电脑是联想，Win10专业工作站版，安装了联想官方热键管理插件。
由于联想的NumLock图标较大，已经严重影响现在的使用，而之前的版本并未出现这种情况。

已经测试，在我的平台上修改快捷键仍会导致该问题。望重视，谢谢。

**Comment by qwertyue** [comment]
> 

可以使用截屏搜索的快捷键先用着

**Comment by Koizumikanon** [comment]
> > 
> 
> 可以使用截屏搜索的快捷键先用着

学到了，感谢回复，至少在快捷键截屏方面功能是一样的。

**Comment by sun868102** [comment]
测试了用截图搜索代替确实可以的，不会触发 Numlock。

比如已经录入了Alt+C作为自动识别的快捷键。在其中快捷键录入里输入Alt+C 会多识别出 Ctrl 和 Numlock
![image](https://user-images.githubusercontent.com/3632792/236610968-fe848828-a28d-41d2-8890-a51a312bd8fa.png)
#162

**Comment by xushengfeng** [comment]
自动识别是通过在 运行目录 下的`copy.vbs`中调用WScript来模拟按下<kbd>ctrl</kbd>+<kbd>c</kbd>实现的
当从https://github.com/xushengfeng/eSearch/issues/124#issuecomment-1537081817 图中发现其实按下了<kbd>ctrl</kbd>+<kbd>numberlock</kbd>

我怀疑是代码中多了一个`{}`，现在修复如下 117e8f95e1564b8ab208cb4cf9fb97c49802b193

https://github.com/xushengfeng/eSearch/releases/tag/1.10.1-beta.1 欢迎大家测试

**Comment by u-Sir** [comment]
![图片](https://user-images.githubusercontent.com/93647031/236630162-62b6374a-8ca0-4922-974c-8dbb8d4c5a29.png)
1.10.1-beta.1 还是会出现

**Comment by xushengfeng** [comment]
再次修复 aae54d63aa4c784630aa52ea2340284f1005233d
https://github.com/xushengfeng/eSearch/releases/tag/1.10.1-beta.2
