### ISSUE TITLE
OCR识别结果窗口，快捷键ctrl+x剪切不成功

### ISSUE THREAD

**Issue by zxxxxxz8** [xushengfeng/eSearch#125]
**描述问题**
截图后使用OCR识别功能，在弹出的识别结果窗口，直接按ctrl+x剪切，识别结果窗口显示已经剪切成功，但是到别的地方粘贴会发现其实没有剪切成功。但是使用ctrl+c 复制，或者按工具栏的剪切复制按钮，却能显示成功剪切复制。

**设备和软件信息**
win10 , x64

软件版本:1.9.8

**Comment by xushengfeng** [comment]
12f238cf5b8bbcc4d93d6eda9300d479c5e39152
