### ISSUE TITLE
1.10.0-beta.2存在长截屏的问题

### ISSUE THREAD

**Issue by zqxathz** [xushengfeng/eSearch#129]
**描述问题**
首次启动后长截屏功能正常，打开设置后再关闭设置后，长截屏功能无法正常显示截屏框和小红点，需要重启软件后恢复
长截屏进行中按ESC键取消后再次长截屏，无法正常使用

**重现步骤**
同上

**屏幕截图**

**设备和软件信息**

-   操作系统和具体版本: WINDOWS 11 
-   屏幕参数:4K、150%缩放，单屏
-   软件版本:1.10.0-beta.1 1.10.0-beta.2

**更多信息**

**Comment by ThreeAurora** [comment]
同上

**Comment by xushengfeng** [comment]
尝试修复esc长截屏问题 7d9648ea1b3b7b0243b7e07e31876cf34db695e5
