### ISSUE TITLE
无法以开发模式启动项目

### ISSUE THREAD

**Issue by jinsuichen** [xushengfeng/eSearch#130]
**描述问题**

fork仓库并clone到本地后无法正常启动项目。

命令行内容如下

```bash
/usr/local/bin/pnpm run dev

> eSearch@1.10.0-beta.2 dev /home/jinsuichen/WebstormProjects/eSearch
> electron-vite --ignoreConfigWarning dev

vite v4.0.4 building for development...
transforming (1) src/main/main.tsUse of eval in "src/main/main.ts" is strongly discouraged as it poses security risks and may cause issues with minification.
Use of eval in "src/main/main.ts" is strongly discouraged as it poses security risks and may cause issues with minification.
Use of eval in "src/main/main.ts" is strongly discouraged as it poses security risks and may cause issues with minification.
✓ 4 modules transformed.
out/main/main.js  139.42 kB

build the electron main process successfully

-----

dev server running for the electron renderer process at:

  ➜  Local:   http://localhost:5173/
  ➜  Network: use --host to expose

start electron app...

Process finished with exit code 0
```

其中提示```start electron app...```后停顿一秒后，立刻显示 ```Process finished with exit code 0```

**重现步骤**

1. fork
2. git clone
3. pnpm install
4. pnpm run dev

**本应该**

正常启动项目

**屏幕截图**

![image](https://user-images.githubusercontent.com/42372982/218301319-5c37060f-c781-49dc-bb70-45c77e2b075a.png)

**设备和软件信息**

-   操作系统和具体版本: Ubuntu 22.04.1 LTS 
-   屏幕参数: 无关
-   软件版本: commit 3a90a6a
-   IDE: WebStorm 2022.3.2 （应该无关）

**更多信息**

我也使用过 electron-vite 开发项目，我的项目可以在我的环境下正常启动。可能不是我本地环境的问题。

尝试过使用 npm 而不是 pnpm，依然没有解决问题。

**Comment by xushengfeng** [comment]
软件不允许重复启动
先退出已运行的eSearch

**Comment by jinsuichen** [comment]
It works
