### ISSUE TITLE
截图会出现空格

### ISSUE THREAD

**Issue by KnSup** [xushengfeng/eSearch#131]
**描述**
我不太会使用模型相关的东西，但是经过调试，我发现用到了这句话对结果进行分词，这会导致截图出来的内容存在空格，是否这句话有其存在的目的，还是删除比较合理一些呢？

**屏幕截图**
![image](https://user-images.githubusercontent.com/53806325/218442093-fb27ed32-64f1-4a34-a9e9-4d4bdb101890.png)

**Comment by KnSup** [comment]
是的，我也发现了，并且我换了模型的版本，好像没什么用

**Comment by xushengfeng** [comment]
https://github.com/xushengfeng/eSearch/issues/112#issuecomment-1627683953
