### ISSUE TITLE
A JavaScript error occurred in the main process，这样怎么办

### ISSUE THREAD

**Issue by onroco** [xushengfeng/eSearch#133]
完全不会处理，重装了也没有用
Uncaught Exception:
SyntaxError:Unexpected end of JSON input at JSON.parse (<anonymous>)at Conf._deserialize
(C:\Users\zstyz\AppData\Local\Programs\eSearch\resources\app\node_module..:43)at get store [as store]
(C:\Users\zstyz\AppData\Local\Programs\eSearch\resources\app\node_module...43)at new Conf
(C:\Users\zstyz\AppData\Local\Programs\eSearch\resources\app\node_module...32)at new ElectronStore
(C:\Users\zstyz\AppData\Local\Programs\eSearch\resources\app\node_modules...3)at Object.<anonymous>
(C:\Users\zstyz\AppData\Local\Programs\eSearch\resources\app\out\main\mai..1.3)at Module.compile (node:internal/modules/cjs/loader:1120:14)at Module._extensions..js (node:internal/modules/cjs/loader:1175:10)at Module.load (node:internal/modules/cjs/loader:988:32)at Module.load (nodeinternal/modules/cjs/loader:829:12)

**Comment by xushengfeng** [comment]
找到`config.json`，一般在`C:\Users\zstyz\AppData\Local\Programs\eSearch`下，把里面内容用记事本改为`{}`
