### ISSUE TITLE
关于截屏库的调用

### ISSUE THREAD

**Issue by Xu-Wade** [xushengfeng/eSearch#136]
关于截屏库不支持Linux arm的情况我在之前的issue中有看到，想问下作者大大具体是从代码的哪儿调入了node-screenshots库？我想尝试一下找其他截屏库替换node-screenshots。
还有就是看到大大今天刚刚更新了clip_window，想问下具体是做了什么改动呢？

**Comment by xushengfeng** [comment]
引入：https://github.com/xushengfeng/eSearch/blob/master/src/main/main.ts#L39
获取数据并通过`ipc`发送 https://github.com/xushengfeng/eSearch/blob/master/src/main/main.ts#L981
渲染进程接收： https://github.com/xushengfeng/eSearch/blob/master/src/renderer/clip/clip_window.ts#L98

最近添加了linux的窗口位置和大小精确获取，windows的窗口识别测试也通过了，过几天会添加的 #94

**Comment by Xu-Wade** [comment]
谢谢!很抱歉没能及时回复您。
在您解答之后我最近有学习ts语言，但仍然不熟练，我想向您请教一下：

- (1)替换截屏库时除了对package.json和引入部分做更改，还有什么需要变动吗？

- (2)我在vscode中debug时出现了很多参数没有读到值的情况，这是因为替换了截屏库吗？

![value1](https://user-images.githubusercontent.com/125551656/226342932-5fdc4722-8e37-41b2-98ff-e0b4ed543b1d.png)
![value2](https://user-images.githubusercontent.com/125551656/226342984-0a5e08ac-907c-4268-8185-d795e0bc3ee8.png)

**Comment by xushengfeng** [comment]
这只是ts的警告而已，表明这个变量没被使用，只是作为占位符。
通过`npm run dev`运行程序，截屏时会弹出调试界面
