### ISSUE TITLE
安装完成自动重启，然后发生了很严重的错误

### ISSUE THREAD

**Issue by The-ballads** [xushengfeng/eSearch#139]
[安装之后让我自动重启，重启了之后屏幕默认变成了200%的缩放，然后显卡掉驱动了，所有有关屏幕的选项都没了，165HZ也没了，现在是60HZ在用，卸载了这个软件重启还是不行，卸载了依赖的运行库还是不行，而且自带的英伟达显卡管理软件直接报错，说是不兼容，自带的色彩管理软件也开机就报错...无语了，现在不知道怎么回去了，独显用不了了]

**Comment by xushengfeng** [comment]
- 重启试试？
- 显卡管理和色彩管理的报错具体时怎么样的
- 在你自动重启前还安装或修改了其他东西吗

**Comment by The-ballads** [comment]
1.重启了也没用，试过好几遍。
2.显卡说不兼容，色彩管理也是说暂时出现问题。
3.没有，就是安装了本软件之后让提示重启，我重启之后就变成这样了。
应该是安装了之后与显卡驱动的什么文件冲突了，导致显卡直接掉驱动了，我重新装了一下显卡驱动就好了。

**Comment by The-ballads** [comment]
对了，电脑是拯救者R9000P2021款

**Comment by xushengfeng** [comment]
也就是说现在你的电脑恢复正常了吧
原先依赖静默安装时不会默认重启，现在依赖更新后安装完默认重启了
猜测是在eSearch安装没完全结束时依赖安装完重启，导致安装不完全，从而影响了其他软件
现在试图优化一下安装逻辑
