### ISSUE TITLE
关于马赛克功能

### ISSUE THREAD

**Issue by avalonskyblog** [xushengfeng/eSearch#14]
个人感觉，马赛克功能属于比较常用的，应该放在第一级菜单，eSearch我个人感觉马赛克使用非常麻烦。

可以仿照一下Snipaste，放在第一级菜单，并且简化操作。

**Comment by xushengfeng** [comment]
截屏不是主要功能啊:joy:

不过图像编辑的相关快捷键还是可以考虑的

**Comment by avalonskyblog** [comment]
还是看个人使用环境，个人意见打磨一下截图体验是比较好的
