### ISSUE TITLE
自动重启后截图疑似全屏贴图无法关闭

### ISSUE THREAD

**Issue by Bo-Magazin** [xushengfeng/eSearch#141]
**描述问题**

**重现步骤**

1. 长截图之后不知道点到什么
2. 任务栏以上被置顶贴图遮蔽，无法关闭，通过win+tab新建桌面依然存在

**本应该**
显示 xxx

**屏幕截图**

**设备和软件信息**

-   操作系统和具体版本:
-   屏幕参数:
-   软件版本:

**更多信息**

**Comment by xushengfeng** [comment]
无法关闭是点x按钮无效还是怎么样
