### ISSUE TITLE
长截图不响应

### ISSUE THREAD

**Issue by Bo-Magazin** [xushengfeng/eSearch#142]
**描述问题**

**重现步骤**

1. 第一次长截图因为无法确认取消了
2. 再之后无法再调用长截图，屏幕会凝固但不会出现长截图页面，可以esc取消，恢复默认设置与覆盖安装均无效

**本应该**
显示 xxx

**屏幕截图**

**设备和软件信息**

-   操作系统和具体版本:
-   屏幕参数:
-   软件版本:

**更多信息**

**Comment by 556mark** [comment]
一样的问题

**Comment by xushengfeng** [comment]
第一次怎么取消的

**Comment by 556mark** [comment]
我一开始也是一样的问题后来我卸载了重新安装，没有改安装位置就可以了，但是长截图的拼图速度真的很慢，而且在拼的时候鼠标掉帧

**Comment by snowingmerak** [comment]
> 第一次怎么取消的
我第一次就卡死无响应，这是我录的屏：
https://www.aliyundrive.com/s/CNMo2zzcdyh
可以看到框选后点了长截图就卡死了，必须按esc退出才能进行别的操作
系统是win11家庭版 22h2 22621.1413
安装时为全局安装并且没有更改默认安装目录
我不知道怎么抓取软件日志，如果可以的话我可以抓取一下当时的日志发上来

**Comment by snowingmerak** [comment]
> 第一次怎么取消的

之前用的1.9.8出现这个问题，现在用的1.10.0-beta.4仍然存在此问题

**Comment by xushengfeng** [comment]
在不响应时按下ctrl+shift+i换出控制台，单击console查看输出
能按下esc退出说明软件能响应，但界面没出来

**Comment by snowingmerak** [comment]
最新的测试版可以用了，但是功能尚不完善。比如在网页点了长截屏之后鼠标会失焦，导致拼接的图只有第一页和最后一页

**Comment by df13954** [comment]
浏览器，长截图流程是怎么操作的，触发截图，选择长截图按钮，然后有一个虚拟框出现，然后滚动网页？滚动了之后怎么停止截图，得到结果呢。有没有大佬说下，长截图是怎么操作的啊。
