### ISSUE TITLE
存在截图后，靠近屏幕边缘的有些位置无法点击的问题，主要是在使用ps时。

### ISSUE THREAD

**Issue by zangchenyang** [xushengfeng/eSearch#144]
软件很好用，用过一个月体验都不错，不过现在又重新安装上了snip截图软件。希望能够解决，感谢！

**描述问题**
存在截图后，靠近屏幕边缘的有些位置无法点击的问题，主要是在使用ps时。
**重现步骤**
同时打开ps和eSearch时，ps全屏，有时会出现有些位置无法点击，一般是ps右下角添加曲线和蒙版小按钮位置。
![sp230314_120216](https://user-images.githubusercontent.com/45621795/224890258-eccab7de-6b3e-4501-811d-6e87e4f51bc2.png)

关掉eSearch问题会消失；
win10专业版系统，将任务栏移到了顶部；
我感觉是截图后，左边贴边显示的小滑块的问题。

**Comment by xushengfeng** [comment]
没贴图时是可以正常点击的是吗

**Comment by xushengfeng** [comment]
已在代码中修复 152d80a
