### ISSUE TITLE
截框选之后就闪退了

### ISSUE THREAD

**Issue by 556mark** [xushengfeng/eSearch#145]
**设备和软件信息**

-   操作系统和具体版本:win10系统，软件版本1.9.8
-   屏幕参数:双屏
-   软件版本:1.9.8

**更多信息**

**Comment by xushengfeng** [comment]
是一放开鼠标就发生了吗
闪退指软件退出，托盘也没有图标还是截屏退出了呢

**Comment by xushengfeng** [comment]
猜测是双击复制导致的误触
已在代码中修复 c593920c86ef5b7d24824826a320724db8057678
