### ISSUE TITLE
录屏点击保存后有个小窗

### ISSUE THREAD

**Issue by u-Sir** [xushengfeng/eSearch#147]
![图片](https://user-images.githubusercontent.com/93647031/227568711-93b148fe-f373-471f-a804-c16c7d93cb60.png)
提示生成成功后就没有，而且也没有找到视频
记得之前是有预览窗口的

1.10.0-beta.5

操作系统和具体版本:  Win11 专业版 22h2
屏幕参数: 15.6 寸，38402160，2.50 倍缩放 + 27 寸，38402160，1.50 倍缩放

**Comment by xushengfeng** [comment]
是结束录屏后这样的吗

拖动窗口边缘可以改变大小，拉开应该就有了

**Comment by xushengfeng** [comment]
3761e430fcb47254e80494c8213003db8345d7e0

**Comment by u-Sir** [comment]
> 是结束录屏后这样的吗
> 
> 拖动窗口边缘可以改变大小，拉开应该就有了

是录屏视频生成那段时间，而且通知说视频已生成，但实际上并没有生成任何文件

**Comment by xushengfeng** [comment]
所以预览窗口是正常显示的吗
小窗是在什么时候出现的

**Comment by u-Sir** [comment]
> 所以预览窗口是正常显示的吗 小窗是在什么时候出现的

点击那个红色录制按键结束就出现，预览小窗不是正常显示

**Comment by xushengfeng** [comment]
对的，那个小窗就是预览窗口
可以拖动边缘拉大它
应该是错误地记录了窗口大小，我现在增加了限制

**Comment by u-Sir** [comment]
> 对的，那个小窗就是预览窗口 可以拖动边缘拉大它 应该是错误地记录了窗口大小，我现在增加了限制

然而拉伸不了😂

**Comment by xushengfeng** [comment]
ctrl+shift+i 并转到console 查看报错

**Comment by u-Sir** [comment]
> ctrl+shift+i 并转到console 查看报错

![图片](https://user-images.githubusercontent.com/93647031/227752575-8330d08f-cf7d-44cb-b8bf-2b2516c932e3.png)
同样调整不了大小

**Comment by xushengfeng** [comment]
你可以在其他界面打开console，然后在右上角三个点哪里更改停靠方式，像下图第一个按钮那样
![eSearch-2023-03-26-13-26-56](https://user-images.githubusercontent.com/28475549/227757163-d685969b-9388-4c4b-894e-a07f77459dae.png)
这样就不会遮挡了。关闭其他界面的console，他会记住，然后再在录屏那个小窗打开，他会单独一个窗口弹出console

**Comment by u-Sir** [comment]
![图片](https://user-images.githubusercontent.com/93647031/227759220-23284628-1cb0-4fe6-885d-111315c40dcd.png)
好像没什么

**Comment by u-Sir** [comment]
新版还是没修好 @xushengfeng 
![图片](https://user-images.githubusercontent.com/93647031/230764962-26ea94d7-cd04-4278-aa7d-5ad30be19f44.png)

**Comment by u-Sir** [comment]
> 配置文件`录屏.大小`配置了大小，你看看

怎么看？

**Comment by xushengfeng** [comment]
设置-高级-打开设置源文件

**Comment by u-Sir** [comment]
![图片](https://user-images.githubusercontent.com/93647031/231818161-fa5d427d-75d3-4274-86a5-6b7686d378ab.png)
这个？好像并没有生效呀，还是老样子

**Comment by xushengfeng** [comment]
加上`"width":800,"height":600`
最后变成：
```
"x": 1320,
"y": 872,
"width": 800,
"height": 600
```

**Comment by u-Sir** [comment]
变得更小了 
![Uploading 图片.png…]()

**Comment by xushengfeng** [comment]
这个窗口真的不能用鼠标改大小吗
这太奇怪了，直接在设置-高级里恢复默认设置吧

**Comment by u-Sir** [comment]
恢复默认设置后好了
