### ISSUE TITLE
有时转到副屏操作后，导致截图界面不正常

### ISSUE THREAD

**Issue by kiergua** [xushengfeng/eSearch#148]
**描述问题**
主屏分辨率 3144*1440
副屏分辨率 3840*1440
详情看截图，正常应该出现正常缩放大小的工具栏，但当在副屏操作过后，回到主屏使用，会出现工具栏与截图界面不正常的情况。（具体表现为：放大了主屏画面，甚至延伸至副屏，工具栏图标也变大了）重启可以解决，但很麻烦

**屏幕截图**

正常界面
![ffafcf17dac8bea9106be61bb6131c8](https://user-images.githubusercontent.com/69829045/228470276-e5ad0990-fc37-477b-838f-c3710ba0679d.jpg)

调出截图工具界面（不正常）

![f1c9630e714a0076a25ee532b28a764](https://user-images.githubusercontent.com/69829045/228470553-5c510eb6-22af-482d-ac78-2e3f347ddb9f.jpg)

**Comment by xushengfeng** [comment]
先在主屏使用时是正常的吗
