### ISSUE TITLE
对于教育场景的ocr 如何识别转换成LaTeX语法

### ISSUE THREAD

**Issue by lei-mu** [xushengfeng/eSearch#149]
1.对于特殊场景，比如数学试卷，如何识别转换成LaTeX语法？

使用了 百度的 试卷分析api,发现识别后还是不对，似乎是没有显示 api 结果里的latex 对应字段。

或者有其他方案吗?

**Comment by xushengfeng** [comment]
需要在设置 在线ocr-百度 选择类型为公式
