### ISSUE TITLE
arm64用npm run dist编译安装包，安装后提示cannot find module "node-screenshots"

### ISSUE THREAD

**Issue by zhuguli3005** [xushengfeng/eSearch#150]
arm64用npm run dist编译安装包，安装后提示cannot find module "node-screenshots"。
应该是electron-builder没有把node_modules的内容编译进去。
请问如何解决这个问题，把相关的module一起打包进去

**Comment by xushengfeng** [comment]
目前node-screenshots暂时不支持linux arm64。你是什么平台的？

**Comment by zhuguli3005** [comment]
> 目前node-screenshots暂时不支持linux arm64。你是什么平台的？

是uos统信arm64，我用cnpm可以安装

**Comment by xushengfeng** [comment]
13版本现在可以通过外部截屏器来截屏，见 https://github.com/xushengfeng/eSearch/blob/master/docs/use/clip.md#linux-arm64

**Comment by xushengfeng** [comment]
如果有其他关于arm64的bug，请在 #111 讨论，这个issue就先关闭了
