### ISSUE TITLE
一个奇怪的事情：截图时总是触发 numlock 的切换提示

### ISSUE THREAD

**Issue by u-Sir** [xushengfeng/eSearch#152]
笔记本是联想的，自带按键切换提示，使用其它的截图软件不会触发，就 eSearch 会触发，
试了下以下情况会触发提示：
- 托盘
   - 自动识别
   - 选中搜索
上面的使用快捷键也会有同样的提示，而截图搜索就不会出现这个提示。
版本：之前就有了，现在 1.10.0 也有
![图片](https://user-images.githubusercontent.com/93647031/230765460-47d55d8b-49dd-4b71-893a-d8e54cfe2ea1.png)

**Comment by xushengfeng** [comment]
#124
