### ISSUE TITLE
优化按键提示

### ISSUE THREAD

**Issue by u-Sir** [xushengfeng/eSearch#155]
希望可以手动调节提示样式、大小、停留时长，现在的提示在高分屏下太小了，而且速度有点快，可以参考下 keyFX、keyviz。还有在 windows 下 windows 键显示为 meta，希望能自动识别系统对应的按键。
最后赞下eSearch 支持单独显示 windows 之类的按键，找了好好久都没找到有这功能的按键提示软件。录制 `alt alt` `ctrl ctrl` `win` 这类特殊快捷键时很有用。👍

**Comment by xushengfeng** [comment]
按键提示初步优化
f3f7be4644c934959e6c20b4ee53914c29a3f158 8b39af50f4e97fd8e8e8ce51124d14af8c888704
[eSearch-2024-03-02-12-36-03-737.webm](https://github.com/xushengfeng/eSearch/assets/28475549/1fb59a4e-6346-4c11-84f7-8799ffc9b23d)

**Comment by xushengfeng** [comment]
可调大小 c7376a9daee89e4a7b2d02848c7debe559839cca
