### ISSUE TITLE
建议添加openai翻译功能

### ISSUE THREAD

**Issue by CXido** [xushengfeng/eSearch#157]
openai的润色太强大了，配合这个软件的OCR工作的效率会有大幅度的提升

**Comment by xushengfeng** [comment]
我在https://github.com/xushengfeng/fanyishu 实现了这个功能
在翻译引擎里添加`翻译树, https://fanyishu.netlify.app/?text=%s`这一行
在主页面的翻译引擎使用翻译树，右上角设置好api-key，选择openai的引擎，他会自动记忆
下次就可以直接使用了
