### ISSUE TITLE
几个建议

### ISSUE THREAD

**Issue by fcsnsu** [xushengfeng/eSearch#158]
**描述问题**
问题1：
使用的时候，鼠标滚轮会是图片上下移动
问题2：
自由画笔和矩形工具同时生效了

**重现步骤**
问题1：
1. 按下软件快捷键
2. 滑动鼠标滚轮
3. 图片上下移动，体验不好

问题2：
1.按下软件快捷键
2.点击画笔
3.点击自由画笔
5.点击矩形画笔
6.两个工具同时生效了

**本应该**
问题1：
建议优化一下，将鼠标滚轮优化成其他功能，比如放大缩小再配合鼠标左键进行移动图片；又或者用滚轮调整画笔粗细
问题2：
建议修复一下，不要让两个工具可以同时使用，另外希望添加一个点击画笔后可以默认选中上次使用的工具的功能，比如上次我使用的矩形工具，这次我只要再点击一下画笔工具就可以直接在屏幕上画矩形了，不用再去翻找矩形工具
其它建议：
是否可以更改成在任意位置点击鼠标中键就可以取消默认工具选择，而不用移动到图标上点击中键来取消

**屏幕截图**
![问题1](https://user-images.githubusercontent.com/54445648/233763811-48fc638b-5f31-42f8-96d1-56ac0a96e068.png)
![问题2](https://user-images.githubusercontent.com/54445648/233764017-54cbc2ab-204e-49c8-98b9-6ef09be06477.png)

**设备和软件信息**

-   操作系统和具体版本:操作系统：win10 64位 版本：19042
-   屏幕参数:分辨率：3840*2160 缩放：225%
-   软件版本:1.10.0

**更多信息**

**Comment by xushengfeng** [comment]
滚轮操作会添加更多选项的

中键按住默认操作是移动画布，可能存在冲突。任意位置中键取消默认操作应该提高了效率，但设置默认操作也是为了效率，这两种情况的目的似乎冲突了。

两种工具互斥操作在代码里已实现过，我目前也复现不出来:( 你这种情况是100%出现的吗

记忆工具我会添加的，我打算设定为点击左侧的形状工具，默认选中上次形状，点击左侧自由绘画，默认选中上次使用的画笔或橡皮
