### ISSUE TITLE
kde系统托盘 存在 没名字的 错误

### ISSUE THREAD

**Issue by detiam** [xushengfeng/eSearch#159]
**描述问题**
kde 托盘不显示应用名称

**重现步骤**
1. 启动程序
2. 打开折叠托盘
3. 没名字

**本应该**
显示 名字

**屏幕截图**
![image](https://user-images.githubusercontent.com/44510779/233800109-5018b44d-2b89-4234-8854-f6d0a59a9597.png)

**设备和软件信息**

-   操作系统和具体版本: archlinux roll
-   屏幕参数: 1080p
-   软件版本: 1.10.0

**更多信息**
无

**Comment by xushengfeng** [comment]
aur版本还是哪个版本？

**Comment by detiam** [comment]
> aur版本还是哪个版本？

appimage和aur的版本都这样

**Comment by xushengfeng** [comment]
已在代码里修复 31b5c47e4ee1ca6c40fc89913f71c7804aff7802
