### ISSUE TITLE
建议在快捷键里添加关闭主界面的选项

### ISSUE THREAD

**Issue by CDOccc** [xushengfeng/eSearch#160]
![image](https://user-images.githubusercontent.com/55381745/235986530-11e063d4-79fd-44d4-8217-436f3e94076b.png)

我通常用这个软件调用OCR，但是调用后要自己手动点击关闭窗口，
可不可以加一个关闭主界面的快捷键？这样子会方便很多

**Comment by xushengfeng** [comment]
可用<kbd>ctrl</kbd>+<kbd>w</kbd>

**Comment by CXido** [comment]
感谢回复，其实我想设置何其他软件都是ESC关闭窗口的，我先习惯一下

**Comment by CXido** [comment]
另外有一个问题，
就是百度OCR里的 标准版 和 高精度版 使用起来没反应，
一直处于扫描的界面，
请问您这边也是一样的情况吗？

**Comment by xushengfeng** [comment]
现在百度ocr要实名才能用，所以我这里无法直接调试 :(
你可以在 https://console.bce.baidu.com/tools/#/aiInterfacePermissions 进行接口权限和额度诊断

**Comment by xushengfeng** [comment]
是bug，不含位置版会出问题 已在代码中修复 2ecef9296dc7047236cbac861eeb2fd05687ce2e

**Comment by xushengfeng** [comment]
已在代码添加”自定义关闭主页面快捷键“功能 9a4983fbd8e93cd4f3e2846fda934261e880aa0d

**Comment by xushengfeng** [comment]
在设置中添加主页面快捷键设置，下一个版本更新 d9c625d7262ff7a0b3d2393e2c490e57f2140dba
