### ISSUE TITLE
关于ocr部分的实现

### ISSUE THREAD

**Issue by Xu-Wade** [xushengfeng/eSearch#161]
作者大大你好，我想对ocr部分做替换（用其他模型去推理，基于C++实现的.so，基于图像返回识别结果），
除了对local_ocr.js部分的改动，项目中还有哪些需要调整的地方吗？

**Comment by Xu-Wade** [comment]
还有一些疑问请教一下，js.ts中获取到的local_ocr中的box是必须的吗？如果local_ocr只返回了识别结果可以调整后显示吗？

**Comment by xushengfeng** [comment]
box用于主页面的文字放到图片上展示功能
见
https://github.com/xushengfeng/eSearch/blob/c11b69fa49da8c4fd067c44c99c23a7e60813920/src/renderer/js/js.ts#L2061

返回空列表应该也可以

**Comment by Xu-Wade** [comment]
原来如此，还有个小问题请教一下您：
如何确定我是否成功调用了库中的函数？现在npm run dev后启用ocr不识别结果，由于C++中是可以正常调用的，我怀疑是在eSearch中我没能成功调用到库里面的函数...

**Comment by xushengfeng** [comment]
我设计将OCR放在主页面（也就是文字编辑区）识别，并在识别时隐藏
https://github.com/xushengfeng/eSearch/blob/b2ce36962bbf20a180b9453a3a5466b5fa1c146d/src/main/main.ts#L1457

你在调试时可以让其直接显示，这样就能通过控制台看看不识别结果的原因
dev模式为了实现热重载，将本地路径替换成了vite在线调试网络路径，可能会无法正确加载库，用npm run start或移除
https://github.com/xushengfeng/eSearch/blob/b2ce36962bbf20a180b9453a3a5466b5fa1c146d/src/main/main.ts#L84

**Comment by Xu-Wade** [comment]
![image](https://github.com/xushengfeng/eSearch/assets/125551656/7d97710d-acf2-42fa-b03b-ef2bd2f65c5d)
（1）按您所说我在调试台看到了报错，但没想到如何解决；
（2）以及后面的devtools无法加载source是正常的吗，我将renderer_path的内容在main.ts中做了注释但仍无法加载

**Comment by xushengfeng** [comment]
后面的警告无所谓的，不报错就可以

**Comment by Xu-Wade** [comment]
了解！
我现在遇到了新的报错T_T：
（1）npm run dev的时候调用ocr，会显示js.ts中的init和ocr两个函数undefined（是因为local_ocr.js中没有成功export吗）
![error](https://github.com/xushengfeng/eSearch/assets/125551656/68f9a6de-667c-43cb-8325-d335ff607916)

（2）npm run start会在ocr识别过程中弹窗crash，我想知道如何查看crash原因？

**Comment by Xu-Wade** [comment]
> 我设计将OCR放在主页面（也就是文字编辑区）识别，并在识别时隐藏
> 
> https://github.com/xushengfeng/eSearch/blob/b2ce36962bbf20a180b9453a3a5466b5fa1c146d/src/main/main.ts#L1457
> 
> 你在调试时可以让其直接显示，这样就能通过控制台看看不识别结果的原因 dev模式为了实现热重载，将本地路径替换成了vite在线调试网络路径，可能会无法正确加载库，用npm run start或移除
> 
> https://github.com/xushengfeng/eSearch/blob/b2ce36962bbf20a180b9453a3a5466b5fa1c146d/src/main/main.ts#L84

打扰一下，想问下vite在线调试网络路径该如何移除，我之前直接在js.ts中注释在npm run dev调试会没有信息打印

**Comment by Xu-Wade** [comment]
还有个疑惑需要向您请教^_^，我通过测试可以在local_ocr.js中获得main_line的识别结果，但是无论npm run dev（路径问题找不到import的local_ocr）还是npm run start都无法在主页面返回结果T_T,一直显示图片识别中请稍等，同样也是export了init和ocr两个函数：
（1）return 的main_line只有string没有box，这个会导致不显示输出结果吗？
（2）在local_ocr.js可以输出结果的情况下，还有什么会导致不显示输出结果吗？下两张图分别为js中的改动以及dev调试信息。
![JsTs_change](https://github.com/xushengfeng/eSearch/assets/125551656/a3eaeacb-3203-41f6-9b9a-6078ea446bba)
![test_result](https://github.com/xushengfeng/eSearch/assets/125551656/0e322bb2-a47c-4cb4-a262-74432fc82c66)
（图中的"league"为自行打印的字符串）

**Comment by Xu-Wade** [comment]
作者大大好，想向您请教一下npm run start和npm run dev的区别是什么？我通过editor.push让识别结果返回到主界面，npm run dev可以正常返回结果，但是运行npm run start会一直无法识别T_T

**Comment by Xu-Wade** [comment]
作者大大好，想请教一下npm run dev和npm run start的区别是什么，我通过npm run dev可以调用到相对路径的库，无法通过npm run start调用到，这是为什么呢^_^

**Comment by xushengfeng** [comment]
那个错误应该是`lo`为undefined，你打印一下`(await import("./././ocr/local_ocr"))`或`lo`看看
我用了vite进行项目的打包，默认情况下，dev会开启一个热更新服务器（一般为localhost:5173/）
![image](https://github.com/xushengfeng/eSearch/assets/28475549/02f7be29-841c-4d50-a5d9-d6c21197e499)

start会编译ts，打包依赖，用过Electron直接运行html文件，下面的图上显示的就是本地路径

![image](https://github.com/xushengfeng/eSearch/assets/28475549/409ddf76-d108-46a9-973b-c9f34abe430f)

发布后的软件运行与start的类似

因此会有路径的坑

但你是用`import`函数引用`local_ocr`的话，vite会在编译时把local_ocr的内容全部放到主页面代码里，因此路径问题存在于local_ocr里。我用require直接调用的npm包，他会自动找到文件。你可以在local_ocr里使用`_dirname`等判断位置，再修改引用node文件的位置

**Comment by Xu-Wade** [comment]
原来如此！根据这种方式我已经成功找到了对应路径！多谢指点！！^_^
还有个小问题在于，整个项目可以通过node.js来编译和运行吗？
这样想是因为我测试ocr库和运行node loccal_ocr.js都是可以跑通的，但是通过npm run start编译会有内存分配的报错，没有遇到过这种情况，目前怀疑是ts编译时引起的errorT_T

**Comment by Xu-Wade** [comment]
> 原来如此！根据这种方式我已经成功找到了对应路径！多谢指点！！^_^ 还有个小问题在于，整个项目可以通过node.js来编译和运行吗？ 这样想是因为我测试ocr库和运行node loccal_ocr.js都是可以跑通的，但是通过npm run start编译会有内存分配的报错，没有遇到过这种情况，目前怀疑是ts编译时引起的errorT_T

原谅我问了个蠢问题，我更想问的在于
（1）关于tsconfig.json中的node.json和web.json的区别是什么，node和web各自配置了哪一部分呢？
（2）项目中ts的代码部分可以先编成js再用electron构建成应用吗？
（3）周末快乐！

**Comment by xushengfeng** [comment]
node.json针对main.ts
web.json针对其他ts
可以用js构建

内存分配错误可能是用vite编译时把其他资源一起打包了，建议分析一下报错，编译ts一般不会有这种问题的

**Comment by Xu-Wade** [comment]
我找到了报错的原因，确实是我操作不当导致的。还想请教下我如果在eSearch目录下还有内容需要打包进.deb中，是在package.json中的“file”下添加吗？

**Comment by xushengfeng** [comment]
一般除了file里用`!`排除的文件，其他文件都会默认打包

**Comment by Xu-Wade** [comment]
好的^_^,还想问下在生成.deb时如何确定他的安装路径呢？是写在了哪个文件中吗？我想把项目放在非/opt下的位置但是dpkg时会失败

**Comment by xushengfeng** [comment]
看起来electron-builder已经写死了 https://github.com/electron-userland/electron-builder/blob/master/packages/app-builder-lib/templates/linux/after-install.tpl

还有一种解决方式是在package.json `linux`同级项下添加
``` json
"deb":{
    "beforeInstall":"xxx.sh"
},
```
然后在`sh`文件里用`mv`移动路径

**Comment by Xu-Wade** [comment]
明白了！已经成功解决了该问题，多谢指教^_^

**Comment by Xu-Wade** [comment]
想请教一下^_^，如果要在应用选项栏中移除或添加新的选项（比如移除长截屏）应该在哪个位置改动呢？

**Comment by xushengfeng** [comment]
clip_window 的tool_开头函数
和clip HTML里
