### ISSUE TITLE
使用快捷键调起esearch，会触发系统的数字键提示

### ISSUE THREAD

**Issue by sun868102** [xushengfeng/eSearch#162]
**描述问题**
使用快捷键调起esearch，会触发系统的数字键提示。单击右下角图标则不会。
已经确定了不是快捷键的问题，更新了快捷键还是一样

**屏幕截图**
![image](https://user-images.githubusercontent.com/3632792/236603601-d924555c-e563-4a40-943e-640bc53a0333.png)
![image](https://user-images.githubusercontent.com/3632792/236603646-f658b53f-c01b-433b-a3c4-733e4a7c470d.png)

**设备和软件信息**
联想 yoga14s 2021
-   操作系统和具体版本: Win11 
-   屏幕参数: 2800 * 1600
-   软件版本: 1.10

**更多信息**

**Comment by xushengfeng** [comment]
Duplicate of #124
