### ISSUE TITLE
建议画线画框之类的编辑可以调整粗细

### ISSUE THREAD

**Issue by absolutemind** [xushengfeng/eSearch#163]
如题

**Comment by xushengfeng** [comment]
![eSearch-2023-05-10-19-18-06](https://github.com/xushengfeng/eSearch/assets/28475549/384a8748-da42-4d06-9657-91d7f161131d)

**Comment by xushengfeng** [comment]
画笔宽可以点击编辑栏左边第一个按钮，也有一个类似“1px”的按钮调节
