### ISSUE TITLE
编辑操作里的方框和椭圆都是实心的

### ISSUE THREAD

**Issue by absolutemind** [xushengfeng/eSearch#164]
编辑操作里的方框和椭圆都是实心的，把内容挡住了
![image-20230508163303250](https://user-images.githubusercontent.com/41701230/236776895-e7f39edd-addc-428a-b146-8e3b41dfe16f.png)

**Comment by xushengfeng** [comment]
![eSearch-2023-05-10-19-22-16](https://github.com/xushengfeng/eSearch/assets/28475549/694b312c-77ca-44ce-b101-727d8bebf8a8)
点击选择元素，把图中拖动条拖到0%就可以了
