### ISSUE TITLE
alt+c需要等待大概1s才能打开截图

### ISSUE THREAD

**Issue by yuhuan001** [xushengfeng/eSearch#168]
**描述问题**
alt+c需要等待大概1s才能打开截图

**重现步骤**

按下软件快捷键alt+c
等待大概1s才能打开截图

本应该
立即打开截图

**屏幕截图**

**设备和软件信息**

操作系统和具体版本:操作系统：win10专业版 64位 版本：22H2
屏幕参数:分辨率：2560*1440 缩放：125%
软件版本:1.10.0

**Comment by vancenx** [comment]
我也是一样，启动速度太慢了

**Comment by xushengfeng** [comment]
尝试优化：

https://github.com/xushengfeng/eSearch/releases/tag/1.10.1-beta.2
