### ISSUE TITLE
录屏 怎么安装ffmpeg

### ISSUE THREAD

**Issue by illii333** [xushengfeng/eSearch#169]
录完后编译好久，安装ffmpeg地方，又是灰色的不能安装它，系统是windows 11，可以选择路径就好了.灰色不能点击

**Comment by xushengfeng** [comment]
新版本不需要安装ffmpeg
录制完按保存后他需要转码需要一点时间，转码后他会自动关闭的

**Comment by xushengfeng** [comment]
你说的编译应该是视频的转码吧
录制时会把视频保存到临时目录里（可在设置-高级-位置信息里看），然后转成其他格式，如mp4等，还会裁切视频大小（原始视频是全屏），这个过程随录制时间增加的变长
我会优化的，让他边录制边转码，减少时间

**Comment by illii333** [comment]
这个优化了 那就太方便了
