### ISSUE TITLE
一些反馈

### ISSUE THREAD

**Issue by MT-susu** [xushengfeng/eSearch#17]
1.使用软件的时候屏幕会闪一下，应该是个放大的过渡动画，能不能优化一下呢，让他不要闪
2.能不能加个文字识别的快捷键呢，就是摁一下然后框选完自动文字识别，不用自己再点一下，因为我一般还是文字识别用得多，之前都是用的天若OCR，习惯了框选直接识别
3.使用时左边的那个菜单栏挡住截屏了，希望能够优化一下位置，因为我截屏都是从最左到最右，另外当鼠标移到最左的时候会变成调整大小的图标，不能框选
4.取色器确实需要个开关，对于没这个需求的人来说有点挡视野
5.图像编辑能不能加个矩形的图案，中间空心的那种，而不是中间是白的，有时候想框选重要内容方便点，另外这个橡皮有点鸡肋，太小了

**Comment by xushengfeng** [comment]
1. 是截屏的时候闪吗，上一次使用软件时的最后操作是什么（ocr还是保存之类的），闪的概率大概多少（偶尔还是100%），什么操作系统？
2. 到 设置-框选-框选后默认操作 选择ocr即可，这样框选完后自动进行ocr，当然，ocr的默认快捷键是<kbd>回车键</kbd>，你也可以到设置自定义
3. 若有遮挡，可以右键按住拖动菜单栏
4. 现在可以在 设置-取色器-大小 把两个值都调到最小
5. 矩形样式（填充颜色、边框颜色、边框大小）都可以在编辑栏上往下数第四个按钮**颜色和大小**里来设定，之后我会考虑让软件记住不同形状的样式。橡皮同样可以在颜色和大小里的边框宽度来设定，不过我会把最大值再调高一点

**Comment by xushengfeng** [comment]
1. 应该是electron框架的bug或我设置错误，我试试有没有方案解决
2. 想取消自动操作的话，<kbd>鼠标中间</kbd>点击工具栏上凸显的图标（你这里是ocr图标），就可以取消这次的自动操作，从而进行截屏。“我感觉可以把截屏加在摁下快捷键出现的菜单里”，这个我不太明白。长截屏要手动滚动。快速截屏默认保存到剪贴板，如果想保存到目录，设置-快速截屏 可以设置
3. 这种情况是100%发生吗？在鼠标变成那样的光标后（是↔这样的吧），按下鼠标并拖动能改变选区大小吗，还是其他反应？选区中间按下鼠标情况又是怎样？ 这个可以提一个新[issue](https://github.com/xushengfeng/eSearch/issues/new?assignees=&labels=&template=bug_report.md&title=)
4. 可以考虑
5. 属性记忆我也打算做，不过可能要等几个版本

**Comment by xushengfeng** [comment]
属性记忆：#51
