### ISSUE TITLE
录屏优化

### ISSUE THREAD

**Issue by xushengfeng** [xushengfeng/eSearch#171]
录屏写得有点粗糙，还需要在交互、性能上优化 :)

- [x] 确保初始化 #135
- [x] 多屏录制条 #156
- [x] 按键提示优化 #155
  - [x] 不同系统显示
  - [x] 合并|拆分显示
  - [x] 保留部分记录
  - [x] 鼠标操作显示在跟踪上
- [x] 分段保存 #128 #169
- [x] 分段转码
- [x] 合并分段
  - [x] gif（较慢）
  - [x] mp4
  - [x] ts（待支持高清）
  - [x] webm
  - [x] mkv
  - [x] mov
  - [x] flv（待支持高清）
  - [x] mpeg（待支持高清）
  - [x] 允许不分段
- [x] 重试步骤 e0931221b660a9822fe1a46347fe9f9bb8866a35
- [ ] 编辑进度条显示全部
- [x] wayland权限

**Comment by xushengfeng** [comment]
https://github.com/xushengfeng/eSearch/releases/tag/1.10.1-beta.4

**Comment by RegretfulALot** [comment]
大佬,我的录屏使用不了等待初始化以后我的录制条还是灰色的,视频的格式可以点击但是就是录制不了,我重装了三次1.10不行,然后我又重装了两次1.10.1-beat.15,还是不行
![是否是bug ](https://github.com/xushengfeng/eSearch/assets/149047367/d39865ec-b7f8-4e8f-a90d-473e8b8111ef)

**Comment by xushengfeng** [comment]
@RegretfulALot 你看一下录屏权限给没，或试试新版，不行的话可以单独开个issue
