### ISSUE TITLE
网站下载首页存在文案错误

### ISSUE THREAD

**Issue by lzyjxqt** [xushengfeng/eSearch#172]
<img width="527" alt="Snipaste_2023-06-10_17-04-49" src="https://github.com/xushengfeng/eSearch/assets/12902930/951dc5d2-5159-4cf7-8042-af95317c8657">

**Comment by xushengfeng** [comment]
https://github.com/xushengfeng/eSearch-website/commit/22fc4e9e357a30beabc56c2b955273c623115a06
