### ISSUE TITLE
不支持第二屏幕

### ISSUE THREAD

**Issue by khinacid** [xushengfeng/eSearch#173]
**描述**
如果两个屏幕共用一个主机，则该软件不支持在第二屏幕截屏，希望得到优化

**设备和软件信息**

-   操作系统和具体版本:w10
-   屏幕参数:两个屏幕
-   软件版本:1.10.0

**Comment by xushengfeng** [comment]
截屏跟随鼠标，把鼠标放在第二个屏幕应该就有了

**Comment by JPQAQ** [comment]
我尝试了一下，貌似还是有问题，把鼠标放在第二屏幕上截图显示的是第一个屏幕的整个屏幕截图。如下：

![image](https://github.com/xushengfeng/eSearch/assets/73947152/de462296-edc1-4da1-ade8-9fdb5d6d14ac)


> 截屏跟随鼠标，把鼠标放在第二个屏幕应该就有了

**Comment by xushengfeng** [comment]
已在代码修复 743bbf628b40b3925111a79182f63c968095db20
https://github.com/xushengfeng/eSearch/releases/tag/1.10.1-beta.13
