### ISSUE TITLE
建议优化翻译页面或允许插入脚本

### ISSUE THREAD

**Issue by khinacid** [xushengfeng/eSearch#174]
目前各种翻译页面太烂，不必要的元素被展示，如图划红线部分：

![eSearch-20230618_203322_864](https://github.com/xushengfeng/eSearch/assets/41636243/fdcdc5ef-f5e5-45d6-9990-413e8fab2206)

----

建议优化可采取以下方式之一：

- 翻译使用api方式，翻译结果直接在自开发页面上展示
- 对翻译页面优化，关掉不必要的元素
- 允许用户插入js脚本，让用户去关掉不必要的元素

-----

-   操作系统:w10
-   软件版本:1.10.0

**Comment by xushengfeng** [comment]
我另外开发了[翻译树](https://fanyishu.netlify.app/)，在1.9.0之后的版本添加了，如果没有，可以在设置中添加翻译引擎：`翻译树, https://fanyishu.netlify.app/?text=%s`

可以在其设置页面设置api key

**Comment by xushengfeng** [comment]
这是以前的域名，后来换了
因为以前版本的设置已经保存，后面版本推送时不好改掉以前的:joy:
