### ISSUE TITLE
截图之后，想使用方框或者圆圈做标记不方便

### ISSUE THREAD

**Issue by sunweiah** [xushengfeng/eSearch#176]
之前一直使用的是snipaste，但是snip不支持识别文字，后来换成eSearch，使用了一段时间，有几点建议：
1、截图时，鼠标选取的时候，选取框和鼠标之间有点延迟，有点卡顿的感觉；
2、选好区域截长图的时候，鼠标滚动没有动静，退出截图之后，内容确实有发生滚动，而且生成长截图的时候速度比较慢；
3、截图后做标记不太方便，使用方框或者圆圈，只会是一块白色遮住内容，想标记只能手动标记。

**Comment by xushengfeng** [comment]
![eSearch-2023-06-25-00-15-54](https://github.com/xushengfeng/eSearch/assets/28475549/d0f593fa-eb2f-43a5-885a-d0c2d2c1b6cb)

对于问题3，如图点击1，然后将2的不透明度调到0

**Comment by xushengfeng** [comment]
问题2的鼠标滚动没动静具体如何？是指屏幕内容不发生滚动吗？滚动截屏的速度目前优化得差不多了，很难再继续优化了
