### ISSUE TITLE
1.10.1-beta.4 高分屏dpi缩放不对

### ISSUE THREAD

**Issue by u-Sir** [xushengfeng/eSearch#178]
alt c 截图，

![image](https://github.com/xushengfeng/eSearch/assets/93647031/70630cc6-514f-456e-bbe1-27747859fd95)
alt c 截图显示如下图
![image](https://github.com/xushengfeng/eSearch/assets/93647031/26afaf91-67e9-4384-92db-55e9a81995de)

**Comment by xushengfeng** [comment]
具体说说

**Comment by xushengfeng** [comment]
eecca368ebf9cc88eeebea97378ce6be689fc656 已在代码中修复
但手头没多屏，不确定在不同缩放的多屏下跟踪鼠标的功能是否正确
