### ISSUE TITLE
设置内 全局-深色模式 修改后不保存

### ISSUE THREAD

**Issue by detiam** [xushengfeng/eSearch#179]
**描述问题**
RT

**重现步骤**
修改成深色后重启软件变回跟随系统

**本应该**
重启后保持深色设置

**屏幕截图**
![image](https://github.com/xushengfeng/eSearch/assets/44510779/e49ca105-e14f-4bfc-9dc2-f282a7fcb7ed)

**设备和软件信息**

-   操作系统和具体版本: archlinux rolling kde plasma 5.27.6
-   软件版本: 1.10.1-beta.6

**Comment by xushengfeng** [comment]
已在代码中修复 39a89d5ea0d97085824a9d189ceba4694be700c8
