### ISSUE TITLE
有时截图工具栏会跑到屏幕外面

### ISSUE THREAD

**Issue by LeoWang2007** [xushengfeng/eSearch#18]
**描述问题**
有时截图工具栏会跑到屏幕外面，显示不全
**重现步骤**
选择有些区域的屏幕截图会导致工具栏显示不全

**本应该**
工具栏显示完全

**屏幕截图**
![图片](https://user-images.githubusercontent.com/79351490/179143979-a201991a-ae6a-4bba-b785-3adf8d865b68.png)

**设别和软件信息**

-   操作系统和具体版本: Windows 10 专业版
-   屏幕参数: 1920*1080 1.5倍缩放
-   软件版本: [如：1.7.2]

**Comment by xushengfeng** [comment]
了解
