### ISSUE TITLE
建议在稳定版中增加ARM for Mac or Windows or Linux支持？

### ISSUE THREAD

**Issue by liuchanghuaX1** [xushengfeng/eSearch#181]

**Comment by xushengfeng** [comment]
本来在 https://github.com/xushengfeng/eSearch/releases/tag/1.9.8-beta.3 添加了arm支持，但npm安装的都是x86的，加之截屏库没有linux arm，故在 https://github.com/xushengfeng/eSearch/releases/tag/1.9.8-beta.7 移除
我再试着尽量尝试，由于手头没有arm设备，调试起来很困难。如果你有在x86上交叉编译层arm64的方案，欢迎pr

**Comment by xushengfeng** [comment]
Duplicate of #111
