### ISSUE TITLE
mac不能正常使用

### ISSUE THREAD

**Issue by roc9579** [xushengfeng/eSearch#183]
开始截图就会自动弹出权限询问窗口，截图框也会弹回桌面，无法正常使用 macos12.6
<img width="650" alt="Snipaste_2023-07-27_16-46-02" src="https://github.com/xushengfeng/eSearch/assets/111994918/82d6b124-30e7-4d7d-a409-d240527788b1">
<img width="604" alt="Snipaste_2023-07-27_16-46-31" src="https://github.com/xushengfeng/eSearch/assets/111994918/06c02752-4f1f-424c-b0ec-a91e0d7b9bdb">

<img width="1280" alt="Snipaste_2023-07-27_16-45-31" src="https://github.com/xushengfeng/eSearch/assets/111994918/964bf418-07ea-4319-a9ba-0d09d351c064">

**Comment by xushengfeng** [comment]
允许权限后还是会弹回桌面吗？
第三张图应该是能正常截屏了，能检测颜色

**Comment by roc9579** [comment]
允许权限了再次截图还是会弹出图一那个框，然后会自动跳到图三的界面（只能截屏这个界面，其他界面截屏不了）。比如我打开浏览器想截图浏览器界面就不行，会变成前面讲的那样。全屏的软件界面也不行。

> 允许权限后还是会弹回桌面吗？ 第三张图应该是能正常截屏了，能检测颜色

**Comment by roc9579** [comment]
> 允许权限了再次截图还是会弹出图一那个框，然后会自动跳到图三的界面（只能截屏这个界面，其他界面截屏不了）。比如我打开浏览器想截图浏览器界面就不行，会变成前面讲的那样。全屏的软件界面也不行。
> 
> > 允许权限后还是会弹回桌面吗？ 第三张图应该是能正常截屏了，能检测颜色



> 允许权限后还是会弹回桌面吗？ 第三张图应该是能正常截屏了，能检测颜色


https://github.com/xushengfeng/eSearch/assets/111994918/5f9e9477-6e35-488c-a4c3-7a71e2f5ea5e


Uploading 屏幕录制2023-07-27 19.39.58.MOV…

**Comment by xushengfeng** [comment]
eSearch 其他版本可用吗
在权限页移除 eSearch 再重新添加试试

**Comment by roc9579** [comment]
> eSearch 其他版本可用吗 在权限页移除 eSearch 再重新添加试试

最新的稳定版和测试版都不行，旧版本没试
移除试了，没用，还是会弹

**Comment by xushengfeng** [comment]
是用下面的➖移除的吗？如果重新添加还不行，那现在暂时还没有解决办法 :(

**Comment by roc9579** [comment]
> 是用下面的➖移除的吗？如果重新添加还不行，那现在暂时还没有解决办法 :(

重新安装，移除重新添加了，可以用了，感谢
