### ISSUE TITLE
关于 图像搜索/文字翻译 无法正常使用的一些问题

### ISSUE THREAD

**Issue by iibeibei** [xushengfeng/eSearch#185]
**描述**

**重现步骤**

1. 在 设置 界面
2. 点击 搜索 - 图像搜索引擎 
3. 选择 Google 会显示 无法按图搜索。请过几小时后重试。
4. 选择 baidu 会一直卡死在点击图片搜索那里
5. 如果选中 在浏览器中打开 的话，则点击无响应

**需求**
希望 Google  和  baidu 可以正常使用
希望 截图搜索 可以调用电脑默认的浏览器打开
希望 文字翻译 可以调用百度的 API 或者 有道的API
希望 文字翻译 可以在主页面分两列显示，左边是原文，右边是翻译

**屏幕截图**
![eSearch-2023-07-30-19-40-41-633.png](https://s2.loli.net/2023/07/30/8udFT1l63tZ2iOS.png)

**设备和软件信息**

-   操作系统和具体版本:
-   屏幕参数: 2560 x 1440 DPI: 125%
-   系统版本: Windows 11 企业版 22H2
-   软件版本: 1.10

**自由描述**

**Comment by xushengfeng** [comment]
google 和百度在排查
默认浏览器打开可在设置开启
文本翻译可以见#174

**Comment by xushengfeng** [comment]
已在代码中修复百度识图 f96fe714714f340da014e3197de71d77b81bc84e

**Comment by xushengfeng** [comment]
谷歌识图似乎使用了新方式，需要模拟上传操作，目前我还无法模拟，当做是无法解决吧 :(

**Comment by xushengfeng** [comment]
现在可以使用谷歌识图了 3b45c4d89200aa6a013699b43bfeaa6445ca789a
