### ISSUE TITLE
建议：支持设置 print screen 键作为快捷键

### ISSUE THREAD

**Issue by u-Sir** [xushengfeng/eSearch#187]
建议：支持设置 print screen 键作为快捷键，类似 win 11 这样的
![图片](https://github.com/xushengfeng/eSearch/assets/93647031/d5e5695c-7765-45b3-a21b-00b20ba3d932)

**Comment by xushengfeng** [comment]
直接在软件设置可以吗

**Comment by u-Sir** [comment]
> 直接在软件设置可以吗

貌似不行

**Comment by xushengfeng** [comment]
这看起来是Electron的问题了 https://github.com/electron/electron/issues/4663
Ctrl+PrintScreen之类的可以，但单独PrintScreen不行

**Comment by xushengfeng** [comment]
我研究了一下，在 系统设置-辅助功能-键盘 中关闭“使用 PrintScreen 捕获屏幕”，再在软件快捷键中设置即可。
