### ISSUE TITLE
长截图无法使用-macos12

### ISSUE THREAD

**Issue by roc9579** [xushengfeng/eSearch#188]
按下快捷键选定区域后，页面好像就以截图的形式固定了，无法滚动，点红色按钮也卡住，无法保存，如视频

https://github.com/xushengfeng/eSearch/assets/111994918/327b189a-d938-4bcb-9454-81261ab92ca3

**Comment by detiam** [comment]
kde 5.27.7 复现，并且旧版本也出现了这个问题。。可能是electron版本更新的原因？
```shell
(node:64144) [DEP0005] DeprecationWarning: Buffer() is deprecated due to security and usability issues. Please use the Buffer.alloc(), Buffer.allocUnsafe(), or Buffer.from() methods instead.
```
每次开启长截图出现以上提示

**Comment by xushengfeng** [comment]
已在代码中修复 58fcd8fe478e8259650b705a9198eb142b02ff7f

**Comment by detiam** [comment]
> 已在代码中修复 [58fcd8f](https://github.com/xushengfeng/eSearch/commit/58fcd8fe478e8259650b705a9198eb142b02ff7f)

![eSearch-2023-09-03-06-00-03-752](https://github.com/xushengfeng/eSearch/assets/44510779/d8813423-5cc4-4fd1-9483-76ace2dcb5eb)<p align="right">这个小红点怎么也截进去了↑</p>

**Comment by xushengfeng** [comment]
已尝试在代码里修复 f19c8bd8f8cbb87ff3d06e9361e4349021ce056b
