### ISSUE TITLE
新增1个截图模式

### ISSUE THREAD

**Issue by mukibook** [xushengfeng/eSearch#189]
希望有一个新的截图模式
原本的链路：按下快捷键——鼠标拖动选中——截图成功——在功能框编辑——复制到剪辑版
希望有一个新的模式：按下快捷键——鼠标拖动选中——复制到剪辑版
然后这两个模式可以同时存在，如果需要编辑图片的话选第一种的，用第一个的快捷键，如果不需要编辑截图的话使用第二种就好。

**Comment by xushengfeng** [comment]
设置-截屏-框选-框选后默认操作 能满足这个要求吗
框选选择后自动复制，实现了第二种模式，中键可取消默认复制，实现第一种模式

**Comment by xushengfeng** [comment]
已在代码中实现： 3d30354 通过快捷键创建临时的“框选后默认操作”，按下快捷键后，框选即可执行指定操作
