### ISSUE TITLE
ocr出现错误

### ISSUE THREAD

**Issue by 333brt** [xushengfeng/eSearch#19]
![屏幕截图 2022-07-15 200449](https://user-images.githubusercontent.com/78519467/179219604-ec4b683f-a864-4cbc-87c6-93f6f27880ca.png)

**Comment by xushengfeng** [comment]
是自定义模型了吗，要解压

**Comment by 333brt** [comment]
没加模型之前也有错误

**Comment by 333brt** [comment]
![屏幕截图 2022-07-16 085212](https://user-images.githubusercontent.com/78519467/179327867-64314edb-4c77-4e18-a1c5-c40c7464cbfb.png)

**Comment by doubly-yi** [comment]
OCR也遇到了错误
![image](https://user-images.githubusercontent.com/26616417/179338340-8cc4eaa1-a83f-48f8-a0ab-e138ac550b50.png)

**Comment by ShelwinSu** [comment]
设置里面的OCR字典：这块需要填写的目录不是很明确，既然列出了OCR 目录信息，还是应该考虑OCR目录那块自定义的设置友好性！

**Comment by xushengfeng** [comment]
> OCR也遇到了错误 ![image](https://user-images.githubusercontent.com/26616417/179338340-8cc4eaa1-a83f-48f8-a0ab-e138ac550b50.png)

见#6 下一个版本修复

**Comment by xushengfeng** [comment]
> ![屏幕截图 2022-07-16 085212](https://user-images.githubusercontent.com/78519467/179327867-64314edb-4c77-4e18-a1c5-c40c7464cbfb.png)

目前我不清楚你这个错误是不是与 #6 一样，你试一下 https://github.com/xushengfeng/eSearch/issues/6#issuecomment-1182876139 里面的补丁2能否正常工作

**Comment by xushengfeng** [comment]
> 设置里面的OCR字典：这块需要填写的目录不是很明确，既然列出了OCR 目录信息，还是应该考虑OCR目录那块自定义的设置友好性！

这个比较难指定，不过我会添加一个文件选择器来限定

**Comment by mgl0919** [comment]
<img width="419" alt="截图_20220802114702" src="https://user-images.githubusercontent.com/31845843/182287529-37af7444-c978-486f-827f-c668e58fdc96.png">
ocr报错

**Comment by xushengfeng** [comment]
> <img alt="截图_20220802114702" width="419" src="https://user-images.githubusercontent.com/31845843/182287529-37af7444-c978-486f-827f-c668e58fdc96.png">
> 
> ocr报错

检查一下你的秘钥是否正确，不要有`[]`等标点符号
