### ISSUE TITLE
截图时颜色提取会遮挡工具条 1.10.1-beta.13

### ISSUE THREAD

**Issue by u-Sir** [xushengfeng/eSearch#190]
![image](https://github.com/xushengfeng/eSearch/assets/93647031/184ca9c5-1d08-4357-ada7-ab02d5ae3342)

**Comment by xushengfeng** [comment]
指针移动到工具条上应该会自动隐藏吧

**Comment by u-Sir** [comment]
> 指针移动到工具条上应该会自动隐藏吧

图里鼠标就是在工具条上的了😂

**Comment by xushengfeng** [comment]
已在代码中修复 4d2f940a2bc0eff05cc673a87992f8a18dcff2f0
