### ISSUE TITLE
编辑栏颜色属性无法设置，自动变化

### ISSUE THREAD

**Issue by 754950416** [xushengfeng/eSearch#191]
xushengfeng 你好

很抱歉以发邮件的方式和您联系（
xushengfeng_zg），因为视频文件大于10M，git不允许提交issues（今天刚注册的账号，可能还没有找对方法）

需要反馈的问题有多个，需要按照视频来解释

1. 在00:01时，界面闪了一下，是因为开启了“自动识别”的全局按键，但这个应该不闪屏吧

2. 在00:02--00:12,演示的时鼠标滚轮的作用，在您的issues里您说，鼠标滚轮是放大缩小的作用，在我这是上下移动的作用，不知道我哪里没有设置的原因还是其他

3. 在00:13--01:21,演示的是截图后，颜色和大小的值，会自动变；而且多种变化规律

4. 在01:27--01:29,可以看到截图时，先出现上一次的截图，再重新截图本次

5. 在01:37--01:55,演示的时识图，没有任何效果，不知道我哪里没有设置的原因还是其他

软件版本为 1.10.1-beta.14，github下载的；
系统版本为22H2(OS内部版本22621.2283)

**Comment by xushengfeng** [comment]
1和4应该是一个问题，我正在试着排查
2的放大缩小是指<kbd>ctrl</kbd>+滚轮进行缩放
3是因为形状属性记忆冲突了，我在代码 3cf12a33a1361638bb77684656b6b6cbd118fabe 中限制为只有按下了形状按钮或选中形状后才能修改颜色
5见#185
