### ISSUE TITLE
在录屏时，还能使用截图的功能，但是按下之后，界面是全白的，只能看见鼠标箭头

### ISSUE THREAD

**Issue by 754950416** [xushengfeng/eSearch#192]
最外层的白色背景是截图的，黑色虚线内是录屏内容；实际都不是白色的

软件版本为 1.10.1-beta.14，github下载的；
系统版本为22H2(OS内部版本22621.2283)

![image](https://github.com/xushengfeng/eSearch/assets/144997882/90ae4e2c-244e-4fdb-b45e-5c9a21939a67)

**Comment by xushengfeng** [comment]
由于录屏的提示窗口与截屏窗口公用，他们会存在冲突，但代码没有禁止这种共存
我之后会让录屏时正常使用截屏的

**Comment by xushengfeng** [comment]
f1a11ddce1e1ae55ad5e5dea4b42868309593cda 已在代码中修复
