### ISSUE TITLE
浏览器打开后自动关闭标签页

### ISSUE THREAD

**Issue by 754950416** [xushengfeng/eSearch#193]
开启了“浏览器打开后自动关闭标签页“；浏览器打开后标签页确实关闭了，但主界面的页面还在，即当前识别的文字页，不知道是否是这样设计的

https://github.com/xushengfeng/eSearch/assets/144997882/3bfd1808-f5ce-411c-a7c2-6ddf6e5c6174

**Comment by xushengfeng** [comment]
设计如此
标签页指软件内置浏览器的标签页，识别结果编辑区不受影响，否则有时候识别的东西会不小心被关闭
