### ISSUE TITLE
默认引擎不能被选中

### ISSUE THREAD

**Issue by 754950416** [xushengfeng/eSearch#194]
”默认搜索引擎“和”图像搜索引擎“的”记住搜索引擎“，选中之后，再次打开设置页面，之前的选中自动变为未选中（历史记录的自动清除、文字识别的默认引擎也是如此），重启软件和电脑都无效，都不能被选中

**Comment by xushengfeng** [comment]
已在代码中修复： 59e615c80fa2d77938a9ec004cda887ca3ed4c6f
