### ISSUE TITLE
上下键改为调节值

### ISSUE THREAD

**Issue by 754950416** [xushengfeng/eSearch#195]
截图时，颜色和大小的不透明度（包括但不限于）方向键左右是调节输入位置，上下键也是，一般来说，上下键改为调节值更合适，比如上是加一，下是减一

![image](https://github.com/xushengfeng/eSearch/assets/144997882/25ce4a60-3760-4dca-8d5a-97c8ffb14e71)

**Comment by xushengfeng** [comment]
d8e5e33584c28e83d239529c4d4b8e4441c37db7 已在代码中添加

**Comment by xushengfeng** [comment]
大小栏也可以了 5f597f393868d775a90c9018d8360f782f6c1b7d
