### ISSUE TITLE
macOS上面如何操作长截图？

### ISSUE THREAD

**Issue by df13954** [xushengfeng/eSearch#197]
**描述问题**
macOS上面如何操作长截图？

**重现步骤**

1、安装最新版工具，点击启用，授予各种权限后。
2、点击截图工具，激活选中框。
3、选择一个可以滚动的区域，比如终端，或者浏览器。
4、区域确定之后，选择长截图的按钮，点击之后得到一个虚线框，右下角有一个红色的圆点。
5、然后滚动，
6、比如我滚动一部分，我想结束，如何结束得到长截图？

**本应该**
查看文档上面也没有说怎么长截图。

**Comment by xushengfeng** [comment]
点击右下角的红点

**Comment by df13954** [comment]
> 

第一次点击可以出现截图拼接中，一直到卡死，第二次不会出现截图拼接中，回到了无触发截图的状态了。这个完整的长截图流程是怎么样的呢，希望可以录制个视频讲解下。。。。

**Comment by GHOST1834** [comment]
macos14系统下无论怎么给辅助功能权限长截图都显示没有给权限。

**Comment by 1515orz** [comment]
macos长截图用不了，还会导致软件软死

**Comment by xushengfeng** [comment]
由于框架目前不能在其他界面获取鼠标位置（https://github.com/electron/electron/issues/42519）所以无法点击红点结束
我现在只能打算添加快捷键来实现结束长截屏功能了
拼接算法在尝试优化

**Comment by xushengfeng** [comment]
新版本 https://github.com/xushengfeng/eSearch/releases/tag/13.0.0 支持定时截屏拼接和使用快捷键结束长截屏
