### ISSUE TITLE
建议添加隐藏托盘图标功能

### ISSUE THREAD

**Issue by zhjr2019** [xushengfeng/eSearch#201]
**设备和软件信息**

-   操作系统和具体版本: win11
-   软件版本:  1.10.0

**请自由地描述你的提议（如有多个不同方向的建议，最好分成几个 issue）**
建议添加隐藏托盘图标功能，需要显示时按快捷键显示托盘图标。开启软件较多时，托盘区图标多了，影响美观（可能强迫症）

**Comment by xushengfeng** [comment]
这个功能应该不会搞，对于其他托盘软件似乎也没有提供这样的功能
对于你的需求，我找到 https://github.com/LCiZY/HideTrayIcon ，但我使用的是linux，并未测试，你可以看看
