### ISSUE TITLE
双显示截图错位 完全不能用

### ISSUE THREAD

**Issue by 0ran** [xushengfeng/eSearch#202]
系统版本 win11 23H2 22635.2486
双显示器 根本用不了 

这里不能发截图 无奈  简单赘述
在显示1上截图  显示1会显示 部分1+2的屏幕 就很诡异 怎么会出现屏幕2的内容 
间接性导致 截图错位  录屏错位  所有都错位 

总结 双显根本不能用

**Comment by xushengfeng** [comment]
测试版会这样吗

**Comment by rfhits** [comment]
两个屏幕没法截屏，issue +1

**Comment by xushengfeng** [comment]
已尝试在测试版修复 https://github.com/xushengfeng/eSearch/releases/tag/1.12.0-beta.6
