### ISSUE TITLE
建议在截图工具条新功能

### ISSUE THREAD

**Issue by SONGjiemo** [xushengfeng/eSearch#207]
1、截图需要有序号1 ，2 ，3，这种序号默认点击就是1.在点击就是2这种标记功能 我经常用来给同事标记步骤。
2、录制gif这种，可以直接发微信或者QQ也不用保存可以直接客户端看。
**设备和软件信息**
mac
-   操作系统和具体版本:mac14版本
-   软件版本:1.10最新版

**请自由地描述你的提议（如有多个不同方向的建议，最好分成几个 issue）**

**Comment by xushengfeng** [comment]
形状区有标号功能，向下滚动可以看到
gif不用保存是什么意思，可以具体描述一下吗

**Comment by SONGjiemo** [comment]
> 形状区有标号功能，向下滚动可以看到 gif不用保存是什么意思，可以具体描述一下吗

我看到了，希望尽可能全部显示不要出现滚动条
然后就是保持文件类型应该是个选择框，不是让用户自己输入格式的.我输入了格式有问题.希望可以解决.

**Comment by SONGjiemo** [comment]
https://verycapture.com/cn/index.html
这个软件可以在截图，长截图，GIF 录制，视频录制借鉴一下.
他那个 GIF 就是录制完毕就直接保持好了可以点击复制到微信直接发送.
再就是你的那个截图功能后常用的展开就好，感觉你的图形很多不能把常用的东西列出来老是.
希望你可以去掉  箭头，矩形，圆形和序号这几个常用的其他都排后面.

**Comment by xushengfeng** [comment]
3feae099bf46326ff9b2d2ffa08419e1b2cd504f 编辑栏ui更新，可以下载[测试版](https://github.com/xushengfeng/eSearch/releases/tag/1.12.0-beta.4)看看
