### ISSUE TITLE
win10启动esearch报json解析错误

### ISSUE THREAD

**Issue by readykevin** [xushengfeng/eSearch#209]
**描述问题**

**重现步骤**
首次安装后正常打开，设置截图快捷键后，关闭程序重新打开时，就提示json解析错误，无法显示主界面。卸载重新安装无法恢复。
Unexpected end of JSON input
at JSON.parse
at Conf._deserialize
resources\app\node_modules\conf\dist\source\index.js:67  at get store
...
main.js:3176

1. 在……界面
2. 点击……
3. 发生错误

**本应该**
显示 主界面

**屏幕截图**

**设备和软件信息**

-   操作系统和具体版本:win10
-   屏幕参数:
-   软件版本:1.10.0

**更多信息**

**Comment by xushengfeng** [comment]
删除配置目录下的config.json文件
配置目录在 %AppData% 即C:\Users\\AppData\Roaming\eSearch

**Comment by xushengfeng** [comment]
我在在代码中添加了自动修复： ba2ade712f397575bddd0c7df131b93cc7365c3e
