### ISSUE TITLE
马赛克滤镜无法生效

### ISSUE THREAD

**Issue by LeoWang2007** [xushengfeng/eSearch#21]
**描述问题**
马赛克滤镜无法生效
**重现步骤**

1. 在界面中使用高斯模糊滤镜功能

**本应该**
保存为马赛克后的图片

**屏幕截图**
这是软件截图预览时的界面
<img width="665" alt="Snipaste_2022-07-16_13-54-39" src="https://user-images.githubusercontent.com/79351490/179342091-38021aff-d063-4513-acdb-d3c7e3bc0dfc.png">
这是软件保存的图片
![eSearch-2022-07-16-13-55-25-559](https://user-images.githubusercontent.com/79351490/179342116-3a7ad6ae-c8bb-4eff-870e-ddc5afef3c33.png)

**设别和软件信息**

-   操作系统和具体版本: Win10专业版
-   屏幕参数: 1920*1080，1.5 倍缩放
-   软件版本: 1.7.2

**更多信息**
整体界面非常好看，加油，支持你！

**Comment by xushengfeng** [comment]
了解

**Comment by xushengfeng** [comment]
4b6388f 已经修复，下一个版本上
