### ISSUE TITLE
贴图存在无法关闭的错误

### ISSUE THREAD

**Issue by huozaiwuli** [xushengfeng/eSearch#214]
**描述问题**

**重现步骤**

1. 在贴图界面
2. 点击右上角叉子
3. 发生贴图自动移动到屏幕右侧，无法删除

操作系统和具体版本:eSearch-1.11.0-win32-x64.zip

**Comment by xushengfeng** [comment]
试一下最新测试版 https://github.com/xushengfeng/eSearch/releases/tag/1.12.0-beta.7

**Comment by huozaiwuli** [comment]
这是来自QQ邮箱的假期自动回复邮件。
 
您好，我最近正在休假中，无法亲自回复您的邮件。我将在假期结束后，尽快给您回复。

**Comment by huozaiwuli** [comment]
这是来自QQ邮箱的假期自动回复邮件。
 
您好，我最近正在休假中，无法亲自回复您的邮件。我将在假期结束后，尽快给您回复。
