### ISSUE TITLE
Linux系统下无法给一些窗口截图

### ISSUE THREAD

**Issue by xdiver** [xushengfeng/eSearch#216]
-   操作系统和具体版本:Rocky linux8.7
-   
-   软件版本:1.11.0

使用Houdin软件的时候弹出的对话框截图的时候，对话（下图中的红框里的内容）无法截图
![微信图片_20240104105652](https://github.com/xushengfeng/eSearch/assets/104573089/d616032c-961c-4bc8-ad6c-5548b41ecde0)

**Comment by xushengfeng** [comment]
是无法截取红框的内容吗？那应该是上游截屏依赖问题，本软件截屏依赖于 https://github.com/nashaofu/node-screenshots ，目前我无法解决
