### ISSUE TITLE
工具栏图标出现的时机问题

### ISSUE THREAD

**Issue by fengshaoye9945** [xushengfeng/eSearch#219]
建议只保留截图操作之后出现的工具栏图标，删除按下截图快捷键后立即出现的快捷键工具栏图标，否则的话会影响截图体验，如果工具栏出现的位置刚好遮挡了截图起点，还要手动右键工具栏移动到别的地方

**Comment by xushengfeng** [comment]
已在代码更新 c476a475120816f55ee3245935d365de4935d68b
