### ISSUE TITLE
希望可以将截图的窗口置顶，以免被其他窗口盖住

### ISSUE THREAD

**Issue by LeoWang2007** [xushengfeng/eSearch#22]
**描述问题**
希望可以将截图的窗口置顶，其他窗口会盖住eSearch
**重现步骤**

1. 正常截图

**本应该**
eSearch显示在最上层

**屏幕截图**
<img width="723" alt="Snipaste_2022-07-16_14-01-58" src="https://user-images.githubusercontent.com/79351490/179342255-e62ee19e-f437-4735-8b52-6e0e61a4a7a1.png">

**设别和软件信息**

-   操作系统和具体版本: Win10专业版
-   屏幕参数: 1920*1080，1.5 倍缩放
-   软件版本: 1.7.2

**更多信息**
希望改进一下，变得更完美，加油，支持你！

**Comment by xushengfeng** [comment]
下面那个ppt窗口是在截屏前就有的吗？

这时点击截图窗口，会怎样？还是被ppt盖住吗？

**Comment by LeoWang2007** [comment]
我后来也发现了，软件本身窗口就已经做过置顶处理了
但是不知ppt窗口是如何盖住的，有可能是点击了Windows键的原因
点击可以回去

**Comment by LeoWang2007** [comment]
另外，在截图时如果直接点击，不选取区域（直接点击鼠标）会出现这样的情况
![image](https://user-images.githubusercontent.com/79351490/179343484-f7e4c449-0ae4-4369-bdfe-cf59c82d532f.png)

**Comment by xushengfeng** [comment]
> 我后来也发现了，软件本身窗口就已经做过置顶处理了 但是不知ppt窗口是如何盖住的，有可能是点击了Windows键的原因 点击可以回去

那这个我就不处理了:upside_down_face:

**Comment by xushengfeng** [comment]
> 另外，在截图时如果直接点击，不选取区域（直接点击鼠标）会出现这样的情况 ![image](https://user-images.githubusercontent.com/79351490/179343484-f7e4c449-0ae4-4369-bdfe-cf59c82d532f.png)

这个了解了

**Comment by LeoWang2007** [comment]
感谢！🙂
