### ISSUE TITLE
无法启动：双击没有反应

### ISSUE THREAD

**Issue by PIKACHUIM** [xushengfeng/eSearch#221]
**描述问题**
无法启动：双击没有反应

**重现步骤**
1、下载最新的`eSearch-1.11.0-win32-x64.exe`
2、双击打开没有反应，进程结束

**本应该**
正常启动

**屏幕截图**
无

**设备和软件信息**
-   操作系统和具体版本: Windows 11 专业版 22H2
-   屏幕参数: 3840x2160
-   软件版本: 1.11.0-win32-x64

**更多信息**
1、解压文件，双击`eSearch.exe`可以正常启动
2、另外，软件没有签名，如果需要我可以提供签名

**Comment by PIKACHUIM** [comment]
另外软件没有签名，下载会提示风险：
![image](https://github.com/xushengfeng/eSearch/assets/40362270/3a2d2e4a-e8b2-4d53-be16-34ad7e5c1b5f)
我可以为开源作者（1k+ stars）免费提供数字签名，如果有需要欢迎联系

**Comment by cherub0507** [comment]
我的是1.11版正常，1.12版无法启动

win 11 pro x64

**Comment by cherub0507** [comment]
> 跟签名应该没关系 启动不了的话，如果能用cmd或powershell，可以在安装目录用其打开（安装目录可在快捷方式右键-运行目录找到），看看输出

(node:4220) UnhandledPromiseRejectionWarning: Error: Cannot find module 'F:\eSearch\resources\app\lib\translate\zh-CN.json'
Require stack:
- F:\eSearch\resources\app\out\main\main.js
-
    at Module._resolveFilename (node:internal/modules/cjs/loader:963:15)
    at n._resolveFilename (node:electron/js2c/browser_init:2:109827)
    at Module._load (node:internal/modules/cjs/loader:811:27)
    at f._load (node:electron/js2c/asar_bundle:2:13377)
    at Module.require (node:internal/modules/cjs/loader:1035:19)
    at require (node:internal/modules/cjs/helpers:102:18)
    at lan (F:\eSearch\resources\app\out\main\main.js:35:9)
    at F:\eSearch\resources\app\out\main\main.js:285:3
(Use `e-search --trace-warnings ...` to show where the warning was created)
(node:4220) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 1)

**Comment by xushengfeng** [comment]
如果能找到配置 `%APPDATA%/eSearch/config.json` 的话，把`"语言":"zh-CN" `改为`"语言":"zh-HANS"`，或等我明天发布新测试版

**Comment by cherub0507** [comment]
> 如果能找到配置 `%APPDATA%/eSearch/config.json` 的话，把`"语言":"zh-CN" `改为`"语言":"zh-HANS"`，或等我明天发布新测试版

一说就反应过来了，可能是调用了原1.11版的配置文件

删了重新运行就好了

1.12版响应感觉要比1.11版的更快
