### ISSUE TITLE
本地OCR文字识别不起作用，任何截图只显示“图片识别中……请等候”

### ISSUE THREAD

**Issue by hao316068545** [xushengfeng/eSearch#224]
**描述问题**
本地OCR文字识别不起作用，任何截图只显示“图片识别中……请等候”
**重现步骤**

1. 安装软件完成后
2. 启动软件，打开截图文字识别
3. 文本框中显示——图片识别中……请等候

**本应该**
显示识别后的文字

**错误屏幕截图**
![eSearch-文字识别问题](https://github.com/xushengfeng/eSearch/assets/16497529/3babdb3c-dfbf-455f-b639-f755f3d3aace)

**设备和软件信息**

-   操作系统和具体版本: Win 11
-   软件版本:eSearch-1.12.0-beta.5-win32-x64

**Comment by hao316068545** [comment]
配置文件中已存储路径
![image](https://github.com/xushengfeng/eSearch/assets/16497529/b86fa05a-ef34-4113-9dde-dee2a934b95f)

**Comment by xushengfeng** [comment]
试试默认模型
新模型使用了paddle ocr v4，det检测模型会不向后兼容，之后会修复的
v4模型已经在 https://github.com/xushengfeng/eSearch-OCR/releases/tag/4.0.0 更新了

**Comment by xylyp** [comment]
请问你的本地默认离线ocr使用成功了么？我更新到最新版本ocr和你一样，一直是图片识别中。使用默认也不行。谢谢

**Comment by xylyp** [comment]
> **描述问题** 本地OCR文字识别不起作用，任何截图只显示“图片识别中……请等候” **重现步骤**
> 
> 1. 安装软件完成后
> 2. 启动软件，打开截图文字识别
> 3. 文本框中显示——图片识别中……请等候
> 
> **本应该** 显示识别后的文字
> 
> **错误屏幕截图** ![eSearch-文字识别问题](https://private-user-images.githubusercontent.com/16497529/305703375-3babdb3c-dfbf-455f-b639-f755f3d3aace.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDg0OTgyNjIsIm5iZiI6MTcwODQ5Nzk2MiwicGF0aCI6Ii8xNjQ5NzUyOS8zMDU3MDMzNzUtM2JhYmRiM2MtZGZiZi00NTVmLWI2MzktZjc1NWYzZDNhYWNlLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAyMjElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMjIxVDA2NDYwMlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWViMWU1NWM3YjNhZWRiMWJiODAyYTEwMzQxYmE3MDE0N2QxMGU2OGNkOGUzNTI1NWVkOTIxNWEzYzU2Y2JmOGEmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.a9l6GcV6G79FWnLPzxziImEZrkTlBJqCWp42qT8aFfI)
> 
> **设备和软件信息**
> 
> * 操作系统和具体版本: Win 11
> * 软件版本:eSearch-1.12.0-beta.5-win32-x64



> 试试默认模型 新模型使用了paddle ocr v4，det检测模型会不向后兼容，之后会修复的 v4模型已经在 https://github.com/xushengfeng/eSearch-OCR/releases/tag/4.0.0 更新了

大佬，我和楼主的问题一样，无法使用本地ocr，默认的也不行。主要是需要内网中固定屏幕位置截图ocr，刚需，找了好多软件才找到大佬这个软件，感谢。求指点。

**Comment by hao316068545** [comment]
没成功，默认模式下一样有问题，无法识别

**Comment by xushengfeng** [comment]
ocr后再主页面编辑框按ctrl+shift+i,点右上角红色小叉，看看报错

**Comment by xushengfeng** [comment]
@xylyp 如果急用的话可以先使用旧版本而不是测试版

**Comment by infseers** [comment]
我的报错是
Uncaught (in promise) TypeError: Cannot read properties of null (reading 'text')
    at editor-CJfsnZLI.js:2508:23
    at editor-CJfsnZLI.js:2968:14
    at localOcr (editor-CJfsnZLI.js:3015:5)

**Comment by xushengfeng** [comment]
已在代码中修复 https://github.com/xushengfeng/eSearch/commit/b2a8dac087a5906ae324b308e601b905daae2332
稍后发布新版本

**Comment by hao316068545** [comment]
https://github.com/xushengfeng/eSearch/releases/tag/1.12.0-beta.7  新版本OCR识别功能经测试可正常使用。
