### ISSUE TITLE
建议在ocr完成后添加自动复制结果到剪切板的功能

### ISSUE THREAD

**Issue by 67906980725** [xushengfeng/eSearch#225]
目前ocr或自动ocr完成后的文字结果必须要手动点击复制按钮才能复制到剪切板, 当比较频繁使用ocr功能的时候每次都要点一下复制铵钮就会显得有些麻烦了. 
所以希望可以增加个是否自动复制ocr结果的设置项.

**Comment by xushengfeng** [comment]
已在代码中实现 90e206491fac3ed4b5b68a43daf9b3bcbadb051a
https://github.com/xushengfeng/eSearch/releases/tag/1.12.2-beta.6
