### ISSUE TITLE
OCR功能百度API接口不能用

### ISSUE THREAD

**Issue by krisppp** [xushengfeng/eSearch#226]
### 描述问题

百度的API的参数有，app id，app key，app secret，isearch的百度ocr设置里，没有app id选项，只填后两项，ocr时一直无识别结果，确认我的百度api是可用的，在captuocr里可用。另希望增加表格识别，这功能太有用了，谢谢

### 重现步骤

设置好以后，ocr识别一直不返回结果

### 软件版本

11.1

**Comment by xushengfeng** [comment]
我现在没有可用的key，所以暂时无法调试 :(
但我看了一下官方的api文档，接口应该没变
你要不用邮箱发一下你的key给我（xushengfeng_zg@163.com），我这里测试一下，测试好你再重新生成
