### ISSUE TITLE
实时翻译屏幕文字

### ISSUE THREAD

**Issue by zsray110** [xushengfeng/eSearch#228]
**设备和软件信息**

-   操作系统和具体版本:
-   软件版本:

**请自由地描述你的提议（如有多个不同方向的建议，最好分成几个 issue）**

**Comment by xushengfeng** [comment]
测试版实现了一个很简单的这样的功能，在测试版设置-工具栏-按钮显示中可把隐藏的翻译拖到显示来启用
像自定义翻译api，覆盖在文字上还是在侧边显示翻译等还有待实现和改进

**Comment by xushengfeng** [comment]
已更新 https://github.com/xushengfeng/eSearch/releases/tag/1.12.0-beta.19
