### ISSUE TITLE
录屏的时候那个交互界面我不能够友好的点击

### ISSUE THREAD

**Issue by SONGjiemo** [xushengfeng/eSearch#229]
### 描述问题

界面显示有问题

### 重现步骤

录屏的时候显示有问题

### 期望结果

![image](https://github.com/xushengfeng/eSearch/assets/46627639/0a37da32-782d-448a-875d-9acd4aa9cda0)
显示的面积大一点，按钮已经被遮住了

### 设备

mac

### 软件版本

1.11

**Comment by xushengfeng** [comment]
149cbcc87f3c1fdaa944944c0f1cf607c20169c6 已在代码中更新
