### ISSUE TITLE
建议禁用全屏窗口的大小调整功能，否则会导致错误

### ISSUE THREAD

**Issue by LeoWang2007** [xushengfeng/eSearch#23]
**描述问题**
希望禁用全屏窗口的大小调整功能，否则会导致错误
**重现步骤**

1.将鼠标放在全屏窗口边缘，可以调整大小，不应该调整

**本应该**
全屏显示，不可调整

**屏幕截图**
<img width="516" alt="Snipaste_2022-07-16_14-09-55" src="https://user-images.githubusercontent.com/79351490/179342527-5b9e517c-9630-4ac2-b9a8-7f7931420091.png">

**设别和软件信息**

-   操作系统和具体版本: Win10专业版
-   屏幕参数: 1920*1080，1.5 倍缩放
-   软件版本: 1.7.2

**更多信息**
感谢！

**Comment by xushengfeng** [comment]
了解

**Comment by xushengfeng** [comment]
d3c36fb 已经修复，下一个版本上
