### ISSUE TITLE
关于OCR识别时，显示识别失败 null

### ISSUE THREAD

**Issue by LazyCatW** [xushengfeng/eSearch#230]
### 描述问题

如下图所示，识别为默认离线模型，在识别一列内容时，如果截图过于窄又长时，会出现识别不全（只识别出个别内容）或者“识别错误  null 请打开开发者工具查看情况“。如图1~2区域，若同等宽度，截图6行内容，能够正常识别内容。在v1.11.0版本，截取相同大小区域，不会出现此状况。v12所有版本（win及linux版本）都存在此问题。

### 重现步骤

![1](https://github.com/xushengfeng/eSearch/assets/35787210/da0773d0-4eea-4d8f-9b23-70476cab2828)
![2](https://github.com/xushengfeng/eSearch/assets/35787210/e9bd754a-21cc-44c1-9e80-ede2ca8cbf2c)
![3](https://github.com/xushengfeng/eSearch/assets/35787210/f806719f-8cd9-4f37-8058-992c6a3f32f6)
![4](https://github.com/xushengfeng/eSearch/assets/35787210/484eab49-f5d0-4a17-9e3f-752dc24b51f9)

### 期望结果

期待大佬能够解决一下，谢谢

### 更多信息

此bug可复现，如截取窄又长时，100%会出现。

### 设备

华硕笔记本及台式机，系统为银河麒麟v10和win10

### 软件版本

v12所有测试版本都存在这个问题

**Comment by LazyCatW** [comment]
刚刚测试了一下，需要框选更大的区域才能正常识别（就是识别的内容周边需要更多的白边才正常识别），希望能修正一下截取的设置，其他的ocr软件及v1.11.0版本都可以几乎贴着文字内容进行ocr。

**Comment by xushengfeng** [comment]
已在代码中修复 https://github.com/xushengfeng/eSearch-OCR/commit/bd2b7291ef5f210fc77c4a9d19d6960ddfd6e4ad
