### ISSUE TITLE
可否增加简体中文语言设置

### ISSUE THREAD

**Issue by WW-0** [xushengfeng/eSearch#232]

**Comment by WW-0** [comment]
> 支持简中，你在设置右上角搜索”简体“ 可能是识别系统语言错误了
搜索后显示有6个匹配项，但是上下箭头不能跳转，不知道在那里被匹配到了

**Comment by xushengfeng** [comment]
是bug b04965d5e89d9bd6ccda9c47ff54278a5e809d28 已在代码中修复
将在下一版本更新，如果现在想启用，在 设置”高级“打开设置源文件，把"语言":"en"值改为"zh-HANS"

**Comment by WW-0** [comment]
> 是bug [b04965d](https://github.com/xushengfeng/eSearch/commit/b04965d5e89d9bd6ccda9c47ff54278a5e809d28) 已在代码中修复 将在下一版本更新，如果现在想启用，在 设置”高级“打开设置源文件，把"语言":"en"值改为"zh-HANS"

好的，谢谢，这样设置过后有效
