### ISSUE TITLE
录屏所选框和结果有偏差

### ISSUE THREAD

**Issue by voon-588** [xushengfeng/eSearch#233]
### 描述问题

在录屏时选择的区域结果预览时没有问题，但是保存的文件显示的区域有偏差

### 重现步骤

如上所述

### 软件版本

1.11.0

**Comment by xushengfeng** [comment]
屏幕分辨率和屏幕缩放可以提供一下吗

**Comment by voon-588** [comment]
> 屏幕分辨率和屏幕缩放可以提供一下吗

不好意思，上次忘记提供。分辨率：1920*1080；缩放：125%

**Comment by xushengfeng** [comment]
已在代码中更新 92088b332cd5e2862aad14ec4af91b647e42aaaa
