### ISSUE TITLE
右键菜单的教程帮助链接打开404

### ISSUE THREAD

**Issue by rubnet** [xushengfeng/eSearch#236]
### 描述问题

右键菜单的教程帮助
https://github.com/xushengfeng/eSearch-website/docs/index.md 

### 重现步骤

右键菜单点教程帮助

### 软件版本

1.12.0-beta.19

**Comment by xushengfeng** [comment]
已在代码修复 0f5f4f9bb5f27f8ef7267c4fe34e51716577d704
