### ISSUE TITLE
贴图存在无法编辑的错误

### ISSUE THREAD

**Issue by Tlonglan** [xushengfeng/eSearch#237]
### 描述问题

把图片贴在屏幕上，点击编辑按钮没有反应

### 重现步骤

1. 快捷键自动识别截图
2. 点击旁边的“放在屏幕上”的按钮
3. 点击贴图的编辑按钮

### 期望结果

点击编辑按钮后可以编辑图片

### 设备

win11 电脑端

### 软件版本

1.12.0-beta.19

**Comment by xushengfeng** [comment]
已在代码中修复 76315d2fd73e593a0fa3cc4451e054e005e8b184
