### ISSUE TITLE
建议贴图没有被选中的时候也有阴影，和背景区分

### ISSUE THREAD

**Issue by Tlonglan** [xushengfeng/eSearch#238]
如图，现在只有在选中贴图的时候才有阴影，建议像snipaste那样，没有被选中也能有阴影，不然有时很难发现这里有张贴图
![image](https://github.com/xushengfeng/eSearch/assets/38731172/60d41e10-7eca-4c24-aa3c-0a6a9b0b9cf1)

**设备和软件信息**

-   操作系统和具体版本: win11 电脑版
-   软件版本: 1.12.0-beta.19

**Comment by xushengfeng** [comment]
已在代码中添加 0e0abc32acb8aa344dfbe755281cb1dfc0f53799
