### ISSUE TITLE
建议在贴图添加保存功能

### ISSUE THREAD

**Issue by Tlonglan** [xushengfeng/eSearch#239]
如图，现在贴图上好像不能保存，只能复制，希望能添加这个功能
![image](https://github.com/xushengfeng/eSearch/assets/38731172/81001b30-b289-4dd9-b571-d98380eb8467)

**设备和软件信息**

-   操作系统和具体版本: win11 电脑版
-   软件版本: 1.12.0-beta.19

**Comment by xushengfeng** [comment]
可以先编辑，再保存
感觉顶栏东西放多了也不好，不知保存是否影响效率？

**Comment by Tlonglan** [comment]
我记得好像保存了就不能贴图了吧？
我用的比较多的是贴图，然后如果想起点什么，就做个标记，再保存一份这样

**Comment by xushengfeng** [comment]
已在代码中添加 bc81458430dea00c6a1a3092c4aea4cbb7fe14ed 将在下一个版本更新
