### ISSUE TITLE
fedora(40)安装rpm包时存在冲突的请求错误

### ISSUE THREAD

**Issue by 67906980725** [xushengfeng/eSearch#241]
### 描述问题

安装eSearch-1.12.0-linux-x64.rpm时报错如下:   
    错误：
     问题: 冲突的请求
      - nothing provides ffmpeg needed by eSearch-1.12.0-1.x86_64 from @commandline
    (尝试添加 '--skip-broken' 来跳过无法安装的软件包)

原因系fedora软件仓库提供的ffmpeg包名为ffmpeg-free而rpm包要求依赖的是ffmpeg

如果可以的话建议使用flatpak包做多发行版适配

### 重现步骤

下载eSearch-1.12.0-linux-x64.rpm
sudo yum localinstall eSearch-1.12.0-linux-x64.rpm

### 软件版本

eSearch-1.12.0-linux-x64.rpm

**Comment by xushengfeng** [comment]
已在代码中修复 a524f02fdd80bf89c15fdd02e8588705637c00a2
