### ISSUE TITLE
实时翻译屏幕文字的BUG

### ISSUE THREAD

**Issue by LazyCatW** [xushengfeng/eSearch#247]
### 描述问题

![微信图片_20240709093516](https://github.com/xushengfeng/eSearch/assets/35787210/0246913c-1838-49ad-9848-aee80ef3e17b)
![微信图片_20240709093523](https://github.com/xushengfeng/eSearch/assets/35787210/aa7488af-ab67-4bb2-a92c-3075fb397450)
如图所示，识别后报错，并且系统进入死机状态，鼠标失灵（桌面就像被蒙版覆盖一般，鼠标无法点击，无法调用任务管理器进行强行关闭），只能重启。

### 重现步骤

如图所示，报错后死机

### 更多信息

![微信截图_20240709101448](https://github.com/xushengfeng/eSearch/assets/35787210/0575713c-5640-40d6-ad52-ecc1993c4330)
linux版本出现如图报错。
![微信截图_20240709101653](https://github.com/xushengfeng/eSearch/assets/35787210/902676c7-7500-4848-a71d-6750786cd9ee)
设置的语言无法更改，修改后，始终会变成如图，两个简体中文

### 操作系统

win10企业版及银河麒麟v10

### 软件版本

所有包含实时翻译的版本

**Comment by xushengfeng** [comment]
屏幕翻译的语言需要在上面设置好引擎后才有效
识别报错正在排除（alt+f4可以关闭卡死的界面）

**Comment by xushengfeng** [comment]
已在代码中修复 a7699c10cbe10e88246d0f80f301cc9864506601 第一个问题
第二个linux的问题在排查

https://github.com/xushengfeng/eSearch/releases/tag/1.12.2-beta.1

**Comment by xushengfeng** [comment]
已在代码中修复 6b4f1854cad17227f06aeb1d6f7781819a0b83b1
https://github.com/xushengfeng/eSearch/releases/tag/1.12.2-beta.6
