### ISSUE TITLE
Wayland下长截图功能存在问题

### ISSUE THREAD

**Issue by Menghuan1918** [xushengfeng/eSearch#248]
### 描述问题

![屏幕截图_20240710_093713](https://github.com/xushengfeng/eSearch/assets/122662527/0152d9d2-e554-4e5b-9a67-a74f289d73f6)

此时无法点击结束长截图，并且ctrl键会被一直占用，就像被一直按下去一样(这也是为什么图片中浏览器缩放这么小的原因...)

需要注销或重启才能取消ctrl键的占用

### 重现步骤

使用自动识别后再点击长截图功能会触发此bug

### 操作系统

Arch KDE Wayland

### 软件版本

AUR上的e-search-bin 1.12.1-1

**Comment by xushengfeng** [comment]
无法结束是因为wayland在其他界面无法获取鼠标位置，所以点不到按钮 #197 之后会出快捷键实现按钮功能
ctrl锁定问题，我是在用快捷键后，确定了kde的远程访问控制才锁定的，不知你是在托盘触发还是用快捷键。这个问题应该是kde新版的问题，我看看能不能解决

**Comment by xushengfeng** [comment]
ctrl锁定是使用了“自动搜索”的问题，如果对自动搜索功能没有特别要求，只是用截屏，把全局快捷键绑定到“截屏搜索”就可以了
关于自动搜索的改进，还在研究

**Comment by xushengfeng** [comment]
新版本 https://github.com/xushengfeng/eSearch/releases/tag/13.0.0 支持定时截屏拼接和使用快捷键结束长截屏

**Comment by Menghuan1918** [comment]
感谢!
