### ISSUE TITLE
 No loader is configured for ".node"

### ISSUE THREAD

**Issue by liyao1520** [xushengfeng/eSearch#249]
### 描述问题

报错
 No loader is configured for ".node" files: node_modules/.pnpm/onnxruntime-node@1.18.0/node_modules/onnxruntime-node/bin/napi-v3/darwin/x64/onnxruntime_binding.node
 
 
![image](https://github.com/xushengfeng/eSearch/assets/76561071/b92f1fe0-24c2-4be9-adf8-1c087696f4dc)

### 重现步骤

clone代码执行
1.pnpm install
2.pnpm dev

### 操作系统

mac

### 软件版本

node version:18.20.4 pnpm version:9.5.0

**Comment by xushengfeng** [comment]
vite没引用.node，我还没配置好
可以使用`pnpm start`运行
