### ISSUE TITLE
录制完视频裁剪错误或者合并错误，导致保存不了，录制的视频一次也没保存成功

### ISSUE THREAD

**Issue by Sevenyy537** [xushengfeng/eSearch#253]

**Comment by Sevenyy537** [comment]
我一般录制最高码率视频，录制时间四十秒以上
![eSearch-2024-08-03-14-05-02-985](https://github.com/user-attachments/assets/2587f5f3-8312-40a3-99c4-f38e98975f5d)

**Comment by xushengfeng** [comment]
已在代码中修复 14789572acb2d52d74198e5b0a9072f61da4f9f5
