### ISSUE TITLE
识屏存在识别错误

### ISSUE THREAD

**Issue by hh2002sun** [xushengfeng/eSearch#254]
### 描述问题

识别错误
Error: no available backend found. ERR: [cuda] backend not found.
请打开开发者工具（Ctrl+Shift+I）查看详细错误

### 重现步骤

使用屏幕翻译，弹出错误，重启可以复现

### 更多信息

![image](https://github.com/user-attachments/assets/b1095668-cd2c-4102-885c-d7e255eac4c6)

### 操作系统

Windows10

### 软件版本

1.12.1

**Comment by xushengfeng** [comment]
设置-AI-后端改为cpu
