### ISSUE TITLE
建议截图时增加参考线

### ISSUE THREAD

**Issue by Chenyigit** [xushengfeng/eSearch#255]
大佬考虑在截图时增加参考线吗，有时截图预判失败，只截到一半的字，图片是bandicam的，截图时有参考线能准确截图，如果能做一个开关，不需要这个功能的可以关掉，
![IMG_20240807_190147](https://github.com/user-attachments/assets/53ab4de1-8b1a-42a6-a3e9-bf14a858f0b0)
![IMG_20240807_190025](https://github.com/user-attachments/assets/153f9685-b2c8-41ca-befb-a4b685e34da1)

**Comment by xushengfeng** [comment]
你指的是光标处水平和竖直的延伸线吗

**Comment by Chenyigit** [comment]
> 你指的是光标处水平和竖直的延伸线吗

是的，光标处的延伸线，谢谢回复

**Comment by xushengfeng** [comment]
已在代码中实现 a191eed20cdb6d18d97f3169424a882ed49c8dbd
https://github.com/xushengfeng/eSearch/releases/tag/1.12.2-beta.6
