### ISSUE TITLE
有没有图片翻译

### ISSUE THREAD

**Issue by xushengfeng** [xushengfeng/eSearch#256]
有没有图片翻译

_Originally posted by @Eyion in https://github.com/xushengfeng/eSearch/issues/223#issuecomment-2278948353_

**Comment by xushengfeng** [comment]
@Eyion 是工具栏没有按钮还是其他问题？
工具栏按钮可在设置中把翻译按钮拖拽到坐标显示区

**Comment by Eyion** [comment]
翻译图片文字，将图片中信息从中文变为其他语言

**Comment by xushengfeng** [comment]
设置-翻译-屏幕翻译-语言 中可以修改
目前只支持在设置中修改

![eSearch-2024-09-03-21-58-07-953](https://github.com/user-attachments/assets/7004e607-6a82-4e75-8266-33791cec2c69)
