### ISSUE TITLE
截图时存在工具栏图标不显示的问题

### ISSUE THREAD

**Issue by bk0531** [xushengfeng/eSearch#257]
### 描述问题

工具栏空白一条

### 重现步骤

截图

### 软件版本

1.12.3

**Comment by xushengfeng** [comment]
只是工具栏吗，还是绘制栏图标也空白

**Comment by xushengfeng** [comment]
已在代码中更新 1156a3e 过几天发新版本

**Comment by bigccc** [comment]
感谢！

**Comment by xushengfeng** [comment]
https://github.com/xushengfeng/eSearch/releases/tag/1.12.4 修复版已发布
