### ISSUE TITLE
设置里所作的更改 存在 无法保存 错误

### ISSUE THREAD

**Issue by ExidAty** [xushengfeng/eSearch#259]
### 描述问题

设置里的更改无法保存，CTRL R 后会恢复初始的设置

### 重现步骤

在设置-快速截屏-获取保存路径-选择文件夹-CTRL+R刷新，更改无效

### 操作系统

Win11

### 软件版本

1.12.4

**Comment by xushengfeng** [comment]
是需要什么特别的操作才 Ctrl+R 刷新吗
设置在关闭时才保存。刷新把更改也归位了，就保存不了。

**Comment by ExidAty** [comment]
感谢大佬的回复，我是设置里其它的更改可以保存，只有快速截屏，获取保存路径这里更改不了，不管怎么设置最终再打开这里都显示空，其它的更改都可以正常应用，我不确定是不是我本地电脑的问题。
![Screenshot - 2024-08-25 21 10 17](https://github.com/user-attachments/assets/72452401-1ed8-492d-a0e3-04a13d100f01)

**Comment by xushengfeng** [comment]
软件没有正确显示路径，是bug
临时解决方案是选择 保存到 为 目录，并获取保存路径，关闭设置。尽管设置不显示，但以及保存了。但下次打开设置再关闭就会清空
我会修复这个错误，并在下一个版本发布

**Comment by ExidAty** [comment]
好的，辛苦大佬了，非常感谢！
