### ISSUE TITLE
暗色主题存在问题

### ISSUE THREAD

**Issue by PTALTS-LK** [xushengfeng/eSearch#261]
### 描述问题

![image](https://github.com/user-attachments/assets/c17dc4d6-b3b4-4121-8d2d-2cf64f06114f)

### 重现步骤

Archlinux
使用aur 
e-search 1.12.3-1

### 期望结果

正确应用深色主题

### 操作系统

Archlinux

### 软件版本

1.12.3-1

### 屏幕参数

2560*1600 150%

**Comment by xushengfeng** [comment]
已在 aur 更新 1.12.4 版本，修复了这个问题

**Comment by PTALTS-LK** [comment]
> 已在 aur 更新 1.12.4 版本，修复了这个问题

经测试已解决👍
