### ISSUE TITLE
您好，我想知道eSearch软件的离线OCR使用的是什么模型

### ISSUE THREAD

**Issue by XmySz** [xushengfeng/eSearch#262]
您好，最近在使用eSearch的时候感觉这个离线识别的准确率很高，自己有一个标签识别的任务想尝试一下这个模型，想请教下作者这里使用的模型是什么，感谢！

**Comment by xushengfeng** [comment]
用了paddle OCR v4模型
具体可以见 https://github.com/xushengfeng/eSearch-OCR

**Comment by XmySz** [comment]
感谢
