### ISSUE TITLE
建议添加独立快捷键来触发框选后默认操作

### ISSUE THREAD

**Issue by kokojacket** [xushengfeng/eSearch#265]
感谢开发这么好的工具

框选后默认操作的方式非常的方便，但是一旦选择了一个功能，就无法在截屏时候使用其他功能了。
建议添加独立快捷键来触发框选后默认操作
比如Alt+A是默认选框，ALT+S是可以设置选框并自动默认操作功能

**Comment by xushengfeng** [comment]
有的，你可以在 设置-快捷键 下看看，应该是在靠后的位置

**Comment by xushengfeng** [comment]
![eSearch-2024-08-29-14-43-54-870](https://github.com/user-attachments/assets/0a9e3ade-e0cc-4fa2-9264-d6883fc05b86)

**Comment by kokojacket** [comment]
不是这个，这个快捷键是用于框选之后用快捷键代替鼠标按钮。
我所表达的是，快捷键直接触发框选+自动触发用具栏的一个功能。比如按下ALT+A之后，调出框选，框选完毕自动触发复制

**Comment by xushengfeng** [comment]
不是截屏快捷键，往下看”框选后默认操作“，虽然都是一样的图标，但是是不一样的，应该就是你说的
不过快捷键设置后重启程序才行

**Comment by kokojacket** [comment]
啊看见了，设置后无法保存，重启程序之后设置的快捷键丢失了

**Comment by kokojacket** [comment]
重试了好几次，保存成功了，感谢🙏
