### ISSUE TITLE
最新版本截屏功能存在图片偏移错误

### ISSUE THREAD

**Issue by Lj-dog** [xushengfeng/eSearch#268]
### 描述问题

按下Alt+C，出现图片偏移，而且鼠标在不同的区域有不同的偏移。
在125%缩放比下
![截图125%——1](https://github.com/user-attachments/assets/d94dcf96-6c29-432c-9e18-c23d3b09ff80)
![截图125%——2](https://github.com/user-attachments/assets/6ca3fa8e-b16c-495e-937a-c772b5a507b9)
![截图125%——3](https://github.com/user-attachments/assets/679f719b-d359-4aea-88c1-aef2e5fd66c1)
在100%缩放比下，恢复正常：
![100%缩放布局](https://github.com/user-attachments/assets/dab62080-e882-42d3-96ff-1ba4c51085db)

### 重现步骤

将缩放与布局调至125&

### 操作系统

win10 专业版

### 软件版本

13.0.0  按下检查更新说是已是最新版本

### 屏幕参数

1920*1080 125%

**Comment by Andrea-lyz** [comment]
相同的问题，Windows 11，屏幕分辨率3072x1920 缩放系统推荐200% 无扩展屏幕，但偏移区域不随鼠标位置变化
![屏幕截图 2024-08-15 101442](https://github.com/user-attachments/assets/2c5f7ceb-ff83-4ce1-b931-eb87ac45fc43)

**Comment by Lj-dog** [comment]
> 相同的问题，Windows 11，屏幕分辨率3072x1920 缩放系统推荐200% 无扩展屏幕，但偏移区域不随鼠标位置变化 ![屏幕截图 2024-09-01 123721](https://private-user-images.githubusercontent.com/52863141/363485389-919a2902-f2c9-423a-a5f7-7bc2e527d877.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjUxODc2NzIsIm5iZiI6MTcyNTE4NzM3MiwicGF0aCI6Ii81Mjg2MzE0MS8zNjM0ODUzODktOTE5YTI5MDItZjJjOS00MjNhLWE1ZjctN2JjMmU1MjdkODc3LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA5MDElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwOTAxVDEwNDI1MlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWRlZGM5MDM0MjcwOGNiODI2YmM0NDAzZGI2NWE3NjYwOTkxNjEyMDE0ZjA3MDJmYzJjMzM1OGE3N2U1ZDk4N2YmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.tyFqCrzzGiA2nLrTrYf7DKDrpjHKdQsQfaMC39TwSS0)
> 
> 版本 Windows 11 专业工作站版 版本号 23H2 安装日期 ‎2024/‎8/‎26 操作系统版本 22631.4112 体验 Windows Feature Experience Pack 1000.22700.1034.0

1、你这是又下了个其他截图软件截的图吗？
2、你多试几次，在其他窗口或者桌面截图试试。看是不是都是不同的偏移，我一开始也是向右下角偏移。但在其他界面就不是了。

**Comment by Andrea-lyz** [comment]
> > 相同的问题，Windows 11，屏幕分辨率3072x1920 缩放系统推荐200% 无扩展屏幕，但偏移区域不随鼠标位置变化 ![屏幕截图 2024-09-01 123721](https://private-user-images.githubusercontent.com/52863141/363485389-919a2902-f2c9-423a-a5f7-7bc2e527d877.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjUxODc2NzIsIm5iZiI6MTcyNTE4NzM3MiwicGF0aCI6Ii81Mjg2MzE0MS8zNjM0ODUzODktOTE5YTI5MDItZjJjOS00MjNhLWE1ZjctN2JjMmU1MjdkODc3LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA5MDElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwOTAxVDEwNDI1MlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWRlZGM5MDM0MjcwOGNiODI2YmM0NDAzZGI2NWE3NjYwOTkxNjEyMDE0ZjA3MDJmYzJjMzM1OGE3N2U1ZDk4N2YmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.tyFqCrzzGiA2nLrTrYf7DKDrpjHKdQsQfaMC39TwSS0)
> > 版本 Windows 11 专业工作站版 版本号 23H2 安装日期 ‎2024/‎8/‎26 操作系统版本 22631.4112 体验 Windows Feature Experience Pack 1000.22700.1034.0
> 
> 1、你这是又下了个其他截图软件截的图吗？ 2、你多试几次，在其他窗口或者桌面截图试试。看是不是都是不同的偏移，我一开始也是向右下角偏移。但在其他界面就不是了。

1.用的Windows自带那个截图，win+shift+s
2.试过的，包括桌面，我的偏移位置都是图片那样，可能我分辨率高了？

**Comment by xushengfeng** [comment]
13.0.0加入了新功能：贴图编辑居中。
但因为大小在缩放下计算错误，进而错误“居中”了截屏
已在代码中修复： 4242768c0306bbeb01e95694645d7c19534e9d11
明天发布修复版

**Comment by xushengfeng** [comment]
现在已经发布修复版
在不同页面下偏移不同的原因可能是偏移是依据窗口大小计算的，有时候窗口没那么快全屏就读取了窗口信息

**Comment by Lj-dog** [comment]
> 现在已经发布修复版 在不同页面下偏移不同的原因可能是偏移是依据窗口大小计算的，有时候窗口没那么快全屏就读取了窗口信息

  感谢博主。13.0.0.1版本单屏模式下已解决截图偏移问题。但在双屏模式下，副屏仍然存在截屏偏移问题，并且在某种情况下还会影响到本来不存在偏移问题的主屏。**直到他们都设置成100%缩放比，或者维持原缩放比，拔掉副屏，_并且重启eSearch_** 。  
  我会做更多的测试，并提交新的issue，以便快速的定位问题。再次感谢。
