### ISSUE TITLE
翻译模块中ChatGPT引擎存在API连接错误

### ISSUE THREAD

**Issue by Andrea-lyz** [xushengfeng/eSearch#269]
### 描述问题

局域网访问ollama，测试报错：TypeError: Cannot read properties of undefined (reading '0')
![image](https://github.com/user-attachments/assets/b64e1bbf-9599-4d4e-8657-469c1f98622b)

### 重现步骤

依照使用帮助填写相关选项
> 使用本地 LLM 模型翻译
> 你可以使用任何技术栈部署 LLM，但需要支持网络访问。下面以 ollama 为例。
> 
> 你需要在[ollama 官网](https://ollama.com/)下载并安装 ollama，添加模型。
> 
> 在设置中添加翻译器，翻译引擎选择“ChatGPT”，填入 url：[http://localhost:11434/api/chat，key](http://localhost:11434/api/chat%EF%BC%8Ckey) 必须随便填写一些内容，如“key”，config 则填入{"model":"你的模型"}，测试通过后，点击完成。拖动翻译器到第一个来默认启用。

同样尝试过/api/chat和/api/generate接口

### 期望结果

通过测试

### 更多信息

```
Failed to load resource: the server responded with a status of 404 (Not Found)
xtranslator.es.js:953 Uncaught (in promise) TypeError: Cannot read properties of undefined (reading '0')
    at xtranslator.es.js:953:67
192.168.0.4:8845/api/chat:1 
        
        
       Failed to load resource: the server responded with a status of 404 (Not Found)
xtranslator.es.js:953 Uncaught (in promise) TypeError: Cannot read properties of undefined (reading '0')
    at xtranslator.es.js:953:67
192.168.0.4:8845/api/generate:1
```

### 操作系统

版本	Windows 11 专业工作站版 版本号	23H2 安装日期	‎2024/‎8/‎26 操作系统版本	22631.4112 体验	Windows Feature Experience Pack 1000.22700.1034.0

### 软件版本

13.0.0

**Comment by xushengfeng** [comment]
已在代码中修复 f5fdb1514a80203571e230c6140cb5925cd69504 ，明天发布修复版

**Comment by Andrea-lyz** [comment]
> 已在代码中修复 [f5fdb15](https://github.com/xushengfeng/eSearch/commit/f5fdb1514a80203571e230c6140cb5925cd69504) ，明天发布修复版

引擎能不能加个不用key的Google翻译，就像沉浸式翻译那种直接使用的（ ollama反应还是太慢了

**Comment by xushengfeng** [comment]
我也有同感，我现在用api的是 https://github.com/chatanywhere/GPT_API_free ，个人感觉还行
其他不用key的翻译打算研究

**Comment by Andrea-lyz** [comment]
> 我也有同感，我现在用api的是 https://github.com/chatanywhere/GPT_API_free ，个人感觉还行 其他不用key的翻译打算研究

https://github.com/pot-app/pot-desktop?tab=readme-ov-file
也许可以参考一下隔壁Pot翻译，他家好多不用key的翻译引擎，只不过他是单纯做翻译相关
