### ISSUE TITLE
最新版 1.12mac 的 arm 崩溃

### ISSUE THREAD

**Issue by SONGjiemo** [xushengfeng/eSearch#274]
### 描述问题 Description of the problem

1.12.0-beta.4
最新版 mac 电脑 下载 arm 版本直接崩溃

### 重现步骤 Steps to reproduce

打开就崩溃了

### 软件版本 Software version

1.12

**Comment by xushengfeng** [comment]
我现在手头没mac
1.11.0崩溃吗
试一下13.0.1

**Comment by SONGjiemo** [comment]
> 我现在手头没mac 1.11.0崩溃吗 试一下13.0.1

13.1完美运行。
