### ISSUE TITLE
13.0.1截屏仍然存在图片偏移

### ISSUE THREAD

**Issue by cmyyx** [xushengfeng/eSearch#275]
### 描述问题 Description of the problem

Alt+C，向右下角偏移
<img width="1280" alt="image" src="https://github.com/user-attachments/assets/5c8daf59-7338-421c-bda6-b22a78d186d1">

在重启软件后的第一次截屏没有偏移
![image](https://github.com/user-attachments/assets/67e2922a-3840-4053-ad60-01dabe73fb47)

### 重现步骤 Steps to reproduce

屏幕缩放调整至150%并使用截屏功能

### 操作系统 OS

win11  23H2  22631.3880

### 软件版本 Software version

13.0.1

### 屏幕参数 Screen parameters

2560*1600 150%

**Comment by xushengfeng** [comment]
尝试在代码中修复 be76409fced9b1de30353302f9ab379d3850a7e8
https://github.com/xushengfeng/eSearch/releases/tag/13.1.0

**Comment by cmyyx** [comment]
> 尝试在代码中修复 [be76409](https://github.com/xushengfeng/eSearch/commit/be76409fced9b1de30353302f9ab379d3850a7e8) https://github.com/xushengfeng/eSearch/releases/tag/13.1.0

感谢,问题已解决
