### ISSUE TITLE
ocr识别图片文字错误

### ISSUE THREAD

**Issue by wang3680** [xushengfeng/eSearch#276]
### 描述问题 Description of the problem

识别错误
Error: The specified module could not be found.
\\?\E:\downloads\eSearch-13.1.0-win32-x64\resources\app\node_modules\onnxruntime-node\bin\napi-v3\win32\x64\onnxruntime_binding.node
请打开开发者工具（Ctrl+Shift+I）查看详细错误

### 重现步骤 Steps to reproduce

ocr识别报错

### 软件版本 Software version

13.1.0

**Comment by xushengfeng** [comment]
试一下重新下载软件？

**Comment by wang3680** [comment]
用的绿色版 用exe？



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2024年9月6日(周五) 下午5:42
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [xushengfeng/eSearch] ocr识别图片文字错误 (Issue #276)




 
试一下重新下载软件？

**Comment by xushengfeng** [comment]
我试了，都可以

**Comment by qqq-qqqq** [comment]
今天我也遇到了这个问题，eSearch版本1.12.4。
操作系统是Windows 7，同样的报错。
初步研究了一下，感觉是onnxruntime.dll的兼容性问题，根据  microsoft/onnxruntime#12718 ，可能从v1.13.1开始就不再支持Windows7了，而打包的onnxruntime.dll似乎是v1.18
