### ISSUE TITLE
A JavaScript error occurred in the main process

### ISSUE THREAD

**Issue by FHMinyi** [xushengfeng/eSearch#277]
### 描述问题 Description of the problem

第一次下载安装完后打开就报错了
![clipboard-image-1726021179](https://github.com/user-attachments/assets/2dd84168-6fa1-468a-80bf-872f14f1f34c)

### 重现步骤 Steps to reproduce

在releases页下载windows arm64 exe安装文件，安装在用户目录下
安装完，打开报错

### 操作系统 OS

windows arm64

### 软件版本 Software version

13.1.2

**Comment by xushengfeng** [comment]
已经定位问题了，是由于截屏依赖库没有安装，而提示安装的代码调用错误

可以通过下载安装 https://aka.ms/vs/17/release/vc_redist.arm64.exe 来避免提示安装，这样暂时不会报错

后续请等待修复版本发布

**Comment by xushengfeng** [comment]
我更新了软件版本，https://github.com/xushengfeng/eSearch/releases/tag/13.1.3 试试看

**Comment by FHMinyi** [comment]
> 我更新了软件版本，https://github.com/xushengfeng/eSearch/releases/tag/13.1.3 试试看

更新完启动软件后提示下载安装依赖，下载安装依赖后又重启软件一遍，但是**又**会提示要下载安装依赖
<img width="394" alt="clipboard-image-1726060595" src="https://github.com/user-attachments/assets/684d1de2-a04b-478b-b553-c6d7867f16cf">
点了取消后软件功能依旧用不了
而且每次启动软件时这个提示会跳出来两次

**Comment by xushengfeng** [comment]
我试着修复 https://github.com/xushengfeng/eSearch/releases/tag/13.1.6

**Comment by FHMinyi** [comment]
> 我试着修复 https://github.com/xushengfeng/eSearch/releases/tag/13.1.6

好了，可以运行了
