### ISSUE TITLE
Linux arm64 deb 包 Architecture 为 amd64，无法安装

### ISSUE THREAD

**Issue by lukashen** [xushengfeng/eSearch#279]
### 描述问题 Description of the problem

linux-arm64.deb 无法安装

### 重现步骤 Steps to reproduce

dpkg -I eSearch-13.1.6-linux-arm64.deb

### 期望结果 Expected behavior

Architecture: arm64

### 软件版本 Software version

13.0.0, 13.0.1, 13.1.0, 13.1.2, 13.1.3, 13.1.6

**Comment by xushengfeng** [comment]
我试着修复，目前在release里更新了
