### ISSUE TITLE
希望增加通过个人申请的API进行翻译的可选项

### ISSUE THREAD

**Issue by qqice** [xushengfeng/eSearch#28]
目前的翻译引擎看起来是直接通过url去获取公共翻译结果，能不能新增使用自定义的API获取翻译结果呢？

**Comment by xushengfeng** [comment]
是像ocr那样，我写好api的调用方式，只需提供密钥就可以使用，还是其他方案？
我有通过api聚合多种翻译引擎的打算

**Comment by qqice233** [comment]
> 写好api的调用方式，只需提供密钥就可以使用

是这样的

**Comment by xushengfeng** [comment]
d846628
我写了一个在线聚合翻译[eSearch-translator](https://github.com/xushengfeng/eSearch-translator)，目前还在测试。
它可以使用url调用` https://esearch-translator.netlify.app/?text=%s`，eSearch和浏览器都支持
它还可以自由组合翻译引擎。
欢迎对新项目进行反馈。
