### ISSUE TITLE
每次使用都会弹出控制台

### ISSUE THREAD

**Issue by xkaaaaa** [xushengfeng/eSearch#281]
### 描述问题 Description of the problem

每次按alt+c之后都①不会置顶（只有开机首次使用会出现这个问题），而且每次都②会弹出控制台（就是浏览器按F12弹出的那个菜单）。打开其他窗口也会弹出控制台。（例如：贴图、主页面）并且没按CTRL+shift+i
![image](https://github.com/user-attachments/assets/cf70a2af-c40b-4ee3-b966-b21494929e5b)
![image](https://github.com/user-attachments/assets/cf377bb1-71c6-4b87-8970-b507b6606566)

### 重现步骤 Steps to reproduce

/

### 操作系统 OS

win11

### 软件版本 Software version

最新

**Comment by xushengfeng** [comment]
右下角托盘菜单 退出开发者模式
