### ISSUE TITLE
更多免费免注册翻译api

### ISSUE THREAD

**Issue by dxyklp** [xushengfeng/eSearch#283]
### 描述 Description

屏幕翻译能增加一些免费和免注册的api吗？或者增加阿里云的api,百度的免费额度太低了

### 操作系统 OS

x64

### 当前软件版本 Current Version

13.1.6

**Comment by dxyklp** [comment]
隔壁的ttime的翻译搞的就不错，类似那样也可以，可惜他没有搞截图和贴图功能

**Comment by xushengfeng** [comment]
#271 
在搞了
这里还有一些免费的api，不过需要注册 [文档](https://github.com/xushengfeng/eSearch/blob/master/docs/use/translate.md#%E5%85%B6%E4%BB%96%E5%85%8D%E8%B4%B9-llm-%E7%BF%BB%E8%AF%91%E6%9C%8D%E5%8A%A1)

**Comment by xushengfeng** [comment]
在代码中加了，将在下一个版本更新
5237afb7b3d69e4b657af6d91a7e4f528d8b76e8

**Comment by dxyklp** [comment]
感谢
