### ISSUE TITLE
截图时图片存在右键菜单的残影

### ISSUE THREAD

**Issue by Bryan2333** [xushengfeng/eSearch#284]
### 描述问题 Description of the problem

RT，下面是这种情况的截图，留意光标所在的位置
![eSearch-2024-09-20-15-00-40-721](https://github.com/user-attachments/assets/4f2cdfff-2fdf-4d42-bb9b-f6a841d0fcf6)

### 重现步骤 Steps to reproduce

1. 启动e-search
2. 右键任务栏的托盘图标
3. 点击截屏搜索

### 期望结果 Expected behavior

没有右键菜单的残影

### 更多信息 Additional context

有意思的是这种情况只有**截屏搜索**会出现，**自动识别**就没有这种情况。

下面是我的系统信息：
Operating System: Arch Linux 
KDE Plasma Version: 6.1.5
KDE Frameworks Version: 6.5.0
Qt Version: 6.7.2
Kernel Version: 6.10.10-zen1-1-zen-cjktty (64-bit)
Graphics Platform: Wayland
Processors: 16 × AMD Ryzen 7 5800H with Radeon Graphics
Memory: 13.5 GiB of RAM
Graphics Processor: AMD Radeon Graphics

### 操作系统 OS

Arch Linux

### 软件版本 Software version

13.1.6

### 屏幕参数 Screen parameters

2880x1800 200%的缩放

**Comment by xushengfeng** [comment]
虽然图片中好像看不出来残影，但我应该理解你说的
kde菜单关闭后会有一个渐变动画，这不是截屏能控制的，不过有一个选项可以控制托盘菜单点击的延时，等菜单完全消失再开始截屏。这个选项不在设置里显示，需要到设置源文件（可以在设置-高级设置打开），把`主搜索功能`.`截屏搜索延迟`改为其他毫秒数，如`300`。
