### ISSUE TITLE
MacOS 15 Sequoia 无法安装

### ISSUE THREAD

**Issue by qiqiangvae** [xushengfeng/eSearch#285]
MacOS 15 Sequoia 无法安装，打开软件提示文件受损

**Comment by xushengfeng** [comment]
旧的软件版本可以安装吗，zip版本可以使用吗

**Comment by xushengfeng** [comment]
我看到[一篇博客](https://www.macat.vip/42320.html)，可以参考一下

**Comment by yeyk1991** [comment]
可以安装，但是菜单栏的图标不忍直视，太大了。

**Comment by xushengfeng** [comment]
在设置里可以调节

**Comment by yeyk1991** [comment]
<img width="166" alt="截屏2024-10-03 09 38 32" src="https://github.com/user-attachments/assets/9bcf767d-aa72-45c9-8b5c-3bcc7833f1fd">
看了一遍设置，没有见到这个项目的调节

**Comment by xushengfeng** [comment]
啊，你指的是托盘图标
我误会了你的意思
这个是bug，我试着修复
