### ISSUE TITLE
arm64 deb 提示安装vs库但是并没有说是什么东西，或者提供具体连接

### ISSUE THREAD

**Issue by tianmingwan** [xushengfeng/eSearch#287]
### 描述 Description

aka 那个网址下不了

**Comment by xushengfeng** [comment]
提示有误

你可以参考文档 https://github.com/xushengfeng/eSearch/blob/master/docs%2Fuse%2Fclip.md#linux-arm64 进行设置截屏
需要添加其他截屏命令作为外部截屏库
