### ISSUE TITLE
BUG：截屏后使用画笔无效

### ISSUE THREAD

**Issue by w154594742** [xushengfeng/eSearch#288]
### 描述问题 Description of the problem

画笔粗细设置的2px，截屏后使用画笔在图片上划线或圈选文字等操作后松开鼠标左键则之前的划线全部消失了

### 重现步骤 Steps to reproduce

任意截取一个图片，然后使用画笔工具按下鼠标左键在图片上任意划线，当松开鼠标左键后划线全部消失

### 操作系统 OS

win32 10.0.19045 (x64)

### 软件版本 Software version

13.1.6

**Comment by xushengfeng** [comment]
已在代码里修复 89f66ca0512835e811acbc0790417d5bcecba251
