### ISSUE TITLE
ubuntu18.04 截图后贴图存在鼠标指针抖动错误

### ISSUE THREAD

**Issue by mainDevgithub** [xushengfeng/eSearch#294]
### 描述问题 Description of the problem

截图后选择贴图，当鼠标指针不在贴图区域时，鼠标指针会发生轻微低频抖动，关掉贴图后恢复正常

### 重现步骤 Steps to reproduce

选择“自动识别”，截图，选择贴图
当鼠标指针在贴图区域之外，它会轻微低频抖动

### 更多信息 Additional context

ding-B0sw58rs.js:1 Uncaught 
RangeError: Incorrect locale information provided
    at new Segmenter (<anonymous>)
    at ding-B0sw58rs.js:1:12073

### 操作系统 OS

ubuntu18.04 LTS x64

### 软件版本 Software version

eSearch-14.1.0-linux-x64.deb

### 屏幕参数 Screen parameters

2560x1440 100%, 1920x1080 100%

**Comment by xushengfeng** [comment]
抖动是怎么样的
是大小变化、位置变化还是形状变化抖动？

**Comment by mainDevgithub** [comment]
https://github.com/user-attachments/assets/8be11d4f-e7c1-444c-b49e-c8a41007f9a1

**Comment by mainDevgithub** [comment]
> 抖动是怎么样的 是大小变化、位置变化还是形状变化抖动？

https://github.com/user-attachments/assets/8be11d4f-e7c1-444c-b49e-c8a41007f9a1

**Comment by xushengfeng** [comment]
关于光标的代码已经进行了优化。
不过，我在测试中发现，Linux系统下光标无法穿透贴图，这意味着贴图无法像正常窗口那样正常工作。这个问题是由于Electron框架的一个bug引起的。在Electron修复之前，可以按照[这份文档](https://github.com/xushengfeng/eSearch/blob/master/docs/use/ding.md)note中的说明进行临时修复。
