### ISSUE TITLE
mac启动报错

### ISSUE THREAD

**Issue by clddup** [xushengfeng/eSearch#297]
### 描述问题 Description of the problem

mac M3 启动报错

![image](https://github.com/user-attachments/assets/069f5edb-a67c-4e53-9d8d-9ea23b7b6d8b)

### 重现步骤 Steps to reproduce

github下载[eSearch-14.1.0-darwin-arm64.dmg](https://github.com/xushengfeng/eSearch/releases/download/14.1.0/eSearch-14.1.0-darwin-arm64.dmg)和[eSearch-14.1.0-darwin-arm64.zip](https://github.com/xushengfeng/eSearch/releases/download/14.1.0/eSearch-14.1.0-darwin-arm64.zip)。启动都不行

### 操作系统 OS

macbook pro m3。arm64

### 软件版本 Software version

14.1.0

**Comment by xushengfeng** [comment]
见 #285
这是mac的限制，互联网上有方法解除

**Comment by xushengfeng** [comment]
是 允许以下来源应用 那个选项吗
不是具体应用的设置，而是系统的设置

**Comment by clddup** [comment]
算了 不用了
