### ISSUE TITLE
刚安装时的那个ocr下载好慢啊，挂不挂梯都一样

### ISSUE THREAD

**Issue by RichardZhang4** [xushengfeng/eSearch#3]

**Comment by xushengfeng** [comment]
我用的是[fastgit](https://hub.fastgit.xyz)的镜像，一般情况下比github快，但有时可能会很慢。
重试一下吧。
如果实在无法下载，那就在[eSearch-OCR](https://github.com/xushengfeng/eSearch-OCR/releases/tag/2.0.0)或[fasthub](https://hub.fastgit.xyz/xushengfeng/eSearch-OCR/releases/tag/2.0.0)下载压缩包解压，把“ocr”文件夹移动到设置里显示的“配置目录”下。
我已经添加了下载进度显示，可能在下周末会推送。
