### ISSUE TITLE
eSearch和Dbeaver存在冲突

### ISSUE THREAD

**Issue by heyXiaoT** [xushengfeng/eSearch#300]
### 描述问题 Description of the problem

在Dbeaver的数据页面按截图快捷键（我设置了 shift + ctrl + alt + s 截图，可随意修改快捷键复现），会先执行 shift + ctrl + alt + c 的快捷键（Dbeaver的快捷键） 再去 执行 eSearch 快捷键shift + ctrl + alt + s；

### 重现步骤 Steps to reproduce

1.  设置自动识别快捷键
![image](https://github.com/user-attachments/assets/4ed2c802-a191-4268-a6c8-17777aa74ee7)
2. 打开Dbeaver，开启一个SQL窗口，随意写一条可执行的SQL
![image](https://github.com/user-attachments/assets/37cf3a4a-ab77-4ec0-9433-b1431831e7f7)
3. 使用自动识别的快捷键截图，此时会先执行Dbeaver的 shift + ctrl + alt + c  快捷键，再去执行 eSearch 快捷键
![image](https://github.com/user-attachments/assets/e85d0e05-34c5-4cd5-a526-10689668f6b8)

eSearch：14.1.6
Dbeaver：微软商店下载的 24.2.3 

### 操作系统 OS

Windows 11 x64

### 软件版本 Software version

14.1.6

**Comment by xushengfeng** [comment]
自动识别会自动按下ctrl+c，所以冲突了
以后可能会考虑更改默认快捷键
