### ISSUE TITLE
录屏存在无法结束录屏

### ISSUE THREAD

**Issue by Haven-Lv** [xushengfeng/eSearch#303]
### 描述问题 Description of the problem

当录全屏时，录屏趋于y轴或者是屏幕的全部时，录屏控制栏被遮挡，但是任务栏有录屏控制栏的图标但是无法点开操作

### 重现步骤 Steps to reproduce

当录全屏时，录屏趋于y轴或者是屏幕的全部时，录屏控制栏被遮挡，但是任务栏有录屏控制栏的图标但是无法点开操作

### 操作系统 OS

Windows11

### 软件版本 Software version

14.1.7

**Comment by xushengfeng** [comment]
尝试在代码中修复 e88ddc6 将在下一个版本发布更新
