### ISSUE TITLE
 eSearch 配置无法便携，preload_config

### ISSUE THREAD

**Issue by neatgz** [xushengfeng/eSearch#304]
eSearch-14.1.7-win32-x64.zip
解压后，按照 https://github.com/xushengfeng/eSearch/blob/master/docs/use/setting.md
的说明，设置配置文件的存储目录。
重启软件后，配置仍然存储在 %AppData%/eSearch
修改软件设置， %AppData%/eSearch 目录下的配置文件会变，但是自定义的配置文件夹里的配置文件不变。
确认软件目录存在 preload_config 文件。

**Comment by xushengfeng** [comment]
如果只是需要便携版，可以参考 https://github.com/xushengfeng/eSearch/blob/master/docs/use/main.md#便携版绿色版 在运行目录下创建`portable`文件夹
preload_config更多是用来自定义配置路径

**Comment by neatgz** [comment]
> 如果只是需要便携版，可以参考 [https://github.com/xushengfeng/eSearch/blob/master/docs/use/main.md#便携版绿色版](https://github.com/xushengfeng/eSearch/blob/master/docs/use/main.md#%E4%BE%BF%E6%90%BA%E7%89%88%E7%BB%BF%E8%89%B2%E7%89%88) 在运行目录下创建`portable`文件夹 preload_config更多是用来自定义配置路径

大佬您好，还是无法便携！是我的设置有问题吗？
win10 x64 虚拟机 全新安装 的系统
eSearch-14.1.7-win32-x64.zip 解压到桌面，目录下新建 portable 文件夹，运行主程序。配置文件仍然存储在 %AppData%
portable 文件夹是空的。

![PixPin_2024-11-05_11-24-14](https://github.com/user-attachments/assets/58c6de7f-9083-432e-8ec3-e3fbe2086d10)

**Comment by xushengfeng** [comment]
运行目录是`resources/app`，在下面新建`portable`文件夹
之后版本我会添加通过点击迁移的功能

**Comment by neatgz** [comment]
感谢解惑！非常感谢。
