### ISSUE TITLE
贴图存在错误

### ISSUE THREAD

**Issue by earautumn** [xushengfeng/eSearch#305]
### 描述问题 Description of the problem

![image](https://github.com/user-attachments/assets/8ee400ff-92f8-4342-9302-38dc7c0e9ca3)

### 重现步骤 Steps to reproduce

截屏后固定时总会弹出一个错误。

### 操作系统 OS

windows 11 x64

### 软件版本 Software version

14.1.7

**Comment by xushengfeng** [comment]
我试着在代码里修复了 0377979
可以先在翻译-屏幕翻译设置目标语言作为临时解决方案
