### ISSUE TITLE
截图后编辑设置默认矩形格式-透明填充

### ISSUE THREAD

**Issue by simonheard** [xushengfeng/eSearch#306]
### 描述 Description

现在的设置可以设置边框颜色，填充颜色，和边框粗细，可否添加一个透明填充的选项？个人比较喜欢截图后用红色框提示重点
或者如果可以改配置文件达到这个效果也可以

### 操作系统 OS

windows

### 当前软件版本 Current Version

14.1.7

**Comment by xushengfeng** [comment]
填充颜色的透明度是可以调节的，就在属性 颜色代码下面，拖动可调节

**Comment by simonheard** [comment]
@xushengfeng 不好意思没有表达清楚 想问的是可不可以设置默认配置？因为每次都要调节比较繁琐

**Comment by xushengfeng** [comment]
调过一次就记住了，你试试

**Comment by simonheard** [comment]
好像是的 没注意到之前一直用的旧版本 感谢！
