### ISSUE TITLE
“位置信息”可改

### ISSUE THREAD

**Issue by Super-Zoe** [xushengfeng/eSearch#32]
你好：
使用了离线OCR，**离线OCR配置**可以改；但是在**高级**中的**位置信息**无法变动，导致离线OCR总是失败，希望**位置信息**也可以改变，谢谢

**Comment by xushengfeng** [comment]
是1.7.3版本吗？

**Comment by xushengfeng** [comment]
1.7.3版本下，配置目录改了，ocr目录和文件目录也一起更改，更改时需要运行目录的读写权限，重启软件生效。

支持相对路径。你在https://github.com/xushengfeng/eSearch/issues/12#issuecomment-1184161641 提到“配置目录、临时目录这些路径可以改成运行目录的路径一样”，你可以在运行目录下建一个配置文件夹，比如`x`，然后更改高级里的配置目录为`./x`，复制目录，重启就可以了。

我测试过1.7.3版本的ocr，即使改了配置目录也能正常工作，如果还是出问题，还请麻烦再提个issue。
