### ISSUE TITLE
绿色版和安装版打开都出错

### ISSUE THREAD

**Issue by ranny0921** [xushengfeng/eSearch#33]
**描述问题**

**重现步骤**

1. 在……界面
2. 点击
3. 发生错误

**本应该**
显示 xxx

**屏幕截图**
![Snipaste_2022-07-19_14-45-14](https://user-images.githubusercontent.com/3004050/179684343-7317a78c-c7f5-46db-8202-f9177ac5950b.png)

**设别和软件信息**

-   操作系统和具体版本:LTSC2021
-   屏幕参数: 17.3寸，1920*1080，1 倍缩放
-   软件版本: 1.7.2/1.73两个版本都报错

**更多信息**

**Comment by xushengfeng** [comment]
此电脑下有“视频”这个文件夹吗

**Comment by ranny0921** [comment]
> 此电脑下有“视频”这个文件夹吗

没有，我把默认存储的文件夹转到D盘了，此电脑下“视频”之类的文件夹全删了！

**Comment by ranny0921** [comment]
> 此电脑下有“视频”这个文件夹吗

果然在默认“视频”的位置新建了“videos”文件夹重启就好了！

**Comment by xushengfeng** [comment]
好吧……你试试在你D盘下新建`Videos`文件夹
我增加了对无相关文件夹的判断来避免错误 2d0c54d ，将在下一个版本更新
