### ISSUE TITLE
界面配置修改无法生效

### ISSUE THREAD

**Issue by Super-Zoe** [xushengfeng/eSearch#35]
你好：
 window1.7.3（便携版本）发现有以下两个问题：

1. 在**配置界面**进行修改（譬如修改搜索引擎），然后图标**右键选择重启软件**，重启软件后，**修改的配置无法生效**——**只能手动退出软件后，再手动启动方能生效**
2. **改变配置目录的位置，OCR测试没有问题**；但当**重启电脑**，自启动的软件仍会弹出OCR服务需要重新安装，此时查看配置文件，配置目录的位置又回到了默认位置——**也只能手动退出软件后，再手动启动，配置目录才发生变动，OCR正常工作**

**Comment by xushengfeng** [comment]
1. 设置界面需要正常关闭才能保存设置
2. 是bug

**Comment by Super-Zoe** [comment]
让eSearch自己重启，应该算是界面正常关闭吧 

![image](https://user-images.githubusercontent.com/39052286/180030207-32b6d624-bb2b-4ca0-b204-bd666c2af248.png)

**这样子的重启 配置还是无法生效**

**Comment by xushengfeng** [comment]
这算是我设计疏忽了

**Comment by xushengfeng** [comment]
修复第二个问题 0b51972

**Comment by db-one** [comment]
@Super-Zoe @xushengfeng 请问配置文件目录是在什么地方更改的？ 我新下载的1.7.4绿色版运行默认配置文件就是在C盘，不会提示配置目录，设置里面也没有找到可更改选项
![image](https://user-images.githubusercontent.com/20243226/183284253-30b3300b-6e74-4baf-b753-af7604619f98.png)
![image](https://user-images.githubusercontent.com/20243226/183284280-48a88b75-6c0c-47af-8931-36470609a0f9.png)

**Comment by xushengfeng** [comment]
> @Super-Zoe @xushengfeng 请问配置文件目录是在什么地方更改的？ 我新下载的1.7.4绿色版运行默认配置文件就是在C盘，不会提示配置目录，设置里面也没有找到可更改选项 ![图像](https://user-images.githubusercontent.com/20243226/183284253-30b3300b-6e74-4baf-b753-af7604619f98.png) ![image](https://user-images.githubusercontent.com/20243226/183284280-48a88b75-6c0c-47af-8931-36470609a0f9.png)

位置信息 配置目录 右侧有一个输入框

**Comment by db-one** [comment]
好的，谢谢回复，另外问一下，我已经下载了离线ocr,但是启动时候会弹出离线OCR版本过低，让重新下载
https://github.com/xushengfeng/eSearch-OCR
从这里下载的2.5.0版本的

**Comment by db-one** [comment]
![image](https://user-images.githubusercontent.com/20243226/183285249-bd3be0a9-69ed-445c-926a-e2546f0f3fcc.png)
输入之后重启或者Crtl+R刷新界面  都会直接消失，不会保存设置

**Comment by xushengfeng** [comment]
> ![image](https://user-images.githubusercontent.com/20243226/183285249-bd3be0a9-69ed-445c-926a-e2546f0f3fcc.png)输入之后重启或者Crtl+R刷新界面 都会直接消失，不会保存设置

看看软件运行目录下是否有preload_config文件，或用管理员权限试试
