### ISSUE TITLE
使用代理后仍然无法使用谷歌以图搜图

### ISSUE THREAD

**Issue by Super-Zoe** [xushengfeng/eSearch#36]
你好：
仍然是window1.7.3版本：
**谷歌搜图**会出现 类似Error：connect ETIMEDOUT 
1. eSearch**搜索可以访问**谷歌 但是eSearch**搜图无法访问** ——好奇 eSearch中的google搜图是怎么实现的？
2. 尝试过用**eSearch配置代理访问**但未成功，**正确的配置方法**应该是怎么样？
3. eSearch代理选项能否增加个**系统代理**的选项呢？

**Comment by xushengfeng** [comment]
1&2. 使用nodejs的http模块进行访问，还没与主程序共享代理配置。
3. 我只提供了electron的官方设置，好像没有系统代理接口，详见[官方文档](https://www.electronjs.org/zh/docs/latest/api/session#sessetproxyconfig)。

你的搜索是如何访问谷歌的？通过软件的代理吗？

**Comment by Super-Zoe** [comment]
1. eSearch**搜索**用的是**主程序代理配置**（这个配置好像也没看见），而eSearch**搜图**用的是**nodejs的http模块**？要是可以**共享代理配置**就好了
2. 看了一下，electron官方文档是有系统代理的吧？
![image](https://user-images.githubusercontent.com/39052286/180262396-3441683d-63d0-4344-8bd0-d2a15386a009.png)
3. 是的，Clash开启系统代理
4. 又尝试了eSearch的代理配置，怎么设置都不生效，设置的PAC如下，来源于[例 3](https://developer.mozilla.org/zh-CN/docs/Web/HTTP/Proxy_servers_and_tunneling/Proxy_Auto-Configuration_PAC_file#%E4%BE%8B_3)
`
function FindProxyForURL(url, host) {
  if (isResolvable(host))
    return "DIRECT";
  else
    return "PROXY 127.0.0.1:7890";
}

`

**Comment by xushengfeng** [comment]
尴尬了，1.7.0合并浏览器和主界面时就把代理相关的代码去掉了。但你使用谷歌搜索仍然正常，说明在不需要eSearch设置代理的情况下是能访问谷歌的，但搜图却无法工作。
你使用电脑上的浏览器能访问谷歌搜图吗？使用eSearch的浏览器呢（在主页面输入网址，选中打开）？

**Comment by Super-Zoe** [comment]
1. 电脑上的浏览器和eSearch的浏览器**两者都可以访问谷歌搜图**https://www.google.com/imghp，但**eSearch浏览器**里面在上传图片搜索时，总是会“检测到您的计算机网络中存在异常流量”，**弹出验证码窗口**，而**电脑浏览器正常搜图**。是不是这个的问题导致的？
2. 一般浏览器默认使用系统代理，无需设置

**Comment by Super-Zoe** [comment]
1. 电脑上的浏览器和eSearch的浏览器**两者都可以访问谷歌搜图**https://www.google.com/imghp，但**eSearch浏览器**里面在上传图片搜索时，总是会“检测到您的计算机网络中存在异常流量”，**弹出验证码窗口**，而**电脑浏览器正常搜图**。是不是这个的问题导致的？
2. 一般浏览器默认使用系统代理，无需设置

**Comment by xushengfeng** [comment]
e26f7b5 尝试修复
你试一下这个[测试版](https://wwt.lanzouv.com/isLL9088a6wf)能否正常工作

**Comment by Super-Zoe** [comment]
google搜图还是有问题 会**弹出以下的窗口**，不过这个的**eSearh浏览器可以正常google搜图**
![image](https://user-images.githubusercontent.com/39052286/180432363-08ea64a4-37e6-4bd1-b8d8-91a513e79b8a.png)

**Comment by xushengfeng** [comment]
抱歉，有些模块没打包进来 这是[测试版2](https://wwt.lanzouv.com/iFQCO088pufc)

**Comment by Super-Zoe** [comment]
google搜图还是有问题 eSearh浏览器可以正常google搜图 跟之前一样
![1658506735643](https://user-images.githubusercontent.com/39052286/180481819-77291e45-8259-4e90-b391-482871c96b7a.jpg)

**Comment by xushengfeng** [comment]
好吧，我试着准备个代理环境再详细测试一下，看看能不能解决

**Comment by xushengfeng** [comment]
[测试版3](https://wwt.lanzouv.com/itO2l08catqb)

**Comment by Super-Zoe** [comment]
这个可以搜图了
