### ISSUE TITLE
Electron在 Ubuntu 16.04 的bug

### ISSUE THREAD

**Issue by Z-Fran** [xushengfeng/eSearch#38]
Electron在 old Ubuntu版本有个bug https://github.com/electron/electron/issues/34118 ，Electron已修复，我安装esearch遇到了，不知道esearch有没有更新Electron版本

**Comment by Z-Fran** [comment]
现在用的是18.1版本，可升级到18.2.2版本
https://github.com/electron/electron/releases?page=6

**Comment by xushengfeng** [comment]
我会尝试更新electron的，因为eSearch所依赖的robotjs经常在更新electron时无法正常编译，所以eSearch的electron更新比较保守，但还是会更的
