### ISSUE TITLE
设置里粘贴失效

### ISSUE THREAD

**Issue by zronghui** [xushengfeng/eSearch#39]
**描述问题**
设置百度 OCR key，用 command v 粘贴，快捷键亮了，但是没有生效，手敲可以，但是也太傻了吧
**重现步骤**

1. 在……界面
2. 点击
3. 发生错误

**本应该**
显示 xxx

**屏幕截图**
可选

**设别和软件信息**

-   操作系统和具体版本: [如： Win11 专业版 pre 25158] Mac
-   屏幕参数: [如：15.6 寸，1920*1080，1.25 倍缩放]
-   软件版本: [如：1.7.2] 目前最新

**更多信息**

**Comment by xushengfeng** [comment]
已在代码中修复 6fa2f10ff4c3da1e506c01dc469e39a7994b97db
