### ISSUE TITLE
ffmpeg无法选择文件位置

### ISSUE THREAD

**Issue by lemontree1433223** [xushengfeng/eSearch#40]
windows11系统，选择后无效

**Comment by xushengfeng** [comment]
怎么个无效？是输入框没显示文件路径，还是录屏后提示错误？选择后的文件名是什么？

**Comment by lemontree1433223** [comment]
输入框没有显示文件路径
![image](https://user-images.githubusercontent.com/54848981/182767316-22697e6c-5967-4a96-a29a-a10b755620d1.png)
这是我下载的ffmpeg版本

**Comment by xushengfeng** [comment]
1.8.0 版本已无需下载ffmpeg
