### ISSUE TITLE
历史记录的时间，window 下显示与北京时间差了12h

### ISSUE THREAD

**Issue by rubnet** [xushengfeng/eSearch#42]
历史记录里的时间 与北京时间 差了12h

ctrl+s 保存

1. 在主页面
2. 点击历史记录图标
3. 显示与北京时间差了12h

**本应该**
显示系统本地时间 

**屏幕截图**
可选

**设别和软件信息**

-   操作系统和具体版本: [如： Win10]
-   屏幕参数: [如：15.6 寸，1920*1080，1.25 倍缩放]
-   软件版本: [如：[eSearch.Setup.1.7.4.exe](https://github.com/xushengfeng/eSearch/releases/download/1.7.4/eSearch.Setup.1.7.4.exe)]

**更多信息**

**Comment by xushengfeng** [comment]
默认是12小时制，若要更改，请参阅 设置-保存-时间代码
