### ISSUE TITLE
eSearch在ubuntu20.04.4无法正常使用

### ISSUE THREAD

**Issue by cqwlxxl** [xushengfeng/eSearch#43]
**描述问题**

使用eSearch时，主屏幕只能框选上半部分，且表现为无法识别图像，拾色器始终为#000000，然后第二个屏幕也未能识别。
无法正常截屏，点击贴图也没有效果。

**复现步骤**

1. 在 [https://esearch.vercel.app/](https://esearch.vercel.app/)下载了deb版本1.7.4
2. 于ubuntu20.04.4安装
3. 正常打开软件后，使用Alt+C截图

**屏幕截图**

![eSearch1 7 4-ubuntu20 04 4](https://user-images.githubusercontent.com/90250048/185826269-9c5f75fc-9e31-44a9-b889-67990ca36912.jpg)

**设别和软件信息**

-   操作系统和具体版本: ubuntu 20.04.4 amd64
-   屏幕参数: 1920*1080 笔记本 1.0缩放率
-   软件版本: 1.7.4

**Comment by xushengfeng** [comment]
ubuntu默认使用wayland，eSearch暂不支持wayland，若想使用，还要在登录界面切换为x window

**Comment by cqwlxxl** [comment]
> ubuntu默认使用wayland，eSearch暂不支持wayland，若想使用，还要在登录界面切换为x window

这个版本ubuntu使用的就是x window，如下：
![x11a](https://user-images.githubusercontent.com/90250048/185846544-83014edc-8f01-4713-9e0b-b843a3106829.png)
![x11b](https://user-images.githubusercontent.com/90250048/185846559-e26bf9e9-84e0-4376-808d-452989196879.png)
安装的时候有个Error，不知道会不会影响使用：
`Error in type 'unknown/unknown' (in /usr/share/mime/packages/esearch.xml): Invalid MIME-type 'image/png;image/jpg;image/svg'.`

**Comment by xushengfeng** [comment]
了解，我会试着解决

**Comment by xushengfeng** [comment]
我的Ubuntu下软件表现正常，怀疑是多屏的问题，目前eSearch暂不支持多屏，你试着移除多屏后软件能否正常工作

**Comment by tianws** [comment]
> 我的Ubuntu下软件表现正常，怀疑是多屏的问题，目前eSearch暂不支持多屏，你试着移除多屏后软件能否正常工作

遇到同样的问题，移除多屏后能正常截图，安装deb的时候也遇到了和上面一样的报错。

**Comment by firstuanl** [comment]
安装包有个图链接错误。

orc一直扫，不出结果，终端也没提示？

**Comment by firstuanl** [comment]
./esearch 
[26910:1022/081300.649952:ERROR:gpu_memory_buffer_support_x11.cc(44)] dri3 extension not supported.
[27729:1022/082306.199290:ERROR:sdp_offer_answer.cc(2154)] Failed to set local offer sdp: The order of m-lines in subsequent offer doesn't match order from previous offer/answer.
[26927:1022/082306.219418:ERROR:socket_manager.cc(127)] Failed to resolve address for stun.services.mozilla.com., errorcode: -105

**Comment by firstuanl** [comment]
取色器值为0

**Comment by xushengfeng** [comment]
> 安装包有个图链接错误。
> 
> orc一直扫，不出结果，终端也没提示？

哪个图？

**Comment by xushengfeng** [comment]
[1.9.0-beta](https://github.com/xushengfeng/eSearch/releases/tag/1.9.0-beta) 提供了多屏支持，应该能正常截屏，欢迎测试

**Comment by firstuanl** [comment]
终端显示没保存，一直安装不了就直接解包使了。

1.9之后libc有点高

**Comment by xushengfeng** [comment]
> 终端显示没保存，一直安装不了就直接解包使用了。
> 
> 1.9之后libc有点高

那截屏和ocr能正常使用了吗

**Comment by firstuanl** [comment]
这个地方不知怎传图。

重新安装下，是16×16那个图。ubuntu16.04,1.8和1.9的包装不上。之前不记得哪个版本的可正常安装。
解包，1.8可以打开，截屏可以，选中也可就search, OCR是空的，出不了东西。

**Comment by xushengfeng** [comment]
> 这个地方不知怎传图。
> 
> 重新安装下，是16×16那个图。ubuntu16.04,1.8和1.9的包装不上。之前不记得哪个版本的可正常安装。 解包，1.8可以打开，选中也可就search, OCR是空的，出不了东西。

拖动图片到输入框就可以了。1.9.0的解包后无法运行吗？

**Comment by firstuanl** [comment]
ubuntu16.04 libc不够高，1.9运行不了，这个正常，高版的软件我通常用flatpak包。file:///home/firstuanl/Pictures/2022-10-22_14-54.png
file:///home/firstuanl/Pictures/2022-10-22_08-21.png

**Comment by xushengfeng** [comment]
> ubuntu16.04 libc不够高，1.9运行不了，这个正常，高版的软件我通常用flatpak包。
> 
> 拖动图片到输入框变成路径……

我更新了AppImage版本的 eSearch，你可以测试一下他的截屏是否正常

**Comment by firstuanl** [comment]
AppImage包 解决不了libc低版本问题。要在低版本系统编译。这软件太大要编译需太久时间……
我先在另一台试试

**Comment by xushengfeng** [comment]
> AppImage包 解决不了libc低版本问题。要在低版本系统编译。这软件太大要编译需太久时间…… 我先在另一台试试

可以在package.json build.linux.target 下删除不必要的编译格式，或运行`npm run pack`直接编译成解包的目录

**Comment by firstuanl** [comment]
20.04可以
