### ISSUE TITLE
AUR源依赖

### ISSUE THREAD

**Issue by du33169** [xushengfeng/eSearch#46]
从AUR安装e-search（非git版本），安装后发现e-search依赖较多，其中甚至有Clion，占用较大硬盘空间
换而尝试安装最新的1.8.0版本deb包后发现并没有上述依赖。
是否可以将AUR源中的这些依赖删除？

另外[AUR上这个包](https://aur.archlinux.org/packages/e-search)版本还在1.7.3，目前应该过时了。

**Comment by xushengfeng** [comment]
我找时间更
