### ISSUE TITLE
OCR英文单词之间的空格无法识别

### ISSUE THREAD

**Issue by owen313** [xushengfeng/eSearch#47]
**描述问题**
OCR英文单词之间的空格和一些字符无法识别，请问怎么解决？
**重现步骤**

1. 在……界面
2. 点击
3. 发生错误

**本应该**
显示 xxx

**屏幕截图**
可选
![image](https://user-images.githubusercontent.com/45940081/187136473-21b7e7fb-fca9-44ad-b46f-6c5fc2db889a.png)

**设别和软件信息**

-   操作系统和具体版本: [如： Win11 专业版 pre 25158]
-   屏幕参数: [如：15.6 寸，1920*1080，1.25 倍缩放]
-   软件版本: [如：1.7.2]

**更多信息**

**Comment by xushengfeng** [comment]
了解，我会试着改进

**Comment by owen313** [comment]
期待ing

**Comment by xushengfeng** [comment]
6d57a3d 下一版本将自动拆分英文句子
