### ISSUE TITLE
记忆 截图尺寸？

### ISSUE THREAD

**Issue by yilksd** [xushengfeng/eSearch#48]
eSearch 可以以确定的尺寸截图，比如设定1280x720。但是截图保存以后，下次再启动，截图尺寸会被重置。能不能记忆上次的截图尺寸？在设置里没找到这个功能。
**设备和软件信息**

-   操作系统和具体版本: [如： Win11 专业版 pre 25158]
 windows server 2012 
-   软件版本: [如：1.7.2]
1.7.4
**请自由地描述你的提议（如有多个不同方向的建议，最好分成几个issue）**

**Comment by xushengfeng** [comment]
会考虑加

**Comment by xushengfeng** [comment]
1b1d17b
