### ISSUE TITLE
在帮助文档里没有找到长截图的使用方法

### ISSUE THREAD

**Issue by GJKen** [xushengfeng/eSearch#5]
刚刚下载体验了一下,
长截图功能点击后会有个选框出来自己选择区域, 选区完毕之后会出现一个置顶的框框 并且右下角会有个红色圆点停止结束, 但也就仅此而已了, 在点击结束之前完全不知道要怎么做长截图.

**Comment by xushengfeng** [comment]
感谢提醒
在这里更新了 fef84d3，下一版本会有
