### ISSUE TITLE
绘制形状的按钮貌似藏的有点深，建议优化下

### ISSUE THREAD

**Issue by sun868102** [xushengfeng/eSearch#50]
如下图，截图时，如果要框选。得 编辑 > 形状 > 方框 这么操作。貌似有点麻烦。。。

建议可以优化下按钮分布，或添加配置项，可以设置截图时默认的操作选项

![image](https://user-images.githubusercontent.com/3632792/187859133-b7f4d22c-20cd-481b-b7ec-f23679ec4209.png)

**Comment by wuxyhc** [comment]
那个是涂鸦，截图随便就能截。

**Comment by xushengfeng** [comment]
cb64f6b 默认展示编辑框
18790b1 编辑框悬浮切换子项
