### ISSUE TITLE
设置快捷键无法保存.保存按钮不清晰

### ISSUE THREAD

**Issue by GuoZheng-Lv** [xushengfeng/eSearch#52]
**描述**
使用快捷键使用软件更加便捷,设置快捷键时候保存没有找到,使用ctlr+s都是使用了
**重现步骤**
设置快捷键保存,设置快捷键保存误操作, 点击top-right的X号会出现向上滑动

**Comment by xushengfeng** [comment]
691f2e938342ee3498a0ae11af499971b8499f21
