### ISSUE TITLE
文字识别以后不自动选中了

### ISSUE THREAD

**Issue by juzizhilian** [xushengfeng/eSearch#54]
**描述**

**重现步骤**

1. 在…识别结果…界面
2. 点击
3. 发生错误或不是我预想的那样

**需求**
本应该显示 xxx，需要 xxx 新功能来代替

**屏幕截图**
可选

**设别和软件信息**

-   操作系统和具体版本: [如： Win11 专业版 pre 25158]
-   屏幕参数: [如：15.6 寸，1920*1080，1.25 倍缩放]
-   软件版本: [如：1.7.2]

**自由描述**
原来用的1.5版本，升级到1.8   文字识别以后不自动选中了

**Comment by xushengfeng** [comment]
784b43f 已经修复，下一个版本发
