### ISSUE TITLE
文字识别的问题

### ISSUE THREAD

**Issue by martjay** [xushengfeng/eSearch#55]
**描述问题**
没有空格，怎么没有逗号还自动加，无法保留正确格式

**重现步骤**

1. 在OCR界面
2. 点击
3. 发生错误

**本应该**
显示 xxx

**屏幕截图**
https://i.ibb.co/vJ29NjW/111111.jpg

**设别和软件信息**

-   操作系统和具体版本: [如： Win11 专业版 pre 25158]
-   屏幕参数: [如：15.6 寸，1920*1080，1.25 倍缩放]
-   软件版本: [如：1.7.2]

**更多信息**

**Comment by xushengfeng** [comment]
英文的格式识别还待优化

**Comment by xushengfeng** [comment]
https://github.com/xushengfeng/eSearch/issues/47#issuecomment-1277343339
下一个版本将通过字典自动识别英文空格，OCR识别空格还在优化
