### ISSUE TITLE
OCR功能到底杂用？

### ISSUE THREAD

**Issue by shileiye** [xushengfeng/eSearch#58]
打开eSearch按快捷键alt+c进入截图模式，然后对有文字的区域进行框选后按工具条的OCR识别，那块选择区域就一直显示动态的扫描线，等10分钟都没啥变化。请问这个OCR的识别到底怎么用？设置里面也是选择的默认离线OCR。win11，不知道是不是系统原因。

**Comment by xushengfeng** [comment]
试试小范围ocr能不能用？

**Comment by xushengfeng** [comment]
1.9.0和1.9.1版本优化了ocr性能，也提供了更多报错信息，你试试看新版本ocr能不能正常使用。

**Comment by shileiye** [comment]
> 1.9.0和1.9.1版本优化了ocr性能，也提供了更多报错信息，你试试看新版本ocr能不能正常使用。

录了个屏，最新的1.9.1版本，还是一样的
https://user-images.githubusercontent.com/7674680/200207721-0f64d08e-ddb2-4e79-9a7b-323a7e45c046.mp4

**Comment by xushengfeng** [comment]
![eSearch-2022-11-07-18-49-23](https://user-images.githubusercontent.com/28475549/200292415-38ab7e5d-760d-49b4-9d84-a00ce63c8d0b.png)
鼠标悬浮在按钮上，正常的应该显示`OCR(文字识别) - 默认`，而你的不显示默认。你点击按钮右上角浅色的小圆点，他会弹出引擎选择框，你看看默认在不在，然后看看 设置-文字识别（OCR）-离线OCR 是否有像我这样的有一个“默认”项。
![eSearch-2022-11-07-18-53-35](https://user-images.githubusercontent.com/28475549/200293095-8b450516-ea14-4ceb-8125-a4fe73767f88.png)
如果没有，在 设置-高级 恢复默认设置

**Comment by shileiye** [comment]
> ![eSearch-2022-11-07-18-49-23](https://user-images.githubusercontent.com/28475549/200292415-38ab7e5d-760d-49b4-9d84-a00ce63c8d0b.png) 鼠标悬浮在按钮上，正常的应该显示`OCR(文字识别) - 默认`，而你的不显示默认。你点击按钮右上角浅色的小圆点，他会弹出引擎选择框，你看看默认在不在，然后看看 设置-文字识别（OCR）-离线OCR 是否有像我这样的有一个“默认”项。 ![eSearch-2022-11-07-18-53-35](https://user-images.githubusercontent.com/28475549/200293095-8b450516-ea14-4ceb-8125-a4fe73767f88.png) 如果没有，在 设置-高级 恢复默认设置

选择默认没用···恢复默认设置起作用了···感谢···
另外那个代理怎么填写？我只有IP，PAC没得，不晓得怎么填啊。我用谷歌翻译···只能通过代理···

**Comment by xushengfeng** [comment]
https://www.electronjs.org/zh/docs/latest/api/session#sessetproxyconfig 我用了官方功能，你有ip的话，应该只用填 proxyRules 就行了。因为我没用代理，所以不太了解。实在不行可以设置系统代理，也就是开了代理并且不填写其他项目



在 2022-11-08 10:08:44，"shileiye" ***@***.***> 写道：

鼠标悬浮在按钮上，正常的应该显示OCR(文字识别) - 默认，而你的不显示默认。你点击按钮右上角浅色的小圆点，他会弹出引擎选择框，你看看默认在不在，然后看看 设置-文字识别（OCR）-离线OCR 是否有像我这样的有一个“默认”项。 如果没有，在 设置-高级 恢复默认设置

选择默认没用···恢复默认设置起作用了···感谢···
另外那个代理怎么填写？我只有IP，PAC没得，不晓得怎么填啊。我用谷歌翻译···只能通过代理···

**Comment by shileiye** [comment]
> https://www.electronjs.org/zh/docs/latest/api/session#sessetproxyconfig 我用了官方功能，你有ip的话，应该只用填 proxyRules 就行了。因为我没用代理，所以不太了解。实在不行可以设置系统代理，也就是开了代理并且不填写其他项目 在 2022-11-08 10:08:44，"shileiye" ***@***.***> 写道： 鼠标悬浮在按钮上，正常的应该显示OCR(文字识别) - 默认，而你的不显示默认。你点击按钮右上角浅色的小圆点，他会弹出引擎选择框，你看看默认在不在，然后看看 设置-文字识别（OCR）-离线OCR 是否有像我这样的有一个“默认”项。 如果没有，在 设置-高级 恢复默认设置 选择默认没用···恢复默认设置起作用了···感谢··· 另外那个代理怎么填写？我只有IP，PAC没得，不晓得怎么填啊。我用谷歌翻译···只能通过代理··· — Reply to this email directly, view it on GitHub, or unsubscribe. You are receiving this because you commented.Message ID: ***@***.***>

我的代理IP类似：127.0.0.1:10809
最多还有个用户名和密码···理论上软件不是只填代理IP即可？现在这个配置看的有点头大啊···

**Comment by xushengfeng** [comment]
我研究一下，应该是在 proxyRules 填入 `http://用户名:密码@127.0.0.1:10809` 你试试

**Comment by xushengfeng** [comment]
代理在 #74 讨论，便于集中问题。这个issue先关了

**Comment by firmianay** [comment]
Mac上离线模型一样无法使用，等了很久都没反应
