### ISSUE TITLE
多屏幕支持

### ISSUE THREAD

**Issue by xushengfeng** [xushengfeng/eSearch#59]
eSearch 使用 [robotjs](https://github.com/octalmage/robotjs) 实现截屏，但robotjs似乎不再维护，也没有多屏截屏，没有 Wayland 桌面环境的支持。

值得高兴的是，已经有大佬使用 rust 与 node 绑定实现多屏和 Wayland 截屏:tada:[nashaofu/node-screenshots](https://github.com/nashaofu/node-screenshots)。感谢大佬，感谢开源。

进度：
- [x] 主屏幕截屏
- [x] 切换屏幕
- [x] 贴图多屏
- [x] 录屏多屏
- [x] 长截屏多屏

**Comment by xushengfeng** [comment]
测试版 1.9.0-beta https://github.com/xushengfeng/eSearch/releases/tag/1.9.0-beta

**Comment by cnSchwarzer** [comment]
多屏怎么切换屏幕呢？现在Alt+C呼出还是默认第一屏，不是鼠标当前位置，希望使用鼠标位置或者占满几个屏幕

**Comment by xushengfeng** [comment]
https://github.com/xushengfeng/eSearch/releases/tag/1.9.4-beta.5

截屏内容跟随鼠标再次修复

vbox 的模拟多屏不知怎么好了，调试更方便了，该版本在我的虚拟机下表现正常 :smile:

**Comment by u-Sir** [comment]
> https://github.com/xushengfeng/eSearch/releases/tag/1.9.4-beta.5 [5acac13](https://github.com/xushengfeng/eSearch/commit/5acac13b92cf7563a794efd713d9c55c762c4713) 截屏内容跟随鼠标再次修复
> 
> vbox 的模拟多屏不知怎么好了，调试更方便了，该版本在我的虚拟机下表现正常 😄

多屏的录屏还要下一个版本吗？😭

**Comment by xushengfeng** [comment]
录屏：
b5a51f2
27c27cdf7633e2c0aeefbada46496a334f85babb
c27e8eb2213410fd991c6fb1504c99aea8f21eed

**Comment by u-Sir** [comment]
> > 录屏： [b5a51f2](https://github.com/xushengfeng/eSearch/commit/b5a51f29002b984c5a350fa9b0aa6529a98a9c39) [27c27cd](https://github.com/xushengfeng/eSearch/commit/27c27cdf7633e2c0aeefbada46496a334f85babb) [c27e8eb](https://github.com/xushengfeng/eSearch/commit/c27e8eb2213410fd991c6fb1504c99aea8f21eed)
> > https://github.com/xushengfeng/eSearch/releases/tag/1.9.5-beta.1
> 
> @xushengfeng 现在可以录制外屏了，但录制出来的位置偏移，工具条没显示在同一屏内

这个是多屏不同缩放的，现在修好了吗? @xushengfeng

**Comment by xushengfeng** [comment]
还没，另一个屏幕被家里人用了，明天才拿得回来，没法调试。1.9.5-beta.1之后的版本都是再修其他小bug

**Comment by u-Sir** [comment]
> 还没，另一个屏幕被家里人用了，明天才拿得回来，没法调试。1.9.5-beta.1之后的版本都是再修其他小bug

最新的测试版，多屏还是有问题。这里补充下其它问题 @xushengfeng 
![20221228_200450](https://user-images.githubusercontent.com/93647031/209809884-1d58f55e-e608-4947-81c2-6f44e17a7b2e.jpg)
![20221228_200509](https://user-images.githubusercontent.com/93647031/209809915-c3b2be5d-b390-4aef-af45-63ed970093d5.jpg)

**Comment by xushengfeng** [comment]
@u-Sir 我继续尝试修复： d69ae7664c4f00612d1ad254ba883a07e1ec29db
你这个其他问题是指录制栏偏移吗？我在测试中没有发现

**Comment by u-Sir** [comment]
> @u-Sir 我继续尝试修复： [d69ae76](https://github.com/xushengfeng/eSearch/commit/d69ae7664c4f00612d1ad254ba883a07e1ec29db) https://github.com/xushengfeng/eSearch/releases/tag/1.9.7-beta.5 你这个其他问题是指录制栏偏移吗？我在测试中没有发现

是的。最新的测试版，录制出来的位置还是偏移的

**Comment by xushengfeng** [comment]
@u-Sir 好像是视频预览出了问题，保存应该是正常裁切的
我在 830348d87feac33c9ef333045c8cc91d817e3151 修复了预览错位，你可以更新到 https://github.com/xushengfeng/eSearch/releases/tag/1.9.7-beta.7 看看

**Comment by u-Sir** [comment]
> @u-Sir 好像是视频预览出了问题，保存应该是正常裁切的 我在 [830348d](https://github.com/xushengfeng/eSearch/commit/830348d87feac33c9ef333045c8cc91d817e3151) 修复了预览错位，你可以更新到 https://github.com/xushengfeng/eSearch/releases/tag/1.9.7-beta.7 看看

好的，现在正常了，现在就剩下录制工具条总是出现在主屏幕上这个问题了，加油👍

**Comment by xushengfeng** [comment]
@u-Sir 你屏幕的分辨率、缩放以及**位置**都是什么设定

**Comment by u-Sir** [comment]
> @u-Sir 你屏幕的分辨率、缩放以及**位置**都是什么设定，录制工具条出现在主屏幕时框选大小和位置是怎么样的（一个例子就行）

![图片](https://user-images.githubusercontent.com/93647031/210131046-6b78506d-62f0-480c-a4a9-6bd09e13b3e7.png)
![图片](https://user-images.githubusercontent.com/93647031/210131050-cf2ebba9-d0ce-4344-bfda-a7bff335ec5f.png)

**Comment by u-Sir** [comment]
@xushengfeng 对了每次在非主屏上录制，录制工具条都是贴着主屏顶端。

**Comment by xushengfeng** [comment]
e7e1436 修了 https://github.com/xushengfeng/eSearch/releases/tag/1.9.7-beta.8
