### ISSUE TITLE
OCR报错

### ISSUE THREAD

**Issue by GJKen** [xushengfeng/eSearch#6]
使用快捷键 alt+c 截图选框并按下 ocr 按钮报错

> Error: Command failed: CHCP 65001 && cd C:\Users\Administrator\AppData\Roaming\eSearch\ocr\ppocr_model && C:\Users\Administrator\AppData\Roaming\eSearch\ocr\ppocr.exe --det_model_dir=inference/ch_PP-OCRv2_det_infer --rec_model_dir=inference/ch_PP-OCRv2_rec_infer --char_list_file=ppocr_keys_v1.txt --image_dir=C:\Users\ADMINI~1\AppData\Local\Temp\eSearch\ocr.png
> 
> 
> --------------------------------------
> 
> C++ Traceback (most recent call last):
> 
> --------------------------------------
> 
> Not support stack backtrace yet.
> 
> ----------------------
> 
> Error Message Summary:
> 
> ----------------------
> 
> NotFoundError: Cannot open file inference/ch_PP-OCRv2_det_infer/inference.pdmodel, please confirm whether the file is normal.
> 
>   [Hint: Expected static_cast<bool>(fin.is_open()) == true, but received static_cast<bool>(fin.is_open()):0 != true:1.] (at C:\home\workspace\Paddle_release\paddle\fluid\inference\api\analysis_predictor.cc:1119)

**Comment by xushengfeng** [comment]
尝试在 设置-文字识别（OCR）-离线OCR-删除离线OCR，然后再下载

**Comment by GJKen** [comment]
> 

还是不行

**Comment by GJKen** [comment]
![image](https://user-images.githubusercontent.com/69197105/178395886-7d53bacf-bf76-4607-bd3a-d5e30b860553.png)
在线OCR也有报错

**Comment by xushengfeng** [comment]
> ![image](https://user-images.githubusercontent.com/69197105/178395886-7d53bacf-bf76-4607-bd3a-d5e30b860553.png) 在线OCR也有报错

这好像还是离线OCR

**Comment by xushengfeng** [comment]
安装OCR时会有一个 Microsoft Visual C++ 的弹窗，安装了吗？

**Comment by GJKen** [comment]
> 安装OCR时会有一个 Microsoft Visual C++ 的弹窗，安装了吗？

没有 我点击下载离线OCR的时候只看到网络在波动 下载完成之后啥也没发生

**Comment by GJKen** [comment]
我定位了下下载路径 是这个吗
C:\Users\Administrator\AppData\Roaming\eSearch\ocr\cp15e.exe

**Comment by xushengfeng** [comment]
> > 安装OCR时会有一个 Microsoft Visual C++ 的弹窗，安装了吗？
> 
> 没有 我点击下载离线OCR的时候只看到网络在波动 下载完成之后啥也没发生 我以为下载完成就算成功了 我的 Windows 已经安装了Microsoft Visual C++

在`C:\Users\Administrator\AppData\Roaming\eSearch\ocr\`下找到`cp15e.exe`运行安装

**Comment by GJKen** [comment]
> > > 安装OCR时会有一个 Microsoft Visual C++ 的弹窗，安装了吗？
> > 
> > 没有 我点击下载离线OCR的时候只看到网络在波动 下载完成之后啥也没发生 我以为下载完成就算成功了 我的 Windows 已经安装了Microsoft Visual C++
> 
> 在`C:\Users\Administrator\AppData\Roaming\eSearch\ocr\`下找到`cp15e.exe`运行安装
> 

刚刚我试过了 提示已经安装

**Comment by xushengfeng** [comment]
所以还是报错吗

看看`\ocr\ppocr_model\inference\ch_PP-OCRv2_det_infer`文件夹下有没有`inference.pdmodel`

**Comment by GJKen** [comment]
> 所以还是报错吗
> 
> 看看`\ocr\ppocr_model\inference\ch_PP-OCRv2_det_infer`文件夹下有没有`inference.pdmodel`

![image](https://user-images.githubusercontent.com/69197105/178410332-f6bbdd76-3cdb-4f27-a873-a93f5760f53b.png)
有的

**Comment by xushengfeng** [comment]
是issue的那个还是乱码的那个？

复制Command failed:后面的命令一直到ocr.png到命令提示符运行看看？

**Comment by GJKen** [comment]
issuce 那个是离线报错

**Comment by GJKen** [comment]
> 是issue的那个还是乱码的那个？
> 
> 复制Command failed:后面的命令一直到ocr.png到命令提示符运行看看？


issuce 那个是离线报错

运行能成功识别到文字欸

**Comment by xushengfeng** [comment]
就是说，软件提示错误，但命令行能正确识别

我知道了，应该是软件的问题，我会继续排查bug

**Comment by GJKen** [comment]
对的

**Comment by SongTong98** [comment]
大神好，与这位老哥一样的问题

**Comment by xushengfeng** [comment]
https://wwt.lanzouv.com/ifymC07rlkmd

能试一下这个补丁版的离线ocr能正常运作吗？是免安装模式的，解压后就可以运行了

**Comment by GJKen** [comment]
> https://wwt.lanzouv.com/ifymC07rlkmd
> 
> 能试一下这个补丁版的离线ocr能正常运作吗？是免安装模式的，解压后就可以运行了

> Error: Command failed: CHCP 65001 && cd C:\Users\Administrator\AppData\Roaming\eSearch\ocr\ppocr_model && C:\Users\Administrator\AppData\Roaming\eSearch\ocr\ppocr.exe --det_model_dir=inference\ch_PP-OCRv2_det_infer --rec_model_dir=inference\ch_PP-OCRv2_rec_infer --char_list_file=ppocr_keys_v1.txt --image_dir=C:\Users\ADMINI~1\AppData\Local\Temp\eSearch\ocr.png
> 
> --------------------------------------
> 
> C++ Traceback (most recent call last):
> 
> --------------------------------------
> 
> Not support stack backtrace yet.
> 
> ----------------------
> 
> Error Message Summary:
> 
> ----------------------
> 
> NotFoundError: Cannot open file inference\ch_PP-OCRv2_det_infer/inference.pdmodel, please confirm whether the file is normal.
> 
>   [Hint: Expected static_cast<bool>(fin.is_open()) == true, but received static_cast<bool>(fin.is_open()):0 != true:1.] (at C:\home\workspace\Paddle_release\paddle\fluid\inference\api\analysis_predictor.cc:1119)

**Comment by xushengfeng** [comment]
那再试一下在设置-离线OCR中指定
det模型：
C:\Users\Administrator\AppData\Roaming\eSearch\ocr\ppocr_model\inference\ch_PP-OCRv2_det_infer
rec模型：
C:\Users\Administrator\AppData\Roaming\eSearch\ocr\ppocr_model\inference\ch_PP-OCRv2_rec_infer

**Comment by GJKen** [comment]
报错信息
![image](https://user-images.githubusercontent.com/69197105/178667495-d72ab41e-4123-4b87-b1ff-0b3d0d1b1b22.png)

**Comment by jjjyyyllll** [comment]
> 那再试一下在设置-离线OCR中指定 det模型： C:\Users\Administrator\AppData\Roaming\eSearch\ocr\ppocr_model\inference\ch_PP-OCRv2_det_infer rec模型： C:\Users\Administrator\AppData\Roaming\eSearch\ocr\ppocr_model\inference\ch_PP-OCRv2_rec_infer

一样报错 [报错](http://pic.rmb.bdstatic.com/bjh/60450503658c692151b4a49201c562ff.png)

**Comment by jjjyyyllll** [comment]
离线报错  软件下载或者用eSearch-OCR  
设置det模型 和 rec 模型 还是一样报错

**Comment by jjjyyyllll** [comment]
> https://wwt.lanzouv.com/ifymC07rlkmd
> 
> 能试一下这个补丁版的离线ocr能正常运作吗？是免安装模式的，解压后就可以运行了

你这个补丁版 也很神奇。 放到桌面上 用离线OCR正常  放到其他盘就是如上的报错了

**Comment by xushengfeng** [comment]
我明白了，因为系统原因，相对路径设置错误，这就修

**Comment by xushengfeng** [comment]
https://wwt.lanzouv.com/iGw5a07s01if
补丁版2

不出意外的话应该正常

**Comment by GJKen** [comment]
> https://wwt.lanzouv.com/iGw5a07s01if 补丁版2
> 
> 不出意外的话应该正常

OK了 能成功显示OCR内容

**Comment by xushengfeng** [comment]
太好了，正式修复版将在下一版本上

**Comment by GJKen** [comment]
> 太好了，正式修复版将在下一版本上

感谢修复

**Comment by jjjyyyllll** [comment]
> https://wwt.lanzouv.com/iGw5a07s01if 补丁版2
> 
> 不出意外的话应该正常

OK 目前正常了
