### ISSUE TITLE
Coding的提议

### ISSUE THREAD

**Issue by alex8088** [xushengfeng/eSearch#61]
你的项目非常棒，参考学习了，提几点Coding的提议

- npm scripts `electron-vite` 可增加 `--ignoreConfigWarning`  flag， 忽略 缺省 preload 的警告
- 使用 `pnpm + electron-builder`, 最好增加 一个 `.npmrc` 文件 内容 `shamefully-hoist=true` 避免打包依赖可能缺省问题，这一点electron-builder也有提及
- renderer下的 tsconfig 是不是改进统一使用 root下的 tsconfig.web

**Comment by xushengfeng** [comment]
很不错的建议，学习了。
