### ISSUE TITLE
图片上传中……请等候

### ISSUE THREAD

**Issue by heitumo** [xushengfeng/eSearch#62]
苹果
master, develop 都有尝试过

百度
<img width="794" alt="image" src="https://user-images.githubusercontent.com/12490954/196317307-aa35faba-dcd5-40db-81be-1def5737ce56.png">

谷歌
图片上传中……请等候
<img width="796" alt="image" src="https://user-images.githubusercontent.com/12490954/196317214-e1ef6cdb-d5e7-4ad2-b3f9-3ccf06cbae28.png">

想尝试默认谷歌以图搜图先， 不知道结果是否还会一样的 因为先百度默认先，再选择谷歌，百度没有上传成功导致->图片上传中……请等候? 

[ERROR:socket_manager.cc(127)] Failed to resolve address for stun.services.mozilla.com., errorcode: -105
[ERROR:socket_manager.cc(127)] Failed to resolve address for stun.services.mozilla.com., errorcode: -105
[ERROR:socket_manager.cc(127)] Failed to resolve address for stun.services.mozilla.com., errorcode: -105
[ERROR:socket_manager.cc(127)] Failed to resolve address for stun.services.mozilla.com., errorcode: -105

谢谢

**Comment by heitumo** [comment]
请问 是这样食用的吗？

![食用eS](https://user-images.githubusercontent.com/12490954/196852327-2f0dcaa9-470f-4b6d-aa5a-a1381e4d8241.gif)

浏览器下 以图搜图 可以找到不少结果的
🙏

**Comment by xushengfeng** [comment]
你的截屏似乎没生效，软件截不到屏幕，所以以图搜图无效。你给了软件访问屏幕的权限吗？

**Comment by xushengfeng** [comment]
你的截屏似乎没生效，软件截不到屏幕，所以以图搜图无效。你给了软件访问屏幕的权限吗？

**Comment by heitumo** [comment]
应该没有， 但是同时 软件也没有提示需要， 
请问苹果系统下，需要确认什么权限已经给予了呢？ （系统选项中软件名字没有出现）

**Comment by xushengfeng** [comment]
系统偏好设置-屏幕录制-隐私 勾选 eSearch

如果你是从源代码编译，勾选 electron

**Comment by heitumo** [comment]
下载编译好的。可以了食用了。 但是 无法食用 cli 了 。eSearch支持 cli 
esearch 和 e-search 都没有反应。

```
zsh: command not found: esearch
x@xnoMacBook-Pro eSearch % e-search
zsh: command not found: e-search
x@xnoMacBook-Pro eSearch %
```

先关这个 （🙏）
