### ISSUE TITLE
1.9.0 beta 快捷键设置选项重复，图还裂了🤣

### ISSUE THREAD

**Issue by u-Sir** [xushengfeng/eSearch#64]
无法保存快捷键设置，设置项重复
设置-快捷键

**屏幕截图**
![图片](https://user-images.githubusercontent.com/93647031/196969493-1447d9c5-5f8c-467d-83f8-9dfc31f0fe06.png)

**设别和软件信息**

-   操作系统和具体版本: 
版本	Windows 11 专业版
版本	22H2
安装日期	‎2022/‎9/‎21
操作系统版本	22621.675
体验	Windows Feature Experience Pack 1000.22634.1000.0

-   屏幕参数:
![图片](https://user-images.githubusercontent.com/93647031/196969931-d5d9390d-38da-411c-8bd5-15b57af8dc02.png)

-   软件版本: 1.9.0 beta 

**更多信息**

**Comment by xushengfeng** [comment]
已修： 53a8ac5f3771a2f44ecea796ba7aaf4a7834f8d2 1dbedba8db8db23f2009b688e02b1e5146ba369b
