### ISSUE TITLE
优化多屏截图逻辑

### ISSUE THREAD

**Issue by u-Sir** [xushengfeng/eSearch#65]
1.9.0 beta 现在是先框选位置 -> 截两个屏，在主屏幕中显示其中一个 -> 按 z 切换屏幕截图，这流程好怪。
建议改成：获取鼠标所有屏幕 -> 直接在该屏幕上进行框选，编辑。鼠标移动到另一个屏幕时就切换过去，这样就不用截多个屏幕的图了，而且符合直觉。
当然，最好像 windows 下的 `win shift s` 一样在多个屏幕中自由选择，然后进行截图或录屏。

**Comment by xushengfeng** [comment]
先选择再截屏会降低效率，还是实时跟随鼠标位置较好

**Comment by azxcvbnmazx** [comment]
版本1.91，多屏确实有问题，我是三屏幕，一个 1080分辨率，一个2.5K分辨率，一个4K分辨率，按 Alt+C，只能截4K屏幕上的内容。

**Comment by xushengfeng** [comment]
> 版本1.91，多屏确实有问题，我是三屏幕，一个 1080分辨率，一个2.5K分辨率，一个4K分辨率，按 Alt+C，只能截4K屏幕上的内容。

按<kbd>z</kbd>键打开侧栏，应该有所有屏幕吧

**Comment by cnSchwarzer** [comment]
@xushengfeng 目前无法跟随鼠标位置，请问是意料之中的吗，就是鼠标在任何位置Alt+C，展示的都是第一个屏幕的内容，必须每次都按Z

**Comment by xushengfeng** [comment]
> @xushengfeng 目前无法跟随鼠标位置，请问是意料之中的吗，就是鼠标在任何位置Alt+C，展示的都是第一个屏幕的内容，必须每次都按Z

似乎是意料之外的，我现在的电脑都是截取鼠标所在屏幕，我再测试一下。你升级到最新版本（1.9.3）了吗

**Comment by cnSchwarzer** [comment]
> > @xushengfeng 目前无法跟随鼠标位置，请问是意料之中的吗，就是鼠标在任何位置Alt+C，展示的都是第一个屏幕的内容，必须每次都按Z
> 
> 似乎是意料之外的，我现在的电脑都是截取鼠标所在屏幕，我再测试一下。你升级到最新版本（1.9.3）了吗

刚才升测试版OK了

**Comment by u-Sir** [comment]
> > > @xushengfeng 目前无法跟随鼠标位置，请问是意料之中的吗，就是鼠标在任何位置Alt+C，展示的都是第一个屏幕的内容，必须每次都按Z
> > 
> > 
> > 似乎是意料之外的，我现在的电脑都是截取鼠标所在屏幕，我再测试一下。你升级到最新版本（1.9.3）了吗
> 
> 刚才升测试版OK了

试了下，轮流在两个屏幕截图时，偶尔会出现下图这种默认框选全屏，直接到了移动框选位置那一步。下图我移动了下
![20221128_220355](https://user-images.githubusercontent.com/93647031/204297621-d1d72f93-bd11-4284-9141-1d9609e986a2.jpg)

**Comment by xushengfeng** [comment]
这个是截不到屏幕了取色器才全黑（实际上是`#00000000`，也就是透明的，默认省略透明数字了）
截不到屏这个我试着修
“直接到了移动框选位置那一步”是不是因为开启了“记忆框选大小”，还是伴随着截不到屏出现的呢

**Comment by xushengfeng** [comment]
1e497bba7c322540049c175e645ccdcff31ab51e
目前只简单实现了更改画面，窗口未跟随移动
窗口跟随鼠标切换是否必要？还是我直接加个开关

**Comment by cnSchwarzer** [comment]
> [1e497bb](https://github.com/xushengfeng/eSearch/commit/1e497bba7c322540049c175e645ccdcff31ab51e) 目前只简单实现了更改画面，窗口未跟随移动 窗口跟随鼠标切换是否必要？还是我直接加个开关

感觉没有太大必要……

**Comment by u-Sir** [comment]
> 这个是截不到屏幕了取色器才全黑（实际上是`#00000000`，也就是透明的，默认省略透明数字了） 截不到屏这个我试着修 “直接到了移动框选位置那一步”是不是因为开启了“记忆框选大小”，还是伴随着截不到屏出现的呢

“记忆框选大小” 是关闭的

**Comment by u-Sir** [comment]
> [1e497bb](https://github.com/xushengfeng/eSearch/commit/1e497bba7c322540049c175e645ccdcff31ab51e) 目前只简单实现了更改画面，窗口未跟随移动 窗口跟随鼠标切换是否必要？还是我直接加个开关

可以加个开关，不过感觉缩放问题又会是一个坑😂，还是先修 Bug

**Comment by xushengfeng** [comment]
我发现不切换窗口会使得切换截屏毫无意义
因为各种操作都是在当前窗口上完成的，截屏内容又跟随鼠标，所以到底还是原来截屏图像:joy:
刚刚试着让窗口一起跟随，发现代码不生效
想着初始截屏时窗口和内容**已经跟随鼠标**了，之后再跟随鼠标会带来误触等问题
所以我决定把初始截屏跟随鼠标搞好就行了
关于多屏的反馈到 #59 ，便于大家集中讨论
