### ISSUE TITLE
最新版的离线OCR怎么用？指定位置不行，难道配置要重置？

### ISSUE THREAD

**Issue by jjjyyyllll** [xushengfeng/eSearch#66]
**描述**

**重现步骤**

1. 在……界面
2. 点击
3. 发生错误或不是我预想的那样

**需求**
本应该显示 xxx，需要 xxx 新功能来代替

**屏幕截图**
可选

**设别和软件信息**

-   操作系统和具体版本: [如： Win11 专业版 pre 25158]
-   屏幕参数: [如：15.6 寸，1920*1080，1.25 倍缩放]
-   软件版本: [如：1.7.2]

**自由描述**

**Comment by xushengfeng** [comment]
默认开箱即用的，如果要自定义ocr模型，需要把他们转成onnx模型，再把检测模型、识别模型、字典一起选中拖入设置-ocr-离线ocr下添加模型
