### ISSUE TITLE
win11 不知为啥打不开

### ISSUE THREAD

**Issue by Tree-New-Beee** [xushengfeng/eSearch#70]
**描述问题**

**重现步骤**

1. 在……界面
2. 点击
3. 发生错误

**本应该**
显示 xxx

**屏幕截图**
可选

**设别和软件信息**

-   操作系统和具体版本: [如： Win11 专业版 pre 25158]
-   屏幕参数: [如：15.6 寸，1920*1080，1.25 倍缩放]
-   软件版本: [如：1.7.2]

**更多信息**

**Comment by Tree-New-Beee** [comment]
主页面都打不开

**Comment by xushengfeng** [comment]
他有弹出什么报错信息吗

**Comment by Tree-New-Beee** [comment]
需要什么运行环境吗，安装以后页面都打不开，只提示“esearch已在后台运行”但是点击任务栏的图标没有反应，然后图标也自己关了

**Comment by xushengfeng** [comment]
我试过在刚安装的 win11 22h2 中安装正常运行
唯一需要的运行环境是vc_redist.x64，也就是 https://github.com/xushengfeng/eSearch/releases/tag/1.9.1 里的那个文件，安装vc++2015-2020用，这个在安装包里附带了，安装时应该会装上的。如果没装上，应该会报错才对。
右键任务栏图标，像设置这些也打不开吗？

**Comment by Tree-New-Beee** [comment]
vc_redist.x64安装了的，我又试了一次，还是打不开，任务栏图标也是，点击图标没反应，会自己关掉

**Comment by xushengfeng** [comment]
右击图标试过了吗，左键单击原本是有一个默认行为的

**Comment by Tree-New-Beee** [comment]
擦，我又按了一遍，现在能正常打开使用了，玄学。。

**Comment by Tree-New-Beee** [comment]
> 右击按钮有没有，左键左键是一个默认行为的

发现问题了，安装的时候只有安装在默认目录，或者新建一个文件夹（不能重命名）才能正常打开使用

**Comment by Tree-New-Beee** [comment]
> 右击按钮有没有，左键左键是一个默认行为的
还有就是绿色版，解压后也是打不开的，只有我上面说的那两种安装方式能正常使用

**Comment by Tree-New-Beee** [comment]
谢谢，没事了，应该是我电脑自己的问题
