### ISSUE TITLE
每次打开截图界面都会弹一个错误窗

### ISSUE THREAD

**Issue by Minelu** [xushengfeng/eSearch#71]
**描述问题**

**重现步骤**
每次唤醒截图都会弹窗

**屏幕截图**

![eSearch-2022-11-04-21-38-15-152](https://user-images.githubusercontent.com/34987057/199987412-17007725-162c-4288-84cf-7fdabd3a425a.png)

**设别和软件信息**

-   操作系统和具体版本: Win11 专业版 pre 25236

**更多信息**

**Comment by xushengfeng** [comment]
这是自动搜索的bug
临时解决方案是：在托盘右键选择截屏搜索或为截屏搜索添加快捷键

**Comment by xushengfeng** [comment]
b8243330df7297309bdc978143d3381cd64f14fb 已在代码中修复，将在下一个版本发布
