### ISSUE TITLE
截屏弹出错误弹窗，只能截到屏幕背景

### ISSUE THREAD

**Issue by mryu010101** [xushengfeng/eSearch#72]
**描述问题**
点击会弹出 windows script host的窗口，显示C:\Program“没有文件扩展”，只能截到屏幕背景。
而且不管从右下角点击图标截图或者快捷键alt+c截图，点完以后桌面图标、打开的应用窗口全都不见了，只出现桌面背景和下面开始菜单栏那条，截图截下来只有桌面背景，啥也截不到，录屏什么的也是这样，无法使用
**重现步骤**

1. 点击右下角图标，或者按快捷键alt+c都会弹出 windows script host的窗口，显示C:\Program“没有文件扩展”
2. 然后跳出来截图界面，但是这时桌面图标、打开的应用窗口全都不见了，只出现桌面背景和下面开始菜单栏那条，截图截下来只有桌面背景，啥也截不到，录屏什么的也是这样，无法使用

**本应该**
本应该不跳出C:\Program“没有文件扩展”的窗口，点击后出现正常的截图界面。

**屏幕截图**
可选
![QQ图片20221109104733](https://user-images.githubusercontent.com/117792614/200727573-c1788469-5af6-43cf-8541-6550e6995e66.png)
![QQ图片20221109104758](https://user-images.githubusercontent.com/117792614/200727850-da1e8727-cc1d-48e1-966f-df7a57a50af7.png)

**设别和软件信息**

-   操作系统和具体版本: [如： Win10 专业版 22H2 19045.2193]
-   屏幕参数: [如：27 寸，3840*2160，1.75 倍缩放]
-   软件版本: [如：1.9.1]

**更多信息**

**Comment by xushengfeng** [comment]
#71 这里有临时解决办法

**Comment by mryu010101** [comment]
> #71 这里有临时解决办法
用屏幕搜索虽然不弹窗了，但是点击后还是只会出现图1的画面，只能截到桌面背景，其他什么画面也截不到，而且在桌面背景上使用绘画工具什么的都是偏离鼠标位置的在截图范围之外。

**Comment by xushengfeng** [comment]
是不是你系统设置问题，比如设置了什么保护之类的
位置偏移按理只出现在1.9.0，你关闭缩放后还会有偏移问题吗

**Comment by mryu010101** [comment]
> 是不是你系统设置问题，比如设置了什么保护之类的 位置偏移按理只出现在1.9.0，你关闭缩放后还会有偏移问题吗

1.调成100%后，按了截图桌面背景就会变大很多，画矩形圆形没问题，画线和其他的还是会偏移。（我是双屏一个是4k屏缩放175%，一个是正常的1920*1080的屏幕100%显示，用了腾讯桌面整理，不过好像和这个没关系，把桌面整理关掉也是一样）（图1用eSearch画矩形、圆没偏移，画线段偏移到右下角，用画笔能画出一串点但是一放开画笔就消失了，不会留下痕迹）
2.截图还是只有桌面壁纸显示，我用其他截图软件都没问题，比如qq截图、微信截图、Snipaste等都是可以正常使用。（图1用eSearch桌面上啥也没了，打开的其他窗口文件夹也都看不见了，而且桌面壁纸被放大。图2用Snipaste是正常的。）

![QQ图片20221109115244](https://user-images.githubusercontent.com/117792614/200736417-2dbb32b8-5998-439c-9d5e-ad7460f49db9.jpg)
![QQ图片20221109120148](https://user-images.githubusercontent.com/117792614/200736423-b8e4e58e-d243-4e17-810e-47232dae2732.jpg)

**Comment by xushengfeng** [comment]
空白屏那个是你的另一个屏幕吧，并不是当前截屏屏幕，需要切换
偏移是出现在有缩放的屏幕还是哪个

**Comment by mryu010101** [comment]
> 空白屏那个是你的另一个屏幕吧，并不是当前截屏屏幕，需要切换 偏移是出现在有缩放的屏幕还是哪个

两个屏幕现在都调成100%显示，画东西还是会偏移，然后用画笔改了颜色画东西还是灰色的线，改颜色没用，画圆形矩形改颜色有用

**Comment by xushengfeng** [comment]
切换屏幕后画板没刷新，我尽量修复

**Comment by mryu010101** [comment]
> 

66666666……      还有是不是能修复下我在2屏截屏的（2屏是主屏幕），为什么按完alt+c截屏就会自己去截1屏的画面去了，搞的以为是只剩背景了其他东西都突然消失了，哈哈。

**Comment by xushengfeng** [comment]
都会修的

**Comment by xushengfeng** [comment]
形状缩放修复： ed28476
尝试多屏识别修复： fd92751
