### ISSUE TITLE
希望支持http代理

### ISSUE THREAD

**Issue by hxse** [xushengfeng/eSearch#74]
好像只能走系统代理, 希望可以支持设置http代理

**Comment by xushengfeng** [comment]
应该支持http的 https://www.electronjs.org/zh/docs/latest/api/session#sessetproxyconfig 在 设置-代理-proxyRules 填入url就可以了

**Comment by shileiye** [comment]
![image](https://user-images.githubusercontent.com/7674680/201554701-7769cadb-f4b0-4e2a-aad1-d25fb802431c.png)


> 应该支持http的 https://www.electronjs.org/zh/docs/latest/api/session#sessetproxyconfig 试试在 设置-代理-proxyRules 填入url

关键是没地方输入···

**Comment by xushengfeng** [comment]
1.9.3 更了界面

**Comment by shileiye** [comment]
![image](https://user-images.githubusercontent.com/7674680/201556728-192a9f7e-9a2b-4c35-859c-83ffcb758a22.png)


> 1.9.3 更了界面

嗯，成功。
