### ISSUE TITLE
录制 GIF 时，若自定义文件名会导致崩溃

### ISSUE THREAD

**Issue by u-Sir** [xushengfeng/eSearch#75]
正常录制 GIF ，保存时自定义文件名，

![图片](https://user-images.githubusercontent.com/93647031/201655343-722e1d11-a0cc-4f5c-8a48-ed2fade93cb7.png)

**Comment by xushengfeng** [comment]
你是不是自定义文件名时把`.gif`去掉了

**Comment by u-Sir** [comment]
> 

默认的也没带 `.gif` 啊😂

**Comment by xushengfeng** [comment]
7c4c636e245753e146b72e5c022504e2fb19b28c
