### ISSUE TITLE
多屏截图的效果图不是全屏显示

### ISSUE THREAD

**Issue by u-Sir** [xushengfeng/eSearch#76]
在外接显示器上截图，效果图不是全屏显示
![20221116_192816](https://user-images.githubusercontent.com/93647031/202169116-d831d715-425e-4135-909e-9b3098d2e90e.jpg)

**设别和软件信息**

![图片](https://user-images.githubusercontent.com/93647031/202169421-948f59ad-79bb-460a-82ad-95e91996967d.png)
![图片](https://user-images.githubusercontent.com/93647031/202169549-b32ba3c2-1432-4cbe-b76e-835e5e3b1b12.png)
![图片](https://user-images.githubusercontent.com/93647031/202169660-9761b0d0-ced5-4f4f-a93f-4b2ac0d68c08.png)

**Comment by xushengfeng** [comment]
https://github.com/xushengfeng/eSearch/releases/tag/1.9.4-beta.1 尝试修复……

**Comment by u-Sir** [comment]
> https://github.com/xushengfeng/eSearch/releases/tag/1.9.4-beta.1 尝试修复……

截图正常，但录屏位置会偏移

**Comment by u-Sir** [comment]
> https://github.com/xushengfeng/eSearch/releases/tag/1.9.4-beta.1 尝试修复……

补充下：好像在另一个屏截第二次时的缩放是正常的，如果一个屏截图一次就会把另一个屏的缩放比例应用到当前屏幕，导致不匹配，建议截图前先识别鼠标所在屏幕的缩放比例

**Comment by xushengfeng** [comment]
录屏是录制框偏移还是生成的视频偏移？现在录制暂不支持多屏
缩放应用我会试着再修的

**Comment by u-Sir** [comment]
> 录屏是录制框偏移还是生成的视频偏移？现在录制暂不支持多屏 缩放应用我会试着再修的

生成时偏移，不知跟上面说的缩放比例不是实时检测的相关不

**Comment by xushengfeng** [comment]
移动到 #59 讨论，便于集中问题
