### ISSUE TITLE
“关于”命令无法跳转到正确位置

### ISSUE THREAD

**Issue by tswwe** [xushengfeng/eSearch#77]
**描述问题**

在主页面中点击菜单栏上的“帮助”→“关于”，会以新窗口的形式弹出软件的设置页面，但不会自动定位到“关于”章节。

**本应该**

直接在主页面中切换到设置页面，并且自动定位到“关于”章节。

**屏幕截图**

![eSearch-20221125-111559](https://user-images.githubusercontent.com/36465489/203893455-912ece1e-8d42-4016-820a-1bd079707ac6.gif)

**设别和软件信息**

-   操作系统和具体版本: Windows 10 专业工作站版 22H2 19045.2251
-   屏幕参数: 14 寸，1366*768
-   软件版本: 1.9.4 Beta1

**Comment by xushengfeng** [comment]
c5cff5de8a808fac31d7d4426467555a70aafaae 已在代码修复
