### ISSUE TITLE
“自动识别”设置项的意义不明确

### ISSUE THREAD

**Issue by tswwe** [xushengfeng/eSearch#78]
**描述问题**

软件的“设置\快捷键\全局\自动识别”这一项，从字面上看不懂其功能（帮助文档中也无对应内容），而其实际功能似乎和“截屏搜索”是一样的。

**本应该**

猜测这一项的名称应改成“自动搜索”，功能也应调整为和软件托盘右键菜单、帮助文档中的“自动搜索”一致。

**屏幕截图**

![image](https://user-images.githubusercontent.com/36465489/203896220-78667e53-7a6b-4518-8976-71dfeef6ea6b.png)

**设别和软件信息**

-   操作系统和具体版本: Windows 10 专业工作站版 22H2 19045.2251
-   屏幕参数: 14 寸，1366*768
-   软件版本: 1.9.4 Beta1

**Comment by xushengfeng** [comment]
b59165e 已在代码中更新
“自动识别”即判断当前是否选中文字，如果有，则搜索选中文字，反之使用截屏搜索
