### ISSUE TITLE
希望添加几个功能

### ISSUE THREAD

**Issue by hao3han3** [xushengfeng/eSearch#8]
图片编辑功能：
1. 标号功能：对图片上的元素做1/2/3等标号，可以选择标号的样式（圆形或直角方形，圆角方形等，立体的还是平面的），大小，背景色，字体颜色，边框（如可能），可以选择从第几个标号开始标记（有时候不一定从1开始）
2. 裁剪功能：裁剪图片尺寸到鼠标框选的大小。
3. 园，方框等可以取消内部的背景色，边框颜色和线宽可选
4. 箭头功能：
- 可以选择填充色，箭头大小等
- 透明度和边框元素修改选项可酌情考虑添加
- 圆弧箭头，自定义线条箭头等可以考虑添加

其他：
1. 快捷键无法添加“Print Screen"等特殊按键。我个人习惯使用Ctrl+Print来调出默认的截图功能
2. 暗色主题下，部分字体和元素显示不清晰，需要优化一下配色
3. 选框最好添加一个勾，表明选上了。而不是直接一个颜色切换，不容易理解到底那种状态是选上还是没选上。此问题在暗色主题下很突出。
4. 编辑功能条，建议直接做到一次菜单中，而不是要二次调出。

先就这么多，你这个软件太新了，功能一点点加吧。
加油。
以上。

**Comment by xushengfeng** [comment]
感谢你的建议！

图像编辑：
1. 标号会考虑的
2. 是不是与框选冲突了呢？或者说框选本身就具有裁切功能，保存后只保存框选内的图片
3. 编辑栏从上往下数第4个就是背景色、边框色、边框宽度调节按钮
4. 箭头功能很实用，我会考虑添加

其他：
1. 是bug #10
2. 样式还会优化的
3. 同上
4. 编辑功能条是哪个

**Comment by hao3han3** [comment]
你好：
2. 是不是与框选冲突了呢？或者说框选本身就具有裁切功能，保存后只保存框选内的图片
不会。毕竟不可能一次性就截取到所需要的，正好的内容。需要有一个二次修改的机会。

4. 编辑功能条是哪个
![20220714-112110-147](https://user-images.githubusercontent.com/46490355/178891161-8505c442-357a-47b7-9d3c-f70df89ceb27.jpg)
看上图。

顺便说下，我对截图的需求：截图完成后，直接在截图的区域做编辑（或者弹出编辑对话框，对图片做编辑）；编辑完成后自动复制到剪切板，并保存到指定文件夹。
这个需求是从阿香婆截图开始的，后来因为新版本各种问题，切换到Snipaste，再到FastStone Capture，最后稳定到xshare（上图就是用xshare编辑的）。
个人感觉阿香婆的早期版本（<=4）很顺手，基本上没有大的问题。新版本各种bug，中文支持也开始掉链子。已经舍弃了。
snipaste个人没用习惯，faststone功能有缺失（没有标号功能，这个很重要）。
xshare虽然我需要的功能有，包括使用习惯也可以无限接近阿香婆，但是多了图片上传功能，可以说是一个不纯粹的截图软件
至于这款，我个人还是很喜欢的，优化一下，应该还是很受欢迎的。

补充1：如果可以的话，自带ffmpeg，或者提供一键自动下载选项（类似OCR的离线包处理方式）。
补充2:提供右键“使用esearch编辑图片”选项，或者是“发送到”->“esearch编辑器”。两个方案都可以。

以上
谢谢

**Comment by xushengfeng** [comment]
二次修改的话，先截全屏也可以吧，然后我会考虑 右键“使用esearch编辑图片” ，这样就可以用 eSearch 进行二次编辑了（现在用系统自带的裁切也可以代替一点吧）

这个软件不只是截屏软件，还有 OCR、以图搜图等功能，截图只是为其他功能获取屏幕信息的工具。所以编辑功能条目前不会直接展现。但是在 设置-框选-框选后默认操作 那里可以设定框选后自动弹出编辑栏。

即复制又保存文件，同时进行两个操作这样的功能应该不会加。

我会考虑FFmpeg下载方法的化简。

**Comment by xushengfeng** [comment]
序号、箭头、二次编辑在[1.7.3](https://github.com/xushengfeng/eSearch/releases/tag/1.7.3)实现

**Comment by hao3han3** [comment]
好的。
多谢。
这个issue我也顺便关闭了，因为主要诉求基本上都实现了。
