### ISSUE TITLE
支持空格键预览文件。

### ISSUE THREAD

**Issue by SONGjiemo** [xushengfeng/eSearch#80]
目前对 空格键预览文件需求还是非常需要的。
预览格式：图片格式JPG,PNG,等等格式，文档格式：word,ppt,excel

空格键找文档还是非常方便的，希望支持他。
具体步骤，
选择文件后按着空格键，可以直接预览文件。

**Comment by xushengfeng** [comment]
你可以尝试其他软件
现在的eSearch是主要还是围绕“识屏”和“搜索”两方向开发的，并不是全能工具箱，所以这个功能就不加了。
