### ISSUE TITLE
划词搜索功能设计建议

### ISSUE THREAD

**Issue by SONGjiemo** [xushengfeng/eSearch#81]
1、在浏览器划词或者选择词后长按3s后出现一个面板进行选择。
2、该面版有百度搜索、必应搜索、谷歌搜索、百度站内搜索、谷歌站内搜索、以图搜图等等。
3、可以自由配置网址搜索串添加个人网址。

**Comment by xushengfeng** [comment]
划词误触可能要考虑一下，目前支持划词后通过快捷键“选中搜索”
选中搜索后会弹出主页面，应该就是你说的面板了
主页面搜索引擎可以在 设置-搜索 里配置

**Comment by SONGjiemo** [comment]
> 

你好，能不能搞个设置。划词后直接出现这个面板。快捷键还是不方便

**Comment by SONGjiemo** [comment]
你好，我的想法是  划词后出现这种快捷界面
![image](https://user-images.githubusercontent.com/46627639/205519897-c55c27d1-0319-43b6-95ca-6e7c3108a0a2.png)
希望可以作为参考。

**Comment by qwertyue** [comment]
不知道这个是不是bug 
我在win10上 使用版本为1.9.7的eSearch，但是该 版本无法使用快捷键触发选中搜索

**Comment by xushengfeng** [comment]
建议用其他快捷面板软件（如quicker）唤起eSearch，目前暂无再搞个面板的打算
