### ISSUE TITLE
语言切换问题

### ISSUE THREAD

**Issue by sywy52pojie** [xushengfeng/eSearch#82]
**描述问题**
切换到其他语言后点击“使用系统语言”，“重启软件以生效”依然是其他语言
**重现步骤**

1. 在“设置-语言”界面
2. 点击“Русский”
3. “重启软件以生效”变为俄语
4. 点击“使用系统语言”（系统语言为简体中文）
5. “重启软件以生效”依然是俄语，没有变回简体中文

**本应该**
显示 “重启软件以生效”

**设别和软件信息**
-   操作系统和具体版本:Win10
-   软件版本:1.9.4-beta.2
![eSearch-2022-12-02-14-15-43-771](https://user-images.githubusercontent.com/114221053/205227944-538379dc-8636-4e4e-9267-d92da78dfb5d.gif)

**Comment by xushengfeng** [comment]
bd460987483defe2a4dccee792367bb39e73798e 已修
