### ISSUE TITLE
希望能提供更改工具栏显示的位置选项

### ISSUE THREAD

**Issue by Tree-New-Beee** [xushengfeng/eSearch#85]
呼出工具栏默认在屏幕左边，但是习惯从左往右下拉取截图范围，这样左边起点总是会被工具栏遮挡，如果默认在右边显示或者工具栏可以直接移动就更好了，这样就不会遮挡

**Comment by xushengfeng** [comment]
右键按住可以拖动工具栏
默认位置这个功能可以加

**Comment by xushengfeng** [comment]
已在代码中实现 d00d66aeb39c2bcd02c3e74c2a6efe8264076708
