### ISSUE TITLE
录屏问题

### ISSUE THREAD

**Issue by sywy52pojie** [xushengfeng/eSearch#87]
**描述问题**
防大屏幕后录屏白屏
**重现步骤**

1. 点击alt+c
2. Ctrl+滚轮调整屏幕大小
3. 点击录屏
4. 白屏
**本应该**
正常录制

**屏幕截图**
![63969ad37e1fa_63969ad3a02a9](https://user-images.githubusercontent.com/114221053/206952490-d4590a11-e577-4011-80b9-f44098385558.gif)

**设别和软件信息**

-   操作系统和具体版本:win10专业版
-   软件版本: 1.9.4

**Comment by xushengfeng** [comment]
f523c01f15af93a9f8ad854b8f240a785248cf91 已在代码中修复
