### ISSUE TITLE
Ubuntu下1.9.4版本appimage启动和设置非常缓慢

### ISSUE THREAD

**Issue by wzk0** [xushengfeng/eSearch#88]
**描述**

在Ubuntu 22.04.1下使用V1.9.4版appimage启动和设置非常缓慢.

**重现步骤**

1. 启动, 使用了33秒加载出界面;
2. 设置, 点击设置选项后, 间隔很久才反应.

> 其他electron软件从未遇见这种情况.

**屏幕截图**

https://user-images.githubusercontent.com/89891126/207309301-97a77533-030a-4258-8841-8f9994dc7d78.mp4

**设备和软件信息**

-  系统: Ubuntu 22.04.1 LTS;
-  内存: 32Gb;
-  CPU:  i7-7700;
-  GPU: GeForce GTX 1060.

**自由描述**

Windows平台的小伙伴似乎没有这种情况...不确定是否是因为自己的设备问题.

**Comment by xushengfeng** [comment]
你看看其他appimage程序也是这样吗

**Comment by wzk0** [comment]
> 你看看其他appimage程序也是这样吗

**重现步骤**中已经说明了, 其他electron软件都是正常的, 非常流畅.

eSearch只在**启动和设置时**缓慢, 具体功能使用时暂无发现缓慢现象.

**Comment by xushengfeng** [comment]
appimage打包软件整体启动慢在我的arch linux下重现了，我会试着优化
但设置界面启动是正常的，其他界面（如主页面）启动是否流畅？

**Comment by wzk0** [comment]
> appimage打包软件整体启动慢在我的arch linux下重现了，我会试着优化 但设置界面启动是正常的，其他界面（如主页面）启动是否流畅？

感谢优化! 所有缓慢的地方都在视频中显示了. 刚刚测试了主页面, 打开过程也非常缓慢, 但使用正常. 同时补充一点, 关闭**设置页面窗口**的速度也很缓慢.

**Comment by wzk0** [comment]
测试了一下deb, 启动速度很快, 但是在加载**设置**页面的时候响应速度还是很慢, 在**设置**页面选择选项时, 也有同样的情况. 这点和appimage一样.

**Comment by xushengfeng** [comment]
我尝试做了一系列针对设置的优化 d0f442f2972026b68adf46ab24a530d09f75aec2 4188c949890b1d2f4cb995b444cb5b4b46aed2fd 57eb09b7e5d5a4aa3fdec941055968a049aaa345
初步分析是加载多语言包导致主进程和设置界面加载过慢，截屏和文字编辑界面没有加载多语言，所以正常。
目前设置界面只是检测到简体中文环境就不加载多语言包，已发布一个预览版更新：https://github.com/xushengfeng/eSearch/releases/tag/1.9.8-beta.2 可以看一下设置界面的开启是否得以加快

**Comment by wzk0** [comment]
> 我尝试做了一系列针对设置的优化 [d0f442f](https://github.com/xushengfeng/eSearch/commit/d0f442f2972026b68adf46ab24a530d09f75aec2) [4188c94](https://github.com/xushengfeng/eSearch/commit/4188c949890b1d2f4cb995b444cb5b4b46aed2fd) [57eb09b](https://github.com/xushengfeng/eSearch/commit/57eb09b7e5d5a4aa3fdec941055968a049aaa345) 初步分析是加载多语言包导致主进程和设置界面加载过慢，截屏和文字编辑界面没有加载多语言，所以正常。 目前设置界面只是检测到简体中文环境就不加载多语言包，已发布一个预览版更新：https://github.com/xushengfeng/eSearch/releases/tag/1.9.8-beta.2 可以看一下设置界面的开启是否得以加快

测试了一下 系统语言是简体中文 但是速度似乎没有得到明显的优化 启动速度和设置界面的响应还是比较慢

**Comment by wzk0** [comment]
> https://github.com/xushengfeng/eSearch/releases/tag/1.9.8-beta.4 我在测试了一下，怀疑是保存设置会占用资源，而我设定了每次点击都会触发保存设置。现在我设定为设置界面失去焦点后保存，设置界面的响应应该会快一点。 启动速度还在想办法优化

这个版本的设置界面响应正常了 不过启动和加载主页面的时候还是缓慢

**Comment by wzk0** [comment]
> https://github.com/xushengfeng/eSearch/releases/tag/1.9.8-beta.5 这次优化了关闭设置界面的速度

和beta4的情况一样🥲

**Comment by xushengfeng** [comment]
整体启动尝试优化 500d39ccb4650bb9b0324bbed42033cc356c83a6 ，版本第一次运行可能会慢点，后面就快了
主页面窗口的展示我目前只能做到这个速度了 :(

**Comment by wzk0** [comment]
> 整体启动尝试优化 [500d39c](https://github.com/xushengfeng/eSearch/commit/500d39ccb4650bb9b0324bbed42033cc356c83a6) ，版本第一次运行可能会慢点，后面就快了 主页面窗口的展示我目前只能做到这个速度了 :( https://github.com/xushengfeng/eSearch/releases/tag/1.9.8-beta.6

感谢! 这个版本界面加载速度可以, 不过启动程序的速度似乎还是没有改善..

**Comment by xushengfeng** [comment]
后面启动几次也没有提升吗

**Comment by wzk0** [comment]
> 后面启动几次也没有提升吗

没有..

**Comment by xushengfeng** [comment]
那目前我也优化不了了……
主程序启动不像其他界面启动那样频繁，目前的对于主程序启动的优化先搁置一下吧 :(

**Comment by wzk0** [comment]
> 那目前我也优化不了了…… 主程序启动不像其他界面启动那样频繁，目前的对于主程序启动的优化先搁置一下吧 :(

OK 谢谢啦!
