### ISSUE TITLE
深色模式下设置里的"框选后默认操作"图标看不见，换成浅色才能看得见

### ISSUE THREAD

**Issue by KiritoGuugk** [xushengfeng/eSearch#89]
**描述问题**
1.深色模式下设置里的"框选后默认操作"图标看不见，换成浅色才能看得见

**重现步骤**

1. 在……界面
2. 点击
3. 发生错误

**本应该**
显示 xxx

**屏幕截图**
![image](https://user-images.githubusercontent.com/35999227/207358914-04e2b75a-de54-40a6-b7a6-aa23ea315e92.png)

**设别和软件信息**

-   操作系统和具体版本: archlinux
-   屏幕参数: 2560x1600
-   软件版本: 1.9.5-beta.1

**更多信息**

**Comment by xushengfeng** [comment]
已在代码中修复： 290b9d2c66c4639b88c40001bbc9c364ad8a19b6
