### ISSUE TITLE
“图像编辑” 功能提议

### ISSUE THREAD

**Issue by KiritoGuugk** [xushengfeng/eSearch#90]
1. **图像编辑** 能否设置成点击一级菜单的铅笔图标就默认自动变成画笔（或者在设置里的默认选项）可以直接开始画，而不是需要先点击 **图像编辑** 再点击 **自由绘画** ，然后再点击 **画笔** 。（感觉大部分时候涉及图像编辑都仅仅是需要画笔这个功能）

2. **图像编辑** 功能下的二级菜单经过第一次鼠标点击之后在鼠标悬浮的情况下就会切换，当选择二级菜单比较靠下的功能，三级菜单比较靠上的功能时容易误触，能否在设置中添加只有鼠标点击才会切换二级菜单的选项

**设别和软件信息**

-   操作系统和具体版本: archlinux
-   软件版本: 1.9.5-beta.1

**请自由地描述你的提议（如有多个不同方向的建议，最好分成几个issue）**

**Comment by xushengfeng** [comment]
14642865da5c00d8934b89185a57f5e32fa44ec0 二级菜单也是可以直接点击的，我在代码中加入了二级菜单“自由绘画”按钮点击后默认启用画笔
dc168196816cf41e95d39ba2468cf5971be522a9
