### ISSUE TITLE
默认保存路径

### ISSUE THREAD

**Issue by KiritoGuugk** [xushengfeng/eSearch#91]
1. 设置里能否增加像快速截图一样的 **默认保存路径** 使普通截图无需自行选择路径，选择完截图区域就能直接保存截图

**设别和软件信息**

-   操作系统和具体版本: archlinux
-   软件版本: 1.9.5-beta.1

**请自由地描述你的提议（如有多个不同方向的建议，最好分成几个issue）**

**Comment by xushengfeng** [comment]
已添加到代码： 569800dfde71d0f480c794e973d23e64d4cef80f 9509e58b728cf7ce774cf177d106d6e5b8616cda
