### ISSUE TITLE
截图发生错误，出现两个屏幕

### ISSUE THREAD

**Issue by EDGARDOCRU** [xushengfeng/eSearch#92]
**描述问题**
截图发生错误，出现两个屏幕

**屏幕截图**
(https://user-images.githubusercontent.com/106093687/207538030-26943518-04d9-4f1c-8d1f-6383abdc9ef9.png)

**设别和软件信息**

-   操作系统和具体版本: [如： Windows 11 家庭中文版  22621.963]
-   屏幕参数: [如：17.2 寸，1920*1080，]
-   软件版本: [如：1.7.4]

**Comment by xushengfeng** [comment]
是最新版本吗，屏幕使用缩放了吗，经常发生这个错误吗

**Comment by jinsuichen** [comment]
这个问题在设置中调整全局缩放即可解决
