### ISSUE TITLE
取色器定位不准

### ISSUE THREAD

**Issue by sywy52pojie** [xushengfeng/eSearch#93]
**描述问题**
放大屏幕后移动屏幕，取色器显示像素串位
**重现步骤**

1. ail+c
2. 放大屏幕
3. 移动屏幕（滚轮、方向键或空格）
4. 取色器串位

**本应该**
显示 鼠标指针的像素

**屏幕截图**
（过大传不上来）
https://www.aliyundrive.com/s/6k9BovcHXPG

**Comment by xushengfeng** [comment]
我还没做移动导航，滚轮和方向键导航应该被屏蔽的。
我下一步将完善滚轮和方向键导航。

**Comment by xushengfeng** [comment]
禁止原生滚动 fcb2c6c958d8ff053de653e938c45ef39c446575
滚轮导航（按`shift`加滚轮水平滚动） 29dbedb1f203ad3956ddce70971a4c801b87cbf3
