### ISSUE TITLE
希望增加任意形状截图功能和更精细的窗口截屏功能

### ISSUE THREAD

**Issue by sywy52pojie** [xushengfeng/eSearch#94]
1、希望增加窗口截屏功能
2、希望增加任意形状截图功能（三角形、圆形、☆五角星或手绘图形）
以上功能出现在Windows“截图和草图”里（win+shift+s）
3、希望增加 屏幕文字复制 功能，方便搜索和翻译（此功能出现在软件textify里：软件开源地址https://github.com/m417z/Textify    ）
4、希望增加软件内自动更新功能，手动卸载+下载+安装非常麻烦+繁琐

**Comment by xushengfeng** [comment]
窗口截屏可以在设置里开启自动框选
任意形状有点难搞，不过还是先添加到开发路线
eSearch有屏幕文字识别，识别完后默认选中所有文字，可以点击编辑栏的复制按钮或通过复制快捷键复制
我会尝试做自动更新的

**Comment by sywy52pojie** [comment]
非常感谢您的回复！
对于您的项目，我还是有些**### 建议**
以下为第一点的补充：

此项目中的自动框选功能为OpenCV 进行图像边缘识别，似乎不能准确的截取完整的窗口
例如：截取浏览器完整窗口：
此软件：
![esearch](https://user-images.githubusercontent.com/114221053/208339404-f5e7cf8a-62ce-491f-b32d-aad4c819350c.gif)
（由于窗口边框颜色不统一，无法准确识别截取完整窗口，框选效率相对较低）
其它软件（微信）：
![微信](https://user-images.githubusercontent.com/114221053/208339646-3c289b52-a847-4d2d-9eb2-0e4f45b8b618.gif)（窗口识别，效率相对高）

综上所述，希望您添加窗口截屏功能，提高效率。
如果此软件无需此功能或已存在此功能，请忽略此条回复

**Comment by xushengfeng** [comment]
准确率这点确实做得不太好
真正的窗口识别已经在考虑了，但需要调用系统api，可能做起来没那么快

**Comment by xushengfeng** [comment]
软件更新其实是不用卸载的，不过我现在加了增量更新，一般只用更新几MB a5d341e95ecac5b502bade08f905f6ecdf117218

**Comment by sywy52pojie** [comment]
> 软件更新其实是不用卸载的，不过我现在加了增量更新，一般只用更新几MB [a5d341e](https://github.com/xushengfeng/eSearch/commit/a5d341e95ecac5b502bade08f905f6ecdf117218)

请问作者，增量更新功能如何使用？
以前在设置-关于里多了增量更新的功能，却时有时无的，不知道是不是网络原因，
![image](https://user-images.githubusercontent.com/114221053/209918129-cb4b5362-191f-4364-88e8-1a43c467cf0b.png)
最近发现最新测试版（[1.9.7-beta.4](https://github.com/xushengfeng/eSearch/releases/tag/1.9.7-beta.4)）里却没了 app 
本人小白一枚，望多指教😊

**Comment by xushengfeng** [comment]
> > 软件更新其实是不用卸载的，不过我现在加了增量更新，一般只用更新几MB [a5d341e](https://github.com/xushengfeng/eSearch/commit/a5d341e95ecac5b502bade08f905f6ecdf117218)
> 
> 请问作者，增量更新功能如何使用？ 以前在设置-关于里多了增量更新的功能，却时有时无的，不知道是不是网络原因， ![image](https://user-images.githubusercontent.com/114221053/209918129-cb4b5362-191f-4364-88e8-1a43c467cf0b.png) 最近发现最新测试版（[1.9.7-beta.4](https://github.com/xushengfeng/eSearch/releases/tag/1.9.7-beta.4)）里却没了 app 本人小白一枚，望多指教blush

抱歉，有点忙，忘记上传，多亏你提醒
增量更新确实是检测是否有`app`这个文件来更新的

**Comment by sywy52pojie** [comment]
作者您好，最新版本[1.9.8](https://github.com/xushengfeng/eSearch/releases/tag/1.9.8)似乎又少了增量更新的app😅

**Comment by xushengfeng** [comment]
https://github.com/xushengfeng/eSearch/releases/tag/1.10.0-beta.4 添加系统级别窗口识别

**Comment by xushengfeng** [comment]
任意形状截屏已在 https://github.com/xushengfeng/eSearch/releases/tag/1.12.0-beta.5 实现，最新版为 https://github.com/xushengfeng/eSearch/releases/tag/1.12.0-beta.8
