### ISSUE TITLE
快捷键长按添加一堆

### ISSUE THREAD

**Issue by kadxka** [xushengfeng/eSearch#97]
设置里添加快捷键，长按Ctrl（或其他）会添加一串
![63a11540b125d_63a11540e1719](https://user-images.githubusercontent.com/121008319/208563022-4f4c23d8-8767-412e-82a7-eae184e3ce86.gif)

**Comment by xushengfeng** [comment]
已在代码中修复 209cdb881362f19da5de410043768bb42a66ddd9
